assets/js/backbone/apps/apply/views/apply_view.js
- Fix render Education and fix if statement
#2882,#2879
=> Education Dos and Review Education

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/auth/controller.js, api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/login/views/login_view.js
- Fix issue where community administrators cound not approve
or delete opportunities
#3034
=> Community Admins

assets/js/backbone/apps/apply/views/apply_view.js
- Fix code syntax causing application load error in IE
=> Fix IE error

assets/js/backbone/apps/apply/views/education.js
=> Review Education

assets/js/backbone/apps/apply/views/education.js
- Fix progress bar state on Education page when adding/editing
#2789
=> Fix Progress Bar State on DoS Education

assets/js/backbone/apps/apply/templates/apply_add_reference_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js
- Fix progress bar state on Experience page when adding/editing
- Fixed issue with radio buttons showing data on Reference edit
- Updated historyApplicationStep function
#2920, #2789
=> Fix Progress Bar State on DoS Experience

README.md, api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/auth/controller.js, api/community/controller.js, api/opportunity/controller.js, api/opportunity/service.js, api/user/service.js, assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/login/views/login_view.js, migrations/20190116184607-trim-tagentity-values.js, package-lock.json, package.json
Prepare a release package candidate for a production deployment for March 8th 2019.
=> Prepare for production release

api/application/dao.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js
- Fix Security clearence dropdown
- Update application experience query
#2920
=> DOS experience

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/experience.js
- Fix securityClearence Id setting
#2920
=> Experience Dos

api/application/controller.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_add_language_template.html, assets/js/backbone/apps/apply/templates/apply_language_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/language.js, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
=>  Department of State: Languages 

README.md, api/opportunity/service.js, package-lock.json, package.json
- Correct database query for task listing
#3105
=> Newly created community opportunities are not displaying in search

api/opportunity/service.js
- Correct database query for task listing
#3105
=> Merge change from ticket 3105

assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/styles/layouts/internship.scss
- Add classes to start and end date form groups
- Update CSS for start and end date validation
- Add languages data to Review page
#2878, #2882
=>  Update HTML and CSS on Add Experience Page

api/admin/controller.js, api/admin/dao.js
- Refactor long running database query for user export
#3109
=> User export timeout

README.md, api/admin/controller.js, api/admin/dao.js, package-lock.json, package.json
- Refactor long running database query for user export
#3109
=> Merge user export timeout updates

assets/js/backbone/apps/apply/views/apply_view.js
- Update to start characterCount when saving from step 4
#2881
=> Start Character Count for Statement of Interest

api/application/service.js, assets/js/backbone/apps/apply/templates/apply_experience_template.html
- Fix country subdivision issue
- Fix display data drawer
#2921
=> Dod  Experience

assets/js/backbone/apps/apply/templates/apply_ineligible_citizenship_template.html, assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/js/backbone/browse-app.js, assets/styles/layouts/internship.scss
- Update display of experience types if overseas experience is No
#2882
=> Update Experience Display on Review Application

assets/js/backbone/apps/apply/templates/apply_add_reference_template.html, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/templates/apply_ineligible_gpa_template.html, assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/js/backbone/apps/apply/views/apply_view.js
- Fix reference type not selecting when edit
#2921
=> Dos reference

assets/styles/layouts/internship.scss
- Update CSS to prevent titles from bouncing on hover in IE11
#2789
=> Update CSS For Progress Bar Titles

api/application/service.js
- Fix reorder issue
- Fix delete issue
#2785
=> Student internship selection

assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/apply/templates/apply_experience_template.html
- Add link
- Update reference card
#2921,#2878
=> Dod Experience and Reference

api/application/service.js
- Added code to autofix issues where multiple program selections
get the same sort order value
#2785
=> Student internship program selection

assets/js/backbone/apps/apply/templates/apply_education_preview_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js
- Update education preview page
- check if conditions for edit and delete button
#2882
=> Dod Review application

assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/js/backbone/apps/apply/templates/apply_statement_template.html, assets/js/backbone/apps/apply/views/apply_view.js
- Add Statement of Interest height check for Review page
#2882
=> Add Statement Height Check to Review Application

assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/app/pages/_task.scss, assets/styles/component/card/opportunity.scss, assets/styles/layouts/internship.scss
- Update CSS for skill labels
#3061
=> Align Skills Left Under Desired Skills Header

api/application/controller.js, api/application/dao.js, api/application/import.js, api/application/service.js, api/auth/profile.js, api/autocomplete/dao.js, assets/js/backbone/apps/apply/templates/apply_education_template.html, assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js, assets/js/backbone/apps/apply/views/transcripts.js, assets/styles/layouts/internship.scss, config/settings/auth.js, environment.json, migrations/20190306194954-create-error-log-table.js, migrations/20190308132818-add-transcript-id-to-application.js
- Select transcript from a list of uploaded transcripts
- Upload transcript via USAJOBS profile
- Refresh list of transcripts after upload via USAJOBS
- Display selected transcript name on application review page
#2919
=> DoS internship transctipt selection

assets/js/backbone/apps/apply/templates/apply_summary_template.html
- Add content to Next Steps Page
#3126
=> Add content to Next Steps Page

assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/tasks/search/templates/internship_filters.html, assets/js/backbone/apps/tasks/search/templates/internship_search_cycle_box.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Remove Filter programs
-  Default setting to Us Dos
#3138
=> Remove program area default to unpaid

assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/apply/views/experience.js, assets/js/backbone/apps/internships/show/templates/internship_view.html
- Remove go to saved part
#3058
=> Remove Go to saved from create opportunity

assets/js/backbone/apps/apply/templates/apply_congratulations_template.html
- Update link on Submission Confirmation to open in a new window
#3153
=> Update Link on Submission Confirmation to Open in a New Window

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/templates/apply_language_template.html, assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js, assets/js/backbone/apps/apply/views/experience.js, assets/js/backbone/apps/apply/views/language.js, assets/js/backbone/apps/tasks/show/views/task_item_view.js
- Update progress bar state according to user actions
#2789
=> Student application progress bar

assets/js/backbone/apps/apply/views/language.js
- Fix edit button on language section of application process
#2995
=> Student application language edit

api/user/controller.js, api/user/dao.js, api/user/service.js, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/nav/views/nav_view.js, assets/js/backbone/apps/profiles/home/internships/controllers/internships_controller.js, assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html, assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_activity_view.js, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Add data for interenships applied to
- Add HTML
- Update Sort
- Add link for updating applications applied to
- Add modal when updating applications
- Collapse submenu when navigating to /apply/
- Update nav
#2899, #3049
=> Student Landing Page: View applications

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Update office to be optional/disabled if bureau has no offices
#3012
=> Don't Require Office if Bureau Doesn't Have Offices

assets/js/backbone/apps/apply/views/experience.js
- Fix issue in IE preventing changes to experience data
#2878
=> Student internship application save experience

assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html
=> Update description under logo

api/v1/application/controller.js, api/v1/application/dao.js, api/v1/application/service.js
Updating ApplicantSummary query for UI #2965
=> Updating ApplicantSummary query for UI

migrations/20190314141900-import-new-bureau-data.js, utils/bureau-data.js, utils/bureau-data.json
=> Load final bureau/office/post data

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Fix issue where you cannot edit an internship when cycle closes
=> Internship edit

assets/styles/layouts/internship.scss
- Updated CSS to add back the 3rem bottom margin for alerts
#2877
=>  Department of State: Ineligible Citizenship

api/opportunity/service.js, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/templates/apply_ineligible_gpa_template.html, assets/js/backbone/apps/apply/views/experience.js
- Fix date Is present selected
#2878
=> Department of State Experience

api/auth/passport.js, api/v1/application/controller.js, api/v1/application/dao.js, api/v1/application/service.js, assets/js/backbone/apps/apply/templates/apply_education_template.html, assets/js/backbone/apps/apply/views/education.js, config/settings/auth.js, environment.json, migrations/20190314201845-add-transcript-name-to-application-table.js, utils/tamper-proof.js
Updates for ApplicantSummary query #2965
=> Updates for ApplicantSummary query

api/user/dao.js, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html, assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js, assets/js/backbone/browse-app.js, assets/styles/layouts/profile.scss
- Update message in modal shown before application is updated
- Remove submitted at date when application is saved
- Update HTML to show applications applied to
#3049
=>  Update Modal Message

assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Comment out lines relating to choosing a program
- Comment out lines hiding bureaus initially
- Fix ESLint issues
#3183
=> Bug: Bureau/Office/Post filters no longer displaying

api/user/controller.js, api/user/dao.js, api/user/service.js, assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js, migrations/20190318163525-add-saved-task-table.js
- Added a table for recording saved opportunities
#2901
=> Save opportunities

assets/js/backbone/apps/profiles/home/internships/views/internships_view.js, assets/styles/component/card/opportunity.scss
- Add margin-bottom so action links and skills pills no longer overlap
#3186
=> Bug: Skills pills sometimes run into duplicate on Create Internship

assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html
=> Fix bureau office Name

assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Updated sorting for applied and saved internship opportunities
- Updated column headers for saved internship opportunities
- Updated status for saved internship opportunities
#2900
=> Student landing page: Saved

assets/js/backbone/apps/apply/views/experience.js
- edit page fix adding zero infront of start and end month if its two digits
#2878
=> Dod Experience

api/v1/application/dao.js, api/v1/application/service.js, assets/js/backbone/apps/apply/templates/apply_experience_template.html
Update ApplicantSummary query for overseas data #2965
=> Update ApplicantSummary query for overseas data

api/v1/application/controller.js, api/v1/application/dao.js, api/v1/application/service.js, api/v1/opportunity/dao.js, migrations/20190313193317-add-is-removed-to-application-task.js, package-lock.json
Added removeApplicationTask service
Added isRemoved to application_task table
Updated applicant summary query
TFS - 36500
=> Applicant Review - Card Removal

assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Fix index change- if its Reordering data
#2912
=> Update Application After Submit from the Student Landing Page

assets/js/backbone/apps/apply/views/education.js
- Fix issue preventing saving of education when no transcripts have
been uploaded to a user's profile
#3222
=> Empty transcript list

api/v1/application/dao.js, api/v1/opportunity/dao.js
Updating ApplicantSummary and internshipSummaryQuery
=> Updating ApplicantSummary and internshipSummaryQuery

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js
- Add character counters on Experience page
#3177
=> Department of State: Experience Questions- Add character limit

assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html, assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html
- Update default text when there are no applications
- Update display to "internship" when there is only one 
application
#3223
=> Student landing page application view updates

assets/js/backbone/apps/apply/views/experience.js
- Fix validation --page not continuing without adding other section
#2878
=> Dos: Experience

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/experience.js
-  Remove Total length of overseas experience when check other and Add it if "Yes" selected
- Fix validation and remove validation when check other
#3178
=> Department of State: Remove question from drawer

api/v1/application/dao.js, api/v1/opportunity/dao.js
updating taskListApplicationQuery and applicantSummary query
=> updating taskListApplicationQuery and applicantSummary query

assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/styles/layouts/internship.scss
- Display length of overseas experience in review page
- display other type specify in the review page
#3255,#3256
=> Display length of overseas experience on the review page andDisplay description of "Other" on the Review Page

api/user/dao.js, api/user/service.js, assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Updated column headings
- Updated column data
#3230
=> Landing page: Update Saved section

api/v1/application/service.js
36758: Added Tamper proofing to API call
=> 36758: Added Tamper proofing to API call

api/v1/opportunity/dao.js
updating internshipSummaryQuery query
=> updating internshipSummaryQuery query

assets/js/backbone/apps/apply/templates/apply_review_template.html
- Header  change for "other" specify
#3255
=> Change header

api/application/service.js, assets/js/backbone/apps/internships/show/views/internship_view.js
- Update modal content when clicking apply on internship opportunity
#3220
=> Update Modal Content When Clicking Apply

assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Update default sort on landing page saved section
#3230
=> Update Default Sort On Landing Page Saved Section

api/v1/opportunity/controller.js, api/v1/opportunity/dao.js, api/v1/opportunity/service.js
updates to internshipListQuery and internshipSummaryQuery
=> updates to internshipListQuery and internshipSummaryQuery

api/v1/opportunity/controller.js, api/v1/opportunity/dao.js, api/v1/opportunity/service.js
updates to internshipListQuery
=> updates to internshipListQuery

api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js
- Add "update application" logic for internship view page
- Add modal for already submitted application
#3205
=> Update application process when viewing an internship already applied to

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/internships/show/templates/internship_view.html
- Allow state to be null when saving
- Check for state value before trying to display state
#3279
=> Bug: Countries with no state will not save

assets/js/backbone/apps/nav/views/nav_view.js, assets/js/backbone/apps/profiles/edit/views/profile_skills_view.js
- Update nav to show when adding or editing skills
#3290
=> Fix Bug Where You Lose Navigation Editing Skills

assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html
- Update the location display for saved virtual internships
#3230
=> Update Location Display For Virtual Internships

api/opportunity/service.js
- Fix issue preventing opportunity creators from being able to manage
their opportunities.
#3280
=> Fix edit functionality for creators of opportunities

api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_task_view.js
- Update internship statuses
- Update Admin Community Opportunity table to show updated statuses
#3000
=> Update Internship Statuses

api/admin/dao.js, api/admin/service.js, api/cycle/controller.js, api/cycle/service.js, api/opportunity/service.js, assets/js/backbone/apps/admin/templates/admin_community_cycle_form_template.html, assets/js/backbone/apps/admin/templates/admin_community_cycle_template.html, assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_community_cycle_edit_view.js, assets/js/backbone/apps/admin/views/admin_community_cycle_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/components/modal.js, assets/js/backbone/components/modal_template.html, assets/js/backbone/entities/cycles/cycle_model.js, assets/styles/component/modal.scss, assets/styles/layouts/admin-dashboard.scss
- Add new cycle management dashboard
- Add ability to create new cycle from management dashboard
- Update CSS for dashboard
- Add ability to edit existing cycles
- Add ability to delete cycles that have not started accepting applicantions
#2835
=>  Community cycle management 

assets/js/backbone/apps/apply/templates/apply_transcript_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js
- Add render function to back button
#3243
=> Fix Back button in apply page

assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html
- Update preview page to suppress office header if no office selected
#3280
=> Suppress Office/post Header

api/application/controller.js, api/application/service.js, api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/apply/templates/apply_program_template.html, assets/js/backbone/apps/apply/templates/apply_saved_list_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/program.js, assets/js/backbone/apps/profiles/home/internships/templates/internships_template.html, assets/styles/layouts/internship.scss
=> Department of State: Select internship opportunities from Saved Search &

assets/js/backbone/apps/apply/templates/apply_education_template.html, assets/js/backbone/apps/apply/templates/apply_transcript_template.html, assets/js/backbone/apps/apply/views/education.js
- Show error when no education is added
#3251
=> Education section of apply is required

api/opportunity/dao.js
- Take out repeated queries and clean up module.exports section
#3308
=> Dao reordeing issue

assets/js/backbone/apps/apply/templates/apply_transcript_template.html
- Update HTML for transcript error message
#3252
=> Update HTML For Transcript Error Message

assets/js/backbone/apps/apply/templates/apply_review_template.html
- Update Review page to add text if there are no references
#3253
=> Add No References Text To Review Page

api/user/dao.js, assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Updated column names
- Updated data displayed in columns
#3229
=> Update Applied Section On Landing Page

assets/js/backbone/apps/apply/templates/apply_transcript_template.html, assets/js/backbone/apps/apply/views/education.js
- Add validation for refresh transcripts
#3252
=> Transcript - should be required

api/cycle/controller.js, elastic/dao.js, elastic/service.js
- Reindex opportunities when a cycle is updated
#2835
=> Community cycle management

assets/js/backbone/apps/apply/views/education.js
- Fix education loose data when save
#3334
=> Bug: Lose education data when education added

api/v1/opportunity/dao.js
Updating CommunitByTaskAndEmail query to accept any case email
=> Updating CommunitByTaskAndEmail query to accept any case email

assets/js/backbone/apps/apply/templates/apply_add_education_template.html, assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Remove "for this internship" from error messages
#3333
=> Bug: Change title of country error message

assets/js/backbone/apps/admin/templates/admin_community_cycle_form_template.html, assets/js/backbone/apps/admin/templates/admin_community_cycle_template.html, assets/js/backbone/apps/admin/views/admin_community_cycle_edit_view.js, migrations/20190404171612-add-review-dates-to-cycle-table.js, migrations/20190404172146-add-secondary-application-url-to-cycle-table.js
- Add review start and end date range to cycles
- Add secondary application link to cycles
#3048
=> Community cycle updates

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Remove the "the" in the first sentence
- Remove cancel button
#3281
=> Update text on submit alert

assets/js/backbone/apps/tasks/search/templates/internship_search_cycle_box.html
- Add "at 11:59 p.m. EST"
#3283
=> Add closing time text to the blue box on search page

environment.json
- Created a new environment variable to application environment
=> Add new environment variable

api/v1/application/controller.js, api/v1/application/dao.js, api/v1/application/service.js, migrations/20190404181409-add-template-name-to-task-list-application.js
Ticket 36387: Added api/v1/application/updateLastContacted end point
=> Ticket 36387: Added updateLastContacted end point

api/v1/application/service.js
Ticket 36905: refactor dates for last contacted
=> Ticket 36905: refactor dates for last contacted

api/v1/opportunity/controller.js, api/v1/opportunity/dao.js, api/v1/opportunity/service.js
internshipsListQuery and internshipsArchiveListQuery updates
=> internshipsListQuery and internshipsArchiveListQuery updates

assets/js/backbone/apps/apply/templates/apply_education_template.html, assets/js/backbone/apps/apply/templates/apply_transcript_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js
- Add validation for gpa
-Limit to X.xx charectors
- set to null field if gpa '0.000'
- Update transcript validation messages
#3304
=> Application: Limit GPA to a 4.xx scale

api/application/controller.js, api/application/dao.js, api/application/service.js, assets/js/backbone/apps/apply/controllers/apply_controller.js, assets/js/backbone/apps/apply/templates/submitted_application_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/submitted_application.js, assets/js/backbone/apps/apply/views/templates.js, assets/js/backbone/apps/nav/views/nav_view.js, assets/js/backbone/apps/profiles/home/internships/templates/internships_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js, assets/js/backbone/browse-app.js, assets/js/backbone/components/modal.js, assets/js/backbone/components/modal_template.html, assets/styles/component/modal.scss, assets/styles/layouts/internship.scss
- Added new page
- Updated CSS
- Updated modal template
- Updated student home page
- Added ability to delete application
#3087
=> Withdraw Application Once Submitted

assets/js/backbone/apps/apply/views/experience.js
- Fix experience data clearing when save experience and reference
#3367
=> Bug: Experience data is cleared when I add a reference

assets/js/backbone/apps/apply/views/apply_view.js, migrations/20190410164540-update-office-names-to-office-table.js
- Add migration for spelling errors for office name
#3320
=> Update two spelling errors on Bureau/Office/post data for State

api/application/dao.js, api/application/import.js, api/application/service.js
Import profile data from OO profile on application load.
#3331
=> Apply: Skills should pull over from my Open Opps profile

assets/js/backbone/browse-app.js, assets/styles/layouts/internship.scss
- Update CSS to fix alignment of "select" and "selected"
#2788
=> Adjust CSS For Right Rail

api/application/import.js
- Rename "LookupCode" to "LookUpCode"
- Fix honor Id  if it is null from core
#3331
=> Fix imports issue for education,experience and reference

assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js
- Code clean up for education page
- Fix transcript clearing issue when save education
#3334
=> Fix Bug for clearing transcript

api/application/import.js
- Correct date issue on import when experience end date is Present
#3331
=> Fix import issue for experience

api/application/service.js, migrations/20190415190033-add-application-id-foreign-keys.js
- Add foreign keys
- Update service
#3087
=> Add foreign keys to tables

api/auth/passport.js
=> Bug: Prevent student from having admin priveleges

assets/js/backbone/apps/apply/views/submitted_application.js
- Added functionality to the Update button on Submitted application page
#3231
=> Update Process modifications

api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_task_view.js
- Fix approved status delete functionality
- Update delete  task logic
#3322
=> Bug: Admin delete of approved doesn't delete

migrations/20190418121124-update-cycle-table-schema.js
- Set cycle dates to date fields rather than timestamp fields
=> Update cycle table schema

api/notification/state.department/layout.html
- Create new folder for DoS emails
- Create new layout based on current layout
#3397
=> Create email template for SIP (Unpaid) Community

assets/styles/component/pill.scss
=> Create new pill for internship opportunity status of "Approved"

assets/js/backbone/apps/internships/show/templates/internship_share_template.txt, assets/js/backbone/apps/internships/show/views/internship_view.js
- Update subject and content of the share internship opportunity email
#3099
=> Internship email: Share internship opportunity

api/opportunity/dao.js, api/user/dao.js, assets/js/backbone/apps/apply/views/program.js
Also removed from application side rail.
#3241
=> Save: Remove from landing page once applied to end date

api/admin/dao.js, api/admin/service.js, api/notification/service.js, api/notification/state.department/internship.create.draft/template.html, api/notification/state.department/internship.create.draft/template.js, api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, api/opportunity/sql/getInternshipApplicants.sql, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/internships/show/templates/applicants_view.html, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/styles/component/card/opportunity.scss, migrations/20190419135058-add-community-email-template-table.js, migrations/20190419141501-add-dos-draft-email-template.js
- Display number of applicants for an internship on the community
admin dashboard
- Add ability for community managers to who has applied to an internship
#2905 
- Override local draft email with custom community draft email
#3093
=> Community updates

api/notification/state.department/internship.update.submitted/template.html, api/notification/state.department/internship.update.submitted/template.js, assets/js/backbone/apps/apply/views/submitted_application.js, migrations/20190419173221-add-dos-submitted-email-template.js
- Override local submitted email with custom community submitted email
#3094
=> Internship Emails: New Internship Opp Submitted

api/notification/state.department/internship.update.approved/template.html, api/notification/state.department/internship.update.approved/template.js, migrations/20190419184459-add-dos-approved-email-template.js
- Override local opened email with custom community approved email
#3095
=> Internship Email: Internship Approved

api/opportunity/service.js
- Fix error around authentication for viewing applicants list
#2905
=> Community manager view applicants

assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
- Take out link redirecting profile for community logo
#3398
=> Joint Duty Program: Default logo as Picture for Community Members

api/notification/state.department/internship.update.submitted.admin/template.html, api/notification/state.department/internship.update.submitted.admin/template.js, api/opportunity/service.js, migrations/20190419195623-add-dos-submitted-admin-email-template.js
- Override local email with custom community email
- Update service.js to override admin emails too
#3096
=> Internship Email: Submitted For Approval - Admin

app/openopps-setup.js, package-lock.json, package.json
- Added Azure Application Insights
- Removed New Relic
=> Update application monitoring

assets/js/backbone/apps/tasks/show/templates/task_progress_template.html
- Add email to top of right rail for DHS opportunities
#3399
=> Joint Duty Program: Default email

.circleci/config.yml, package.json
- Update CircleCI to use workflows
- Build changes to all non dev branches
- Build and tag all changes to dev branch
=> Update CircleCI build

gulpfile.js
- Update package publishing task
=> Update gulp file

README.md, package-lock.json
- Update version number in each file to match package version
=> Update readme and package-lock

api/application/dao.js, api/application/service.js, api/notification/layout.html, api/notification/state.department/internship.application.received/template.html, api/notification/state.department/internship.application.received/template.js, api/notification/state.department/layout.html
- Create template
- Create view
- Update service
- Correct misspelled word on both layout files
#3098
=> Internship email: Application received

gulpfile.js, package.json
- Added gulp build task to the publish task
- Updated package npm publish script definition
=> Update publish script

assets/js/backbone/apps/apply/templates/apply_summary_template.html
- Updated text for step 2
#3248
=> Update text on Next Steps page of application

assets/js/backbone/apps/admin/templates/admin_community_cycle_template.html, assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html
- Use moment.js to render our dates rather than the base JavaScript
date object
#2835
=> Update UI date rendering

assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html
- Removed erroneous closing parenthesis
=> Fix syntax error

assets/js/backbone/apps/apply/templates/apply_experience_template.html
- Add class to the Experience header
#3245
=> Apply: Add Optional beside Experience header

assets/js/backbone/apps/admin/templates/admin_community_cycle_form_template.html, assets/js/backbone/apps/tasks/search/templates/task_search_item.html
- Use moment.js to render our dates rather than the base JavaScript
date object
#2835
=> Update UI date rendering 

api/application/controller.js, api/application/service.js, api/notification/state.department/internship.application.withdraw/template.html, api/notification/state.department/internship.application.withdraw/template.js, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Add email template for withdraw application
#3100
=> Internship email: Withdraw application confirmation

api/auth/controller.js
Redirect student to search page on log in.
#3403
=> Start Students on the Search Page

api/application/controller.js, api/application/service.js, api/auth/auth.js, api/auth/passport.js, api/auth/profile.js, api/user/controller.js, assets/js/backbone/apps/tasks/search/templates/internship_search_cycle_box.html
- Implement refresh token from openid connect client library
#3237
=> OpenID Connect refresh token

assets/js/backbone/apps/apply/templates/apply_review_template.html
- Limit gpa to 2 decimal places
#3402
=> GPA should be limited to 2 decimal points on Review page

assets/js/backbone/apps/internships/show/templates/internship_view.html
- Add check for student hiring path
#3400
=> Remove Duplicate from Internship Opp. for student

assets/js/backbone/apps/internships/show/templates/internship_view.html
=> Content correction

assets/js/backbone/apps/apply/templates/apply_congratulations_template.html, migrations/20190429182334-update-bureau-name.js
- Update wording on link
#3447
=> Change wording on "What happens next?" page

assets/js/backbone/apps/apply/templates/apply_add_education_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js, assets/styles/layouts/internship.scss
- Add validation to enter 4 digit input for year
- limit Year field to 3000
#3362
=> Enforce a 4 digit year in education fields

api/application/service.js, api/cycle/service.js, assets/js/backbone/app.js, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, elastic/service.js, migrations/20190429193205-update-security-clearance-codes.js, migrations/20190430193124-update-cycle-table-schema.js, package-lock.json, package.json, utils/base-data.js
- Update security clearance code data
- Update cycle dates to enforce eastern time for display and search
- Fix tokenset issue around profile data imports
#3237
#3471
#3349
=> Sync security clearance data and fix a few bugs

assets/js/backbone/apps/apply/views/education.js
-  set  to education page  when gpa is ineligible
#2874
=> Department of State: Ineligible GPA

api/cycle/service.js
- Utilize moment timezone to format dates for eastern time before saving
to the database
#3471
=> Update cycle dates to enforce eastern time

api/community/service.js
- Utliize moment timezone library when searching for active cycles
#3471
=> Loading of active cycles

assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html
- Fix program link is not active  if apply end date today's date
#3471
=> Bug: Cycle date issues

assets/js/backbone/apps/welcome/templates/welcome_template.html
- Correct capitalization errors
#3462
=> New user flow: Federal hiring path page

api/auth/controller.js, api/auth/login.js, api/auth/passport.js, api/lookup/controller.js, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/nav/views/nav_view.js, assets/js/backbone/apps/welcome/templates/welcome_template.html, assets/js/backbone/apps/welcome/views/welcome_view.js, assets/js/backbone/browse-app.js
- Pull profile for new user to Open Opportunities
- Display new user flow welcome pages according to level and types of
profile information provided
#3461
#3462
#3463
#3464
#3466
=> New user flow

api/auth/login.js, assets/js/backbone/apps/admin/templates/admin_user_table.html, migrations/20190503123511-add-lastlogin-column-to-midasuser-table.js
=> Add last login to the Admin user display 

assets/js/backbone/apps/admin/templates/admin_user_table.html
Display username if no uri for login.gov column.
#3182
=> Admin Dashboards: Display federal email

assets/js/backbone/apps/welcome/templates/welcome_template.html
- Update content on welcome page
#3462
#3463
#3464
#3466
=> New user flow: Update content

api/auth/login.js
- Update last login on successful login attempt
#3469
=> Last login

assets/js/backbone/apps/admin/templates/admin_user_table.html
=> Add last login to the Admin user display

assets/js/backbone/apps/apply/views/apply_view.js
- Add correct footer for apply process
#3482
=> Bug: Wrong email displays in apply process footer 

assets/js/backbone/apps/admin/templates/admin_community_user_table.html, assets/js/backbone/apps/admin/templates/admin_user_table.html
Fixed header placement and verbiage.
#3182
=> Admin Dashboards: Display federal email 

api/application/import.js, assets/js/backbone/apps/apply/templates/apply_education_preview_template.html
- gpa and gpaMax  import data fix
#3481
=> Bug: GPA doesn't come over from USAJOBS to Open Opps on Education row

assets/js/backbone/apps/welcome/templates/welcome_template.html
- Add missing paragraph.
#3461
=> New User Flow - No profile page

migrations/20190507163104-update-office-name-to-office-table.js
- add migration to fix office name
#3501
=> BUG: Spelling error in post/office

api/auth/login.js
- Update account lookups during log in attempt
=> Account lookup and auto linking

assets/js/backbone/apps/apply/views/apply_congratulations_view.js
- Corrected footer on apply congratulations page
#3482
=> Bug: Wrong email displays in apply process footer

assets/styles/app/pages/_search.scss
- Update linear gradient CSS
#3285
=> Add fade to internship card

assets/js/backbone/apps/welcome/templates/welcome_template.html
=> New user flow: no hiring path selected

api/autocomplete/dao.js
- Do not allow students to be added as members of a community
#3515
=> Community - invite members

assets/js/backbone/components/modal_idle.js
- Navigate to proper logout page on session timeout
=> Session timeout

api/auth/dao.js, api/auth/service.js
- Add error logging for account create and linking functionality
#3505
=> New create account

package-lock.json, package.json
=> Update package to new release candidate

assets/js/backbone/apps/nav/templates/nav_template.html
- Remove navigation menu during new user flow
#3525
=> Remove navigation

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/internships/show/templates/internship_view.html
- Update the font size of the paragraph that was too small
#3527
=> Update Too-Small Font Size

api/community/controller.js, api/community/dao.js, api/community/service.js, assets/js/backbone/apps/admin/templates/admin_community_cycle_form_template.html, assets/js/backbone/apps/admin/templates/admin_community_form_template.html, assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/templates/admin_main_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/tasks/search/templates/internship_search_item.html, assets/js/backbone/apps/tasks/search/templates/task_search_item.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/js/backbone/apps/tasks/search/views/task_search_view.js, assets/js/backbone/entities/community/community_model.js, assets/js/backbone/global-utils.js, assets/styles/layouts/admin-dashboard.scss, package-lock.json, package.json
- Add ability for community managers to edit community data
#2837
=> Manage community data

assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/js/backbone/apps/apply/templates/apply_review_template.html
- Change modal title from invite to add
#2791
=> Change Modal Title From Invite to Add

assets/js/backbone/apps/apply/templates/apply_program_template.html, assets/js/backbone/apps/apply/views/apply_view.js
- Added disabled to Save and continue button
- Added check for empty internship slots
- Remove disabled attribute if no empty internship slots
#3518
=> Remove Ability to Save w/o Having 3 Selections

assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/js/backbone/apps/profiles/home/controllers/home_controller.js, assets/js/backbone/apps/tasks/search/controllers/task_search_controller.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/js/backbone/browse-app.js, assets/js/backbone/entities/tasks/task_model.js
- Load data asynchronously
- Remove unnecessary data loads
- Utilize Backbone client URL loading
=> Code refactoring to increase efficiency

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/internships/show/templates/internship_view.html
=> Bug: Disable Apply Button for Inactive Internship Opportunities

assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/js/backbone/apps/apply/templates/apply_program_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/browse-app.js
- Display success alert when successfully saving changes
#2837
=> Community data management

assets/js/backbone/apps/tasks/edit/templates/task_audience_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_audience_form_view.js, assets/js/backbone/global-utils.js
- Wrap text in selects that have really long options
#3344
=> Display full name in community dropdown

api/v1/opportunity/controller.js, api/v1/opportunity/dao.js, api/v1/opportunity/service.js
ticket 37341: Added get Last Updated
=> ticket 37341: Added get Last Updated

assets/js/backbone/apps/tasks/search/views/internship_search_view.js
Convert USA to United States for search to work.
#3521
=> Bug: Entering USA as a location shows no results

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/templates/apply_review_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js, migrations/20190522201733-change-column-on-experience-table.js
- On Apply step 2, Add Experience, disable postal code field if not U.S.
- Update postal_code on Experience table to allow null
- Update Experience pg Postal Code header to not show if no postal code
- Update Review page Postal Code header to not show if no postal code
#3522
=> Disable Postal Code on Foreign Country

assets/js/backbone/apps/tasks/search/templates/internship_search_cycle_box.html
- Make sure to display application end date for internships in EST
=> Internship application end date display

assets/js/backbone/apps/apply/templates/apply_experience_template.html
- Remove "Not Required" as value for security clearance in Apply Step 2
#3514
=> Remove "Not Required" as Value for Clearance

api/admin/controller.js, api/admin/dao.js, api/community/service.js, api/model/AuditTypes.js, api/opportunity/dao.js, assets/js/backbone/apps/admin/templates/admin_community_user_table.html, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/styles/layouts/admin-dashboard.scss, migrations/20190523201251-add-disabled-to-community-user.js
- Add functionality to remove members from open communities
- Add functionality to disable membership to closed communities
- Do not allow disabled members to post new opportunites to
closed community
#2836
=> Community user management

api/auth/controller.js
- Pull id token from new tokenset object created during refresh
token implementation
#3237
=> Update user logout

assets/js/backbone/apps/admin/templates/admin_announcement_template.html, assets/js/backbone/apps/admin/templates/admin_main_template.html, assets/js/backbone/apps/profiles/edit/templates/profile_skills_template.html, assets/js/backbone/apps/profiles/show/templates/profile_photo_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/component/search/search-tab.scss
- Update /admin related pages to fix accessibility issues found
#3503
=> Make Accessibility Updates

.circleci/config.yml, gulpfile.js, package.json
- Add ability to patch prior release
- Update CircleCI configuration to require approval before taging a
patched release
=> Update build configurations

package-lock.json, package.json
=> Update package for new major release candidate

assets/js/backbone/apps/apply/views/transcripts.js
- Default transcript if only one
#3537
=> Transcript: Default radio button if only one

assets/js/backbone/apps/apply/templates/apply_transcript_template.html
=> Transcripts: Modify text on the Education & Transcript page

assets/styles/component/card/opportunity.scss
- Remove extra whitespace
- Add CSS to space button back out
#3343
=> Bug: Save for later and preview buttons too close

assets/js/backbone/apps/apply/templates/apply_transcript_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/transcripts.js
- Add modal for upload transcript
- Navigate continue button to Usajobs profile document
#3539
=> Transcript: Add instructional modal

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/tasks/edit/views/task_audience_form_view.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/browse-app.js
- Show and hide loading icon
#3341
=> Display loading icons on page loads

assets/js/backbone/browse-app.js
- Add button to "Create another internship"
- Navigate to target audience page
#3552
=> Internship submit - add button to "Create another internship

assets/js/backbone/apps/tasks/search/templates/internship_search_item.html, assets/js/backbone/apps/tasks/search/templates/no_internship_search_results.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/styles/component/card/opportunity.scss
- Add save star to internship search page
- Add new oops page when no current cycle
#3561
#3519
=> DOS Oops Page/Add Save to Internship Search Page

assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Fix sorting
- Fix saving and unsaving
#3519
#3561
=> Fix Sorting/Saving and Unsaving

api/opportunity/service.js, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/browse-app.js
- Update modal text for internship create  and opportunity create
- update modal with target audience
#3552
=> Internship submit - add button to "Create another internship"

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Add a check for cycles before initalizing select2 fields
#3341
=> Check for Cycles Before Initializing

assets/styles/app/pages/_search.scss
- Fix link color and underline on oops page
#3561
=> Fix Link Display on Oops Page

api/admin/export/dao.js
- Set default sort of newest to oldest
#2613
=> Community task report export

api/v1/opportunity/dao.js, api/v1/opportunity/service.js
- Change Task List Query to conditionally pull Alternate list based on phase
#37492
=> DOS Manual Triggers Start Button Functionality

assets/js/backbone/apps/admin/views/admin_task_view.js
=> Delete Confirmation Does not display in red as per Design System 

assets/js/backbone/apps/admin/templates/admin_paginate.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/components/markdown_editor_template.html, assets/js/utils/rendererWithExternalLinkSupport.js
- Fixed a typo for the header button
- Fixed a typo for links that open in new tabs
#1166
=> Markdown tool: Header and List buttons don't work

api/user/service.js, assets/js/backbone/entities/profiles/profile_model.js
- Fix new skills not saving issue
#3598
=> Bug: New Skills will not save

assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/styles/layouts/profile.scss
- Hide search area when filters are shown
#3195
=> Mobile - Filters are not displayed properly

api/v1/cycle/controller.js, api/v1/cycle/dao.js, api/v1/cycle/service.js
37338: Manual Triggers - Primary Phase Start Email to Hiring Manager
=> 37338: Manual Triggers - Primary Phase Start Email to Hiring Manager

api/activity/service.js, assets/js/backbone/apps/profiles/home/templates/home_search_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
- Change links to /search
#2865
=> Home: Search opportunities by links

assets/js/backbone/apps/profiles/list/templates/profile_list_table.html, assets/js/backbone/apps/profiles/list/templates/profile_list_template.html, assets/js/backbone/apps/profiles/list/views/profile_list_view.js, assets/js/backbone/apps/tasks/search/templates/task_search_template.html, assets/js/backbone/global-utils.js, assets/styles/app/pages/_search.scss, assets/styles/component/_initials.scss
- Add new HTML
- Add new CSS
- Generate visual happiness
#3566
=> People: Revamp Page shell

api/auth/dao.js, api/auth/profile.js, api/user/controller.js, app/initialize-on-startup.js, elastic/dao.js, elastic/elastic-utils.js, elastic/initializer.js, elastic/service.js, elastic/user_mapping.json, elastic/user_settings.json, migrations/20190614161559-add-location-fields-to-user.js
- Establish user index for profiles
- Index federal user on log in
- Add ability to search against new elastic user index
#3569
=> Elasticsearch for people search

api/admin/export/controller.js, api/admin/export/dao.js, api/admin/export/service.js, api/auth/profile.js, api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/admin/templates/admin_task_template.html
Refactor code to reduce duplicate lines.  Fixed agency to filter on agency.  Updated queries to use agency table.
#3122
=> Opportunity .csv

api/v1/cycle/controller.js, migrations/20190617181043-update-alternate-phase-config.js
37386: Manual Triggers - Alternate Phase - Confirm Start Modal
=> 37386: Manual Triggers - Alternate Phase - Confirm Start Modal

.circleci/config.yml, gulpfile.js
First attempt at creating a gulp task to integrate a TFS build
=> TFS build task

package-lock.json, package.json
- Update package version for new sprint
=> Update package to version 7.8.2

api/user/dao.js, assets/js/backbone/app.js, assets/js/backbone/apps/profiles/list/controllers/profile_list_controller.js, assets/js/backbone/apps/profiles/list/templates/no_search_results.html, assets/js/backbone/apps/profiles/list/templates/profile_list_table.html, assets/js/backbone/apps/profiles/list/templates/profile_list_template.html, assets/js/backbone/apps/profiles/list/templates/profile_template.html, assets/js/backbone/apps/profiles/list/views/profile_list_view.js, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/js/backbone/global-search-utils.js, assets/styles/app/pages/_search.scss, assets/styles/component/card/opportunity.scss, elastic/dao.js, elastic/elastic-utils.js
- Leverage new elasticsearch endpoint api
#3568
=> People: Profile card

assets/js/backbone/apps/profiles/list/templates/profile_template.html
- Add skills to profile card
- Add class to name when no other info shows
#3568
=> Add Skills to Profile Care

assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/lib/_select2.scss
- Fix icons turning gold incorrrectly
#3614
=> Fix Incorrect Gold Icons

assets/js/backbone/apps/apply/templates/apply_add_language_template.html
=> Fix language save redirecting

assets/js/backbone/apps/profiles/list/templates/search_pills.html, assets/js/backbone/apps/profiles/list/views/profile_list_view.js
- Add pills to search page for locations
#3569
=> Profile search

api/opportunity/dao.js, assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/templates/internship_step_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, migrations/20190624132048-add-is-disabled-column-and-update-community-vsfs-to-community-table.js
- Set default to usdos community for student target audience
- Add migration to add is_defaut column and update vsfs community
- Removing community dropdown
#2838
=> Ability to change the community assigned to opportunity

assets/js/backbone/apps/profiles/list/templates/profile_list_template.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Move filter count out of cycle check
#3626
=>  Mobile-Filters not being counted in filter display

assets/js/backbone/apps/profiles/list/views/profile_list_view.js
- Complete final steps to implement pagination
#2018
=> Profile search: pagination

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
- Fix issue of extra commas for partial location data
#3597
=> Profile view: location

assets/js/backbone/apps/profiles/list/templates/profile_list_template.html
- Remove comma from keyword field
#3566
=> Remove Comma From Keyword Field

assets/js/backbone/apps/footer/templates/footer_template.html, elastic/dao.js
- Fix footer help link not open in new window
- Fix location undefined showing in internship search card
#2853, #3636
=> Bug: Prod: On internship card, location didn’t show

assets/js/backbone/apps/profiles/list/templates/profile_list_template.html, elastic/dao.js
- Add photoId to elastic user query
#3568
=> Add photoId to elastic user query

api/autocomplete/dao.js
- Add is_disabled = false to avoid language showing twice in drop down
#3603
=> Student Application: add same language twice to application 

assets/js/backbone/globals/search-utils.js, elastic/dao.js, elastic/elastic-utils.js, elastic/service.js, elastic/task_mapping.json, elastic/user_mapping.json
- Update elastic index for profiles to increase location matching
#3570
=> Profile search: location

assets/js/backbone/apps/profiles/list/views/profile_list_view.js
=> Add Sort Function to Profile Page

assets/js/backbone/apps/profiles/list/templates/profile_list_template.html, assets/js/backbone/apps/profiles/list/templates/search_pills.html, assets/js/backbone/apps/profiles/list/views/profile_list_view.js, elastic/dao.js, elastic/elastic-utils.js, elastic/user_mapping.json
- Implement sorting for profile search
#2191
=> Profile search: sort by 

assets/styles/app/pages/_search.scss
- Update CSS to explicitly declare max-width
#3568
=> Correct IE Image Width Rendering

assets/js/backbone/apps/profiles/list/templates/profile_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/styles/app/pages/_search.scss
- Show Open Opps email if no federal email
#3666
=> Profile: If no federal email, show Open Opps email

assets/js/backbone/apps/footer/templates/footer_template.html
- update link to open in new window
#3669
=> DoS Footer: Visit DoS link should open in new window

assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js
- Change Table Header label to Approve if target audience is students
#3663
=> Comm. Admin - change label from Publish to Approve

assets/js/backbone/apps/nav/templates/nav_template.html
=> Only display first name in navigation header

assets/js/backbone/apps/admin/templates/admin_community_user_table.html
- Show fed email instead of login.gov email
#3674
=> Show Fed Email on Community Admin User Dashboard

assets/js/backbone/apps/profiles/home/internships/templates/internships_template.html, assets/js/backbone/apps/profiles/home/templates/home_template.html
- Update to givenName in home and internship template
#3675
=> Modify landing page/home page to only display first name

api/autocomplete/service.js
- Show fed email in add member to community dropdown
#3673
=> Show Fed Email in Add Member to Community Dropdown

assets/js/backbone/apps/profiles/home/templates/home_template.html, assets/styles/app/pages/_dashboard.scss
- Add a ? Help link on landing page
#3613
=> Add help link on landing page

assets/js/backbone/apps/profiles/home/internships/templates/internships_template.html
- Add a ? Help link on student landing page
#3613
=> Add help link on student landing page

assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/styles/layouts/admin-dashboard.scss
- Add help link on manage sitewide opportunities page
- Add help link on manage community opportunities page
#3615
=> Add ? Help for Internship/Opportunity help content

api/auth/login.js, api/auth/service.js
- Lower case all emails when looking up accounts
#3652
=> One Profile: Linking existing Open Opportunities account

api/notification/state.department/closecyclephase.start.creators/template.html, api/notification/state.department/closecyclephase.start.creators/template.js, api/v1/cycle/controller.js, api/v1/cycle/dao.js, api/v1/cycle/service.js
Applicant Review - Closeout Email
=> 36910: Applicant Review - Closeout Email 

api/notification/state.department/closecyclephase.start.creators/template.html, api/notification/state.department/closecyclephase.start.managers/template.html, api/notification/state.department/closecyclephase.start.managers/template.js, api/notification/state.department/firstphase.start.community/template.html, api/notification/state.department/firstphase.start.community/template.js, api/v1/cycle/controller.js, api/v1/cycle/service.js
Applicant Review - Manual Trigger - Close Cycle: Hiring Manager Email Notifications
=> 37384: Applicant Review - Manual Trigger - Close Cycle: Hiring Manager Email Notifications

assets/js/backbone/apps/admin/views/admin_task_view.js, assets/styles/layouts/admin-dashboard.scss
- Update from approve to approval
#3664
=> Update Confirm Modal Title

api/community/controller.js, api/community/service.js, assets/js/backbone/apps/admin/templates/admin_community_form_template.html, assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/js/backbone/browse-app.js, assets/styles/layouts/admin-dashboard.scss
- Add new community page
- Add functionality for inserting data
-clean up some code for manage community
#3530
=> Ability for System Administrator to Add new community

assets/js/backbone/apps/login/templates/logout.html
- Add periods to the end of sentences.
#2730
=> Add a period to the sign out screen

assets/js/backbone/apps/tasks/search/templates/internship_search_template.html
- Fix create internship button shows for student
=> Bug: Create internship button showing on Student Search page when student signed in

assets/js/backbone/apps/home/templates/home_view_template.html
- Remove comma, and add period.
#3350
=> Home page update - change punctuation

assets/js/backbone/entities/tasks/task_model.js
- Handle undefined community id rather than throwing an error
=> Hotfix release 7.8

assets/js/backbone/apps/tasks/edit/templates/task_audience_form_template.html
- Correct issue where student target audience is always showing
- Only display student target audience if an active member of a student community
=> Hot fix 7.8 release

migrations/20190715140332-update-alternate-phase-description.js
37730: Manual Triggers - Alternate Phase - Update Text
=> 37730: Manual Triggers - Alternate Phase - Update Text

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/experience.js
- Fix validation showing for questions
#3726
=> Bug: Student Application: Experience Page

api/community/service.js, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, elastic/service.js
- Fix sorting based on published At date
-Clean up some code
#2076
=> Opportunity card sort order

api/community/controller.js, assets/js/backbone/apps/admin/templates/admin_community_template.html
- Add condition isAdmin for Add community
#3738
=> Bug: Community Admin should not have the ability to add a new community

api/application/dao.js, api/application/service.js, api/v1/cycle/dao.js, api/v1/cycle/service.js, migrations/20190715120521-update-get-applicant-score-by-task.js
=> Fix bug around application_task records.

api/admin/dao.js
- Fix filter search on manage users community dashboard
#3732
=> Community manage users

assets/js/backbone/apps/tasks/search/templates/task_search_item.html
- Do not display posted on for opportunities with no posted at date
#2076
=> Opportunity card sort

api/user/dao.js, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Once review for current internship cycle has been closed display
appropriate application status of Selected, Alternate or Not selected.
#2999
=> Internship application status updates

assets/js/backbone/apps/internships/show/templates/interns_view.html, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js
=> DoS: Close out Page for Hiring Managers

api/v1/cycle/controller.js, api/v1/cycle/dao.js, api/v1/cycle/service.js
Added download report functionality to ATP and OO for cycle data. 
TFS Ticket #37305
=> Add download report functionality to ATP and OO for cycles

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/layouts/profile.scss
- Correct display of Add skills button
#3736
=> Bug: Add skills button overhangs container

assets/js/backbone/apps/internships/show/templates/applicants_view.html, assets/js/backbone/apps/internships/show/templates/interns_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/component/card/opportunity.scss, assets/styles/layouts/profile.scss
- Add HTML and update CSS
#3001
=> Internship Badge

assets/js/backbone/apps/internships/show/templates/confirm_close_internship.html, assets/js/backbone/apps/internships/show/views/internship_view.js
- Add modal for selected interns
#3609
=> DoS: Close out confirmation modal

assets/js/backbone/apps/apply/templates/apply_experience_template.html
=> Bug: At least should be two words in error message on apply process

assets/styles/component/card/opportunity.scss
- Update the CSS for circles with initials and names inside of modals
#3609
=> Update CSS for Circles with Initials and Names

api/notification/task.update.not.assigned/template.html
- update text and link for the email
#2869
=> Add link to not selected email

api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
- Add conditions if community is closed group and
community user is disabled to prevent duplicating opportunity
#3558
=> Prevent disabled member of a closed community from duplicating

api/auth/passport.js, api/auth/profile.js, api/user/service.js, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js
- Correct location display on profile
- Correct bug preventing new users from applying to opportunities
#3745
=> Location display and apply bug

api/opportunity/service.js, assets/js/backbone/apps/admin/templates/admin_task_table.html
- Correct issue introduced in version 7.8 preventing community managers
from being able to approve opportunities
#3772
=> Community manager approve opportunities

api/auth/controller.js, api/auth/service.js, api/opportunity/dao.js
- Correct logic around assigning badges for opportunity completion
- Add try catch logic for session timeout
#3757
#3686
=> Badges for opportunity completion and session timeout

api/auth/service.js, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/profiles/find/views/profile_find_view.js
- Add navView when its new user and redirecting to home
- update few properties in api/auth post to display firstname
#3737
=> Bug: Create new user doesn't take user to full landing page

api/badge/service.js, api/notification/task.update.completed/template.js, api/opportunity/dao.js, api/volunteer/dao.js
=> Change all emails in Open Opps to go to the Official federal government email address

assets/js/backbone/apps/internships/show/templates/interns_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js
- Add functionality when click close in the modal popup for close internship
- set status to completed if its closed
#3607, #3609
=> DoS: Close out Page for Hiring Mangers (internship creator)

api/application/import.js, api/auth/service.js, api/v1/cycle/service.js
- Fix issue where error object was not coverting to JSON properly
=> Correct error logging

api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/admin/templates/admin_task_table.html
- Allow deletion of internship opportunities
- Remove 'Approve' header from Draft and Approved states
#3357
=> Allow Deletion of Internship Opportunities

api/auth/controller.js
- Update logout procedure
#3686
=> Session idle logout

api/opportunity/sql/getInternshipApplicants.sql, assets/js/backbone/apps/internships/show/templates/applicants_view.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/styles/component/card/opportunity.scss
- Show separate labels for emails if Login.gov or federal email
#3706
=> Show Separate Labels for Emails

api/opportunity/service.js
- Add security clearance level info when copying an internship
#3798
=> Copy Security Clearance Level

api/user/dao.js, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js, assets/js/backbone/apps/tasks/edit/views/task_audience_form_view.js
=> Applicant Status: Completed

api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/internships/show/views/internship_view.js
=> DoS Survey Emails

api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/internships/show/views/internship_view.js
- Fix route
- fix email data
- Add query for completed interns
#3702,3703
=> DoS: Email with Survey link for Applicants

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
Removed Classified value from list.
#3767
=> Create internship: Remove value from suggested security clearance field

api/notification/state.department/internship.update.submitted/template.html
- update text for internship submitted email
#3773
=> Bug; Internship submitted email content update

api/user/dao.js, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Correct application status updates
#2999
=> Internship application statuses

api/user/dao.js
- Limit subqueries to 1 row
#2999
=> Application status updates

assets/js/backbone/apps/internships/edit/templates/internship_step_template.html, config/session.js
=> Suggest security clearance context help and removed "Classified" value

api/opportunity/controller.js, api/opportunity/service.js
- Need to be able to view selected interns
#3607
=> Community hiring manager

assets/js/backbone/apps/admin/views/admin_community_cycle_edit_view.js
=> Bug: Secondary URL does not save on Cycle

api/admin/dao.js, api/admin/service.js
- When changing internship owner, update task sharing data
#3813
=> Change internship opportunity owner

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
Changed title to "Intern".
#3812
=> Bug: intern badge doesn’t display title

api/admin/controller.js, assets/js/backbone/apps/admin/views/admin_community_edit_view.js
- Add separate routing for  getting community agencies .
#3743
=> Bug: Community Manager cannot click on "Manage community" link

api/admin/dao.js
- Update sitewide admin page to no longer show internship opportunities
#3815
=> Update Queries to Filter Internship Oppportunities

api/opportunity/controller.js
- Use proper permission check
#3822
=> Internship creator (DoS hiring manager) cannot close internship

gulpfile.js, package-lock.json, package.json
- Clean up an existing packages in the bin folder during build process
=> Update gulp TFS build script

api/admin/service.js
- Correct issue causing change in ownership not propagating to ATP
#3813
=> Internship change owner

assets/js/backbone/apps/apply/templates/apply_saved_list_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/styles/layouts/internship.scss
- Update HTML to make card a link
- Update related CSS
- Fix issue allowing clicks of Selected links
- Fix issue with double slashes between bureau and office
#3520
=> Ability to view internship from saved right rail

assets/js/backbone/apps/admin/templates/admin_announcement_template.html, assets/js/backbone/apps/admin/templates/admin_dashboard_activities.html, assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html, assets/js/backbone/apps/admin/templates/admin_dashboard_template.html, assets/js/backbone/apps/admin/templates/admin_dashboard_top_contributors_template.html, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_dashboard_view.js, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/admin/views/admin_top_contributors_view.js, assets/styles/layouts/admin-dashboard.scss
- Add HTML and CSS for Top contributors section
- Add associated view file
- Update header for Opportunities section
- Update header for Announcement section
- Update Recent activity header
- Update Recent activity styles
- Prevent submitted opps with past posting dates from being approved
#2366
=> Add HTML/CSS for Top Contributors Section

api/v1/cycle/controller.js, api/v1/cycle/dao.js, api/v1/cycle/service.js
=> Only allow community managers to start cycles.

assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/styles/layouts/admin-dashboard.scss
- Add sorting for  sitewide agency and community opportunities
#2389
=> Admin Dashboard: Opportunities --> Manage sort by

assets/js/backbone/apps/admin/templates/admin_task_table.html
=> Admin Dashboard: Opportunities

api/admin/controller.js, api/admin/service.js, api/admin/sql/getTopAgencyCreators.sql, api/admin/sql/getTopAgencyParticipants.sql, assets/js/backbone/apps/admin/templates/admin_dashboard_top_contributors_template.html, assets/js/backbone/apps/admin/views/admin_top_contributors_view.js
- Add sql to pull top agency creators and participants
- Add admin api call to retrieve top contributors data
- Update top contributors template to render contributors data
#2366
#2367
=> Top contributors

api/admin/controller.js, api/admin/service.js, api/admin/sql/getCyclicalTasksByState.sql, api/admin/sql/getTasksByState.sql, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js
- Update opportunity sort to work with paging
#2389
=> Admin dashboard

api/v1/cycle/dao.js
=> Update column header in query.

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_community_dashboard_activities_template.html, assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/styles/layouts/admin-dashboard.scss
- Update top margin for ordered list of agencies
#2366
=> Update Margin for Ordered List

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/admin/taskmetrics.js, api/admin/taskmetrics/stateMetrics.js, api/admin/taskmetrics/taskDecorator.js, api/admin/taskmetrics/volunteerMetrics.js, assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html, assets/js/backbone/apps/admin/views/admin_dashboard_view.js
- update queries for task metrics
- update volunteer metrics
- Remove html not in ac
#2369
=> Admin Dashboard: Section 3: Completed Opportunities

api/admin/dao.js
- Update query to remove student activity
- Update query to return max 20 results
#2371
=> Admin Dashboard: Section 4 - Recent activity

assets/js/backbone/apps/admin/templates/admin_dashboard_top_contributors_template.html, assets/styles/layouts/admin-dashboard.scss
- Update HTML and CSS to correct issue with wrapping on narrower screens
#2366
=> Update Top Contributors HTML and CSS

api/admin/sql/getTopAgencyParticipants.sql
- Update query to pull participant agency not creator agency
#2367
=> Top contributors - participants

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/admin/sql/getUserAgencyListBySort.sql, api/admin/sql/getUserCommunityListBySort.sql, api/admin/sql/getUserListBySort.sql, assets/js/backbone/apps/admin/templates/admin_community_user_table.html, assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/styles/app/pages/_dashboard.scss
=> Admin Dashboard: Add sort by to User list

.circleci/config.yml, package.json
- Update target version to NodeJS 10
=> Update NodeJS target version

manifest.yml
- Update buildpack target to version 1.6.53
=> Upgrade target buildpack

api/opportunity/service.js
- Update code causing issue with pulling the correct email addresses
#3856
=> Email to community managers

assets/js/backbone/apps/welcome/templates/welcome_template.html
- Add contractor info to the "Your profile is missing information page"
#3849
=> Add info to Welcome page

api/admin/export/controller.js, api/admin/export/dao.js, api/admin/export/service.js, api/admin/export/sql/getTopAgencyCreatedExport.sql, assets/js/backbone/apps/admin/templates/admin_dashboard_top_contributors_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/welcome/templates/welcome_template.html, assets/js/backbone/browse-app.js
- Redirect from opportunity if not fed hiring path
- Only show apply button if fed hiring path
#3854
=> Prevent students from applying to federal opps

assets/js/backbone/apps/admin/views/admin_user_view.js
- Correct administrator lookup for community managers
#3754
=> Community manager

assets/js/backbone/browse-app.js
- Add modal directing user to complete profile and add agency
#2824
=> Prevent user with no agency from creating opp

assets/js/backbone/apps/internships/show/templates/interns_view.html
- Add condition for button enable
#3814
=> Close out: must be able to close out even if no selectees

assets/js/backbone/apps/nav/views/nav_view.js
- Fix issue caused by multiple instances of the idle timeout object
=> Idle timeout updates

api/document/service.js
- Use GM auto orient to rotate uploaded images based on exif data
#2353
=> Auto rotate images

api/document/service.js, package-lock.json, package.json
- Use an Exif parser to determine photo orientation and rotate if needed
#2353
=> iPhone profile pictures load sideways

api/document/fileUtils.js, api/document/service.js
=> Processing file uploads

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
- Add check to add contractor label
#3865
=> Add contractor label to admin view of profile

assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html
-Fix change display n/a to 0
#2369
=> Admin Dashboard: Section 3: Completed Opportunities#

api/admin/sql/getTasksByState.sql, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js
- Update query to get task agency data
- Display agency column for site wide
#3895
=> Sitewide: Add agency to manage opportunities

api/admin/dao.js, api/opportunity/service.js, assets/js/backbone/browse-app.js
- Prevent students from applying to federal opportunities
- Fix display for community users without an agency
- Use government email address when sending emails to community managers
#3854, #3855, #3856
=> Hotfix release 7.9

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_agencies_template.html, assets/js/backbone/apps/admin/views/admin_agencies_view.js
- Add HTML to Agency Admin page
- Add agency interaction metric queries
#3900
=> Agency Admin: Interactions

api/admin/controller.js, lib/log/index.js, package-lock.json, package.json
- Add ability to send logs to Azure Application Insights
=> Update applicaton logging

api/admin/export/controller.js, api/admin/export/dao.js, api/admin/export/service.js, api/admin/export/sql/getTopCreatedExport.sql, assets/js/backbone/apps/admin/templates/admin_agencies_dashboard_top_contributors_template.html, assets/js/backbone/apps/admin/templates/admin_dashboard_top_contributors_template.html, assets/js/backbone/apps/admin/views/admin_top_contributors_view.js
- Add query for downloading .csv
#3903
=> Agency Admin: Top opportunities created .csv

api/opportunity/service.js, assets/js/backbone/apps/admin/views/admin_agencies_view.js, assets/js/backbone/apps/admin/views/admin_community_view.js
=> Community admin: opportunity metrics for dashboard (Non Dos)

assets/js/backbone/apps/admin/views/admin_agencies_view.js
- Add marked to keep comments from blanking out recent activity
#3902
=> Correct No Recent Activity Issue

assets/js/backbone/apps/admin/views/admin_agencies_view.js, assets/js/backbone/apps/admin/views/admin_community_view.js
- Fix timing issue
#3901, #3905
=> Agency Admin: Dashboard Opportunity Data

api/admin/controller.js, api/admin/service.js, api/admin/sql/getCyclicalTasksByState.sql, api/admin/sql/getTasksByState.sql, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/styles/layouts/admin-dashboard.scss
Filter for non student community opportunities.
#3893
=> Community Admin: Add filter for opportunities (non DoS) 

assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js
- Fix charecter count for experience page
- Add charecter count 5000 for duties and accomplishments
#3946 ,#3951
=> Bug: character counter on the "Please indicate what type of overseas experience you possess" box does not count input

api/admin/dao.js, api/autocomplete/dao.js, api/autocomplete/service.js
=> Bug: Add member search doesn't always return value

assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/experience.js
- Correct experience date displays
- Update max length for duties field
#3946, #3847
=> Update to release 7.9

assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/apply/views/experience.js
=> Community Admin: Add filter for opportunities (non DoS)

assets/js/backbone/apps/apply/templates/apply_review_template.html, gulpfile.js
- Correct application review current experience date views
#3954
=> 7.9 Hotfix

api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_task_table.html
- Add sort by option agency for site wide
#3897
=> Sitewide Admin: Add Agency to Opportunity sort by

assets/js/backbone/apps/admin/templates/admin_user_table.html
- Add agency for sitewide manage users
#3890
=> Sitewide User: Add agency to manage users

assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Add 'not submitted' application status for applications that are not
submitted by the deadline
#3917
=> Intern application status update

assets/js/backbone/apps/admin/views/admin_task_view.js
- Correct issue causing inability to filter by opportunity state on
site admin and agency admin dashboards
#3972
=> Opportunity state filtering -> dev

assets/js/backbone/apps/admin/views/admin_task_view.js
- Correct issue causing inability to filter by opportunity state on
site admin and agency admin dashboards
#3972
=> Opportunity state filtering -> staging

assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js
- Correct issue where career field selections not displaying on edit
#3919
=> Career field display

api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_task_view.js, migrations/20190925175045-add-reference-id-to-community-table.js, migrations/20190925193353-community-reference-id-data.js
Create scripts to add reference_id to community table to distinguish between communities.  Update code to use reference_id.
#3963
=> Community: Add bureau/office post to manage opportunities (DoS)

api/admin/service.js, api/admin/sql/getSitewideTaskStateTotals.sql, api/admin/sql/getTasksByState.sql, assets/js/backbone/apps/admin/templates/admin_task_template.html
- Add functionality to filter opportunities by title, creator or agency
#3891
=> Admin search filter on opportunities

api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_task_table.html
=> Community Admin: Add Bureau and Office/post to opportunity sort by (DoS

api/admin/sql/getCyclicalTasksByState.sql, assets/js/backbone/apps/admin/templates/admin_task_table.html
=> Simplify community opportunities query

assets/js/backbone/apps/admin/templates/admin_task_table.html
- Add agency column to opportunity view in community admin
#3896
=> Community Admin: Add Agency to Opportunity view

migrations/20190930150741-add-task-id-index-to-application-task.js
- Add index to application task table to increase sql performance
#3963
=> Community admin dashboard

api/application/controller.js, assets/js/backbone/apps/internships/show/views/internship_view.js
=> Change modal title if non-student tries to apply

lib/log/middleware.js
- Added additional details to application logs for troubleshooting
=> Update application logs

api/admin/service.js, api/admin/sql/getAgencyTaskStateTotals.sql
- Add ability to filter agency opportunities by title or creator
#3892
=> Search filter for agency admin dashboard

assets/js/backbone/apps/admin/templates/admin_task_table.html
- Add agency to dropdown, with checks for community and non-DoS
#3898
=> Community Admin: Add Agency to opportunity sort

assets/js/backbone/apps/admin/templates/admin_task_template.html
- Update search filter placeholder
#3892
=> Agency admin opportunity filtering

assets/js/backbone/apps/admin/templates/admin_community_user_table.html
- Change to "Community admin"
#3986
=> Update Capitalization on Community Admin

api/admin/export/controller.js, api/admin/service.js, api/admin/sql/getCommunityTaskStateTotals.sql, api/admin/sql/getCyclicalCommunityTaskStateTotals.sql
- Update status pills and paging based on applied search filter
#3992
=> Patch release 8.0

api/admin/service.js, api/admin/sql/getAgencyTaskStateTotals.sql, assets/js/backbone/apps/admin/templates/admin_task_template.html
- Update status pills and paging based on applied search filter
#3992
=> Community opportunity search filter

api/admin/controller.js
- Update auth check for community administrators
=> Community administrators

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/admin/sql/getCyclicalCommunityApplicantMetrics.sql, api/admin/sql/getCyclicalCommunityTaskMetrics.sql, api/admin/sql/getCyclicalCommunityTaskStateTotals.sql, assets/js/backbone/apps/admin/templates/admin_community_cycle_task_interactions.html, assets/js/backbone/apps/admin/templates/admin_community_cyclical_task_metrics.html, assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/js/backbone/apps/admin/views/admin_task_view.js
- Add completed opportunity metrics for community
-Add interactions and opportunities count based on the cycle
- Load cycles  to community page dos
#3910
=> Community Admin: Opportunity metrics Cycle communities (DoS)

api/admin/service.js, api/admin/sql/getCyclicalCommunityTaskStateTotals.sql
- Update sql to return correct numbers for state pills
#3910
=> DoS community bureau and office filtering

api/admin/service.js
- Update filter clause creation
#3891
=> Administration dashboard opportunity filtering

README.md, package-lock.json, package.json
=> Update package version

api/admin/export/dao.js, api/admin/export/service.js
=> Sitewide Admin: Download opps .CSV file changes

assets/js/backbone/apps/admin/templates/admin_community_cycle_task_interactions.html, assets/js/backbone/apps/admin/templates/admin_community_cyclical_task_metrics.html, assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/styles/layouts/admin-dashboard.scss
- update text
- add css for separator line
#3943,#3995
=> DoS community: Update opportunity metric values

api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_community_cycle_task_interactions.html
- update interaction query
- update interactions display page
#3942
=> DoS Community: Interactions updates

api/admin/export/controller.js, api/admin/export/dao.js, api/admin/export/service.js, assets/js/backbone/apps/admin/templates/admin_task_template.html
- Update query for community
- Add query for DoS community with cycle
#3888
=> Community Admin: Opportunity .csv

assets/js/backbone/apps/admin/views/admin_agencies_view.js, assets/js/backbone/apps/admin/views/admin_community_view.js
- fix issue for updating new fiscal year opportunity metrics section (staging)
#4022
=> Opportunities metrics at start of new fiscal year

api/user/controller.js, api/user/service.js, assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_activity_view.js, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/styles/layouts/profile.scss
- Add ability to see a user's opportunities on the user's profile page
#3779
=> View user's opportunities

api/admin/sql/getCyclicalTasksByState.sql
- Only count applicants with a completed application
#4035
=> Applicant count for internships

api/admin/export/dao.js
- update query to pull correct applicant numbers
- update query to pull correct participant names
#3888
=> Community admin opportunity CSV

api/admin/export/dao.js, api/admin/sql/getUserCommunityListBySort.sql, assets/js/backbone/apps/admin/templates/admin_community_user_table.html
=> Admin Dashboard: User .csv file updates

api/admin/export/dao.js
- Update location field in user queries
#2377
=> Sitewide Admin Dashboard: User .csv file changes

assets/js/backbone/apps/profiles/home/templates/home_created_template.html, assets/js/backbone/apps/profiles/home/views/home_view.js, assets/styles/app/pages/_dashboard.scss, assets/styles/layouts/profile.scss
Delete "draft" opportunity with confirmation modal.
#2458
=> Signed in Landing page: Ability to delete draft from Your opportunities 

api/admin/dao.js, assets/js/backbone/apps/admin/templates/admin_community_cycle_task_interactions.html
- update query for interactions dos
#4030
=> Update to DoS interactions

api/admin/service.js
- Update search query on manager users dashboards
#4033
=> Enhance user search for administrators

assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/edit/templates/internship_step_template.html
- Allow for edits to approved internships without needing to
get it approved again
#4027
=> Updates to DoS internships

api/model/AuditTypes.js, api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js
- Add opportunity deletions to the database audit log
#3959
=> Audit opportunity deletions

api/model/AuditTypes.js, api/opportunity/controller.js, api/opportunity/service.js
- Add opportunity updates to the database audit log
#3959
=> Audit opportunity updates

assets/js/backbone/apps/admin/templates/admin_agencies_dashboard_top_contributors_template.html, assets/js/backbone/apps/admin/templates/admin_dashboard_top_contributors_template.html
- Add default text for dashboards if no data is available
#4051
=> Add default text if no data available

assets/js/backbone/apps/admin/templates/admin_community_form_template.html, assets/styles/layouts/admin-dashboard.scss
=> Update Office/Post information - Edit

api/notification/state.department/closecyclephase.start.alternate/template.html, api/notification/state.department/closecyclephase.start.selected/template.html
- Update learn more link
#4058, #4059
=> Update DoS student internship selection emails

api/admin/sql/getUserCommunityListBySort.sql, assets/js/backbone/apps/admin/templates/admin_community_user_table.html
-update query
-add bureau /office to dos manage users
#4061
=> Add Bureau/Office post to State Manage user dashboard

api/admin/export/dao.js, api/admin/export/sql/getCycleInteractions.sql
=> Update DoS interactions CSV file

api/opportunity/dao.js, api/opportunity/service.js
=> Limit approver emails to Bureau/Office/post users

api/admin/controller.js, api/admin/service.js
- Update logic causing error when validating permissions for
changing owner
#4085
=> Community manager cannot change owners

api/v1/cycle/dao.js
=> Update the GetCycleApplicantData for review board

assets/js/backbone/apps/admin/templates/admin_community_add_bureau_office_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js
- Add charecter counter for bureau and offices
- show bureau data in select2 for add new modal
#3851
=> Ability for Community Managers to update Office/Post information - Add new

api/cycle/service.js
- Update code causing errors on updating cycles with no close date
#3985
=> Cycle close date

assets/js/backbone/apps/profiles/edit/views/profile_bureau_office_view.js, assets/js/backbone/apps/profiles/home/views/home_view.js
Fixed to use bureau instead of office since office is not always populated.
#4060
=> Tip to tell State users to update their profile 

api/v1/cycle/controller.js, api/v1/cycle/service.js
Update check for Exclusive JOA
=> 39373: Update check for Exclusive JOA

api/v1/cycle/dao.js
=> Update close cycle report query

api/notification/state.department/closecyclephase.start.alternate/template.html
- Update alternate email
#4058
=> Update DoS student internship selection email

assets/styles/app/pages/_dashboard.scss
Fix font color on button. 
#4060
=> Tip to tell State users to update their profile

api/auth/login.js
Update to remove students from communities.
#4115
=> Bug: community allows for owner of internship to be changed to a student

assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/edit/templates/internship_step_template.html
- Allow for editing of internships that are open without
them going back to submitted state
#4132
=> Add ability to edit DoS internships

assets/js/backbone/apps/profiles/home/views/home_view.js, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js
- Update logic around when to display bureau and office data
#4060
=> Update bureau/office profile data

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Do not allow modifying of cycle after application start date
#4063
=> Updating internships

api/opportunity/dao.js, api/opportunity/service.js
- Only send approver email to BICs
#4062
=> Internship approver emails

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/model/AuditTypes.js, assets/js/backbone/apps/admin/templates/add_community_bureau_office_message_template.html, assets/js/backbone/apps/admin/templates/admin_community_add_bureau_office_template.html, assets/js/backbone/apps/admin/templates/admin_community_bureau_and_office_form_template.html, assets/js/backbone/apps/admin/templates/admin_community_form_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js
- update html for bureau office section html
- update modal for add or edit
- Add audit log for update bureau and office
- Add validation for edit bureau and office
- check bureau offices already exist
#4065
=> Ability for Community Managers to update Office/Post information - Edit

api/enumerations/service.js, assets/js/backbone/apps/admin/templates/admin_community_bureau_and_office_form_template.html, assets/styles/layouts/admin-dashboard.scss
- Update HTML
- Update CSS
- Update service file to display office names as intended
#4065
=> Update Edit Bureau/Office/Post Table HTML

api/application/service.js
Add logging to applications that are updated and submitted.
#4046
=> DoS application: Track submit and update dates

api/admin/export/dao.js, api/admin/export/service.js
- Updated query to include location
#4131
=> Add location to the State internship .csv file

api/application/service.js, assets/js/backbone/apps/profiles/home/templates/home_created_template.html, assets/js/backbone/apps/profiles/home/views/home_view.js
=> Delete draft confirmation modal - update text

api/v1/cycle/service.js, api/v1/opportunity/dao.js
=> Populate closed date when cycle is closed.

assets/js/backbone/apps/apply/templates/apply_summary_template.html, assets/js/backbone/apps/profiles/home/internships/views/internships_view.js, assets/js/backbone/apps/profiles/show/views/profile_show_view.js
- Update the status labels
#4093
=> Update applicant status labels

assets/js/backbone/apps/profiles/show/views/profile_show_view.js
- Add if condition for communities student
#4056
=> Add bureau/office post to profile for State users

assets/js/backbone/apps/internships/edit/templates/internship_step_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Remove Virtual and In person buttons in HTML
- Add validate class to country field
- Remove function that toggles location fields
#4094
=> Remove option to create virtual student internship

api/admin/export/dao.js, api/admin/export/service.js
- Update query
- Update which columns get shown for DoS
#4103
=> Update Manage Users .csv file for State

assets/js/backbone/apps/apply/views/submitted_application.js, assets/js/backbone/apps/internships/show/views/internship_view.js
- update modal text with  application end date
#4122
=> Update modal - update the text to provide more information

assets/js/backbone/apps/apply/templates/apply_congratulations_template.html, assets/js/backbone/apps/apply/views/submitted_application.js, assets/js/backbone/apps/internships/show/views/internship_view.js
- Update text on what's next page
#4116
=> Update What's next page to include content on updating application

assets/js/backbone/apps/apply/templates/apply_summary_template.html
- Update text from PM to p.m.
#4009
=> DoS: Update text on next steps page

api/application/service.js
Moved the import profile data function from Apply to Continue.
#4118
=> Move USAJOBS data pull from Apply button to Next Steps "Continue" 

api/notification/state.department/internship.application.received/template.html, api/notification/state.department/internship.application.received/template.js
- Include info on updating
#4104
=> Update student application submitted email

api/admin/controller.js, api/admin/service.js, api/admin/sql/getCommunityApplicantsInternships.sql, api/admin/sql/getCommunityCycleApplicants.sql, assets/js/backbone/apps/admin/templates/admin_community_applicant_submitted_template.html, assets/js/backbone/apps/admin/templates/admin_community_applicant_template.html, assets/js/backbone/apps/admin/templates/admin_community_cycle_task_interactions.html, assets/js/backbone/apps/admin/templates/admin_main_template.html, assets/js/backbone/apps/admin/views/admin_community_applicant_submitted_view.js, assets/js/backbone/apps/admin/views/admin_community_applicant_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js
- Add llink for search application
- Add new page for applicants
-Add new page for  submitted students internships page
- Add functionality for data displaying for both pages
#4049
=> View what applicants have applied to

api/notification/state.department/internship.application.received/template.html, assets/js/backbone/apps/apply/templates/apply_congratulations_template.html, assets/js/backbone/apps/apply/templates/apply_summary_template.html, assets/js/backbone/apps/apply/views/submitted_application.js, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/js/backbone/apps/tasks/search/templates/internship_search_cycle_box.html
=> Change EST to ET on system pages

assets/js/backbone/apps/admin/templates/admin_community_cycle_task_interactions.html
-Add drafts to state metrics
#4170
=> Update state internship metrics to include drafts

api/admin/export/dao.js, api/admin/export/service.js
=> Add number of positions to the State .csv file

api/admin/export/dao.js, api/opportunity/service.js
Changed title of column and fixed next step error.
#4165
=> Change "Assigned' to "In progress" on opportunity .csv 

assets/js/backbone/apps/apply/views/apply_view.js
Fixed to only pull and show on step 1.
#4119
=> Add "We're pulling data" modal after Next Steps

README.md, package-lock.json, package.json
=> Update package version number

api/admin/controller.js, api/admin/service.js, api/admin/sql/getCommunityCycleApplicants.sql, assets/js/backbone/apps/admin/templates/admin_community_applicant_template.html, assets/js/backbone/apps/admin/views/admin_community_applicant_view.js
- Add sort by options and functionality
- update query
#4133
=> View applicant - sort by

api/v1/application/dao.js
=> Add sorting to application_task list.

api/application/controller.js, api/application/service.js, assets/js/backbone/apps/apply/views/apply_view.js
- Import profile data after reviewing next steps page
#4119
=> Pull profile data for internship applications

api/opportunity/service.js
- Remove unnecessary line of code causing error
#4194
=> Update opportunity state bug

api/admin/export/controller.js, api/admin/export/dao.js, api/admin/export/service.js, api/admin/export/sql/getCommunityCycleApplications.sql
- Added query
- Updated service and controller
- Added link to HTML
#4134
=> Applicant list: csv download

api/admin/service.js
=> Bug: DoS recent activity not showing in order

README.md, api/admin/controller.js, api/admin/export/controller.js, api/admin/export/dao.js, api/admin/export/service.js, api/admin/export/sql/getCommunityCycleApplications.sql, api/admin/service.js, api/admin/sql/getCommunityCycleApplicants.sql, api/application/controller.js, api/application/service.js, api/opportunity/sql/getInternshipApplicants.sql, api/v1/application/dao.js, assets/js/backbone/apps/admin/templates/admin_community_applicant_submitted_template.html, assets/js/backbone/apps/admin/templates/admin_community_applicant_template.html, assets/js/backbone/apps/admin/views/admin_community_applicant_view.js, assets/js/backbone/apps/apply/views/apply_view.js, package-lock.json, package.json
- Correct issue where non applicants are being shown during the interns review process
#4195
=> Displaying internship applicants

migrations/20191121220122-update-application-task-table.js
- Add sort order column to experience table
#4123
=> Bring work experience sort order over from USAJOBS

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/styles/layouts/internship.scss
- Add HTML and CSS for sort buttons
#3994
=> DoS apply: Allow for sorting of work experience

api/admin/controller.js, api/admin/service.js, api/admin/sql/getCommunityCycleApplicants.sql, assets/js/backbone/apps/admin/templates/admin_community_applicant_template.html, assets/js/backbone/apps/admin/views/admin_community_applicant_view.js
- Add filter and filter functionality
- Update query for filter status cycle
applicants
#4130
=> View application status - filter applicants

assets/styles/component/card/opportunity.scss
=> Bug: View applicant display on mobile overlaps

api/admin/service.js
- Sort last login descending will null values last
#2388
=> Sorting users by last login

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js, assets/js/backbone/apps/internships/edit/templates/internship_step_template.html, migrations/20191119164123-add-declineexperience-to-application-table.js
=> Add "I do not have work experience" option on application 

assets/js/backbone/apps/apply/templates/apply_education_preview_template.html, migrations/20191129174549-add-column-sort-order-to-education-table.js.js
- Add  migration for add sort Order column in education table
- update code to default by sort order
#4124
=> Pull/Display the education sort order from USAJOBS One Profile

api/notification/state.department/closecyclephase.start.alternate/template.js, api/notification/state.department/closecyclephase.start.selected/template.js
- Update suggested security clearance
#4192
=> Updates to State selectee email

api/application/controller.js, api/application/service.js, api/model/AuditTypes.js, package-lock.json
- Track when an internship application is withdrawn
#4024
=> Application withdrawl

api/application/controller.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_education_preview_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js, assets/js/backbone/apps/apply/views/experience.js, assets/styles/layouts/internship.scss
- Add sorting and functionality for education apply
#4125
=> Allow for sorting of education data in Open Opps application

api/admin/controller.js, api/admin/service.js, api/admin/sql/getBureauCount.sql, api/admin/sql/getBureauOfficeCount.sql, assets/js/backbone/apps/admin/views/admin_community_cycle_view.js, assets/js/backbone/apps/admin/views/admin_community_edit_view.js
- Update modal
- Add new queries for internship counts
#4120
=> Update delete bureau/office/post confirm modal

api/v1/cycle/controller.js, api/v1/cycle/dao.js, api/v1/cycle/service.js
=> Log deleted applicants when phase begins.

api/notification/state.department/layout2.html, assets/js/backbone/apps/admin/views/admin_community_cycle_view.js
=> Delete cycle modal - update confirmation text

api/v1/user/dao.js, api/v1/user/service.js
=> Community user access for users with no boards.

api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/tasks/edit/templates/task_audience_form_template.html
- Update audience form to always show students button
- Add error message if non-member tries to create internship
#4055
=> Friction if non-member tries to create internship

api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/styles/component/card/opportunity.scss
- Add cancel internship link to right rail
- Add functionality to update state
#4007
=> DoS internship cancel process

api/model/AuditTypes.js, api/opportunity/controller.js, api/opportunity/service.js
- Add Audit log for internship canceled
#4129
=> Cancel: Track metrics

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
=> Fix city name display issue when edit

api/admin/controller.js, api/admin/systemSetting.js, assets/js/backbone/apps/admin/templates/admin_dashboard_template.html, assets/js/backbone/apps/admin/templates/admin_system_setting_form_template.html, assets/js/backbone/apps/admin/templates/admin_system_settings_template.html, assets/js/backbone/apps/admin/views/admin_dashboard_view.js, assets/styles/layouts/admin-dashboard.scss, migrations/20191204131810-add-system-setting-table.js, migrations/20191204150749-add-survey-links-to-system-setting.js
- Create system settings table
- Add creator and participant survey links to system settings
- Add ability for admins to edit system settings
#4088
=> Survey links

api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/internships/show/views/internship_view.js
- If duplicating from a previous closed cycle then assign to a
current cycle
- If duplicating from a previous closed cycle with no current cycle
then display appropriate error message
#4229
=> Duplicate internship

api/admin/systemSetting.js, api/notification/service.js, api/notification/task.update.completed.participant/template.html, api/notification/task.update.completed.participant/template.js
- Pull participant survey link from system settings
#4113
=> Participant survey

api/notification/task.update.completed/template.html
Update survey link to use global url with new settings from db.
#4114
=> Update creator completed survey link in email 

assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/views/admin_community_view.js
Fix issue with not selecting new cycle.
#4199
=> State Admin: Default cycle to current cycle

api/notification/state.department/internship.applicants.canceled/template.html, api/notification/state.department/internship.applicants.canceled/template.js, api/opportunity/service.js, api/opportunity/sql/getInternshipApplicants.sql
- Add email template and functionality when cancel internship
#4064
=> Internship cancel email - internship canceled but select another internship

api/notification/service.js
- Correct issue preventing emails from being logged in the
notification table
=> Logging application emails

api/notification/state.department/internship.applicants.update/template.html, api/notification/state.department/internship.applicants.update/template.js, api/opportunity/service.js, api/opportunity/sql/getInternshipApplicantsForUpdates.sql
- Added email template
- Added query
#4112
=> Email applicants of bureau/office/post/loc. change

assets/js/backbone/apps/admin/templates/admin_community_cycle_form_template.html, assets/js/backbone/apps/apply/views/apply_view.js
- Added timeout around slidedown
#4225
=> Bug: Exp. and edu. drawers don't expand 1st click

api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/internships/show/views/internship_view.js
- Add conditions for dos manager to cancel internship
#4249
=> Limit cancel process to community managers

api/v1/cycle/dao.js, api/v1/cycle/service.js
- Changes requested via USAJOBS PMO to enable sending of DoS
not selected emails to applicants
=> Cycle close email adjustments

api/notification/service.js
- Update code causing notification insert errors
=> Logging notifications

api/notification/task.update.completed.participant/template.html
- Update participant survey link
#4113
=> Opportunity participant survey

api/notification/task.update.completed.participant/template.html, api/v1/cycle/dao.js, api/v1/cycle/service.js
- Update query for collecting list of students that were not selected for an internship
=> Close cycle emails

assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/show/templates/internship_view.html
- Added security clearance to internship view
- Added security clearance to internship edit preview
#4250
=> Add security clearance to internship view

assets/js/backbone/apps/admin/templates/admin_community_cycle_form_template.html, assets/js/backbone/apps/admin/views/admin_community_cycle_edit_view.js, migrations/20191212201739-add-exclusive-date-to-cycle-table.js
=> Add new field to cycle table for Exclusive posting end date and change title

assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/tasks/show/templates/participate_check_list.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/styles/component/modal.scss
- Added check for biography and skills
- Added warning class for modals
#3960
=> Updates to submit modal on opportunity application

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/admin/sql/getUserCommunityListBySort.sql, api/auth/auth.js, api/auth/passport.js, api/community/controller.js, api/community/service.js, api/opportunity/service.js, assets/js/backbone/apps/admin/templates/admin_community_cycle_task_interactions.html, assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/templates/admin_community_user_table.html, assets/js/backbone/apps/admin/templates/admin_main_template.html, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/templates/admin_user_template.html, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/styles/layouts/admin-dashboard.scss, migrations/20191217142242-add-is-approver-to-community-user-table.js
- Create new BIC role
- Update admin pages to utilize new BIC role
- Add audit logging for new BIC role
#4258, #4266
=> DoS BIC role

api/auth/login.js
- Add ability reenable account when linking to valid USAJOBS profile
#4246
=> Linking disabled accounts

api/cycle/service.js, assets/js/backbone/apps/admin/templates/admin_community_cycle_form_template.html, assets/js/backbone/apps/admin/views/admin_community_cycle_edit_view.js
=> Add new field to cycle table for Exclusive posting end date

api/notification/state.department/closecyclephase.start.alternate/template.html, api/notification/state.department/closecyclephase.start.alternate/template.js, api/notification/state.department/closecyclephase.start.selected/template.html, api/notification/state.department/closecyclephase.start.selected/template.js, api/v1/cycle/dao.js, api/v1/cycle/service.js
- Update email, adding new exclusive posting end date
#4231
=> State selectee email content update

api/notification/state.department/closecyclephase.start.alternate/template.js
- Update certificate name to match AC
#4236
=> Correct Certificate Name

api/notification/state.department/closecyclephase.start.alternate/template.js, api/notification/state.department/closecyclephase.start.selected/template.js, api/v1/cycle/controller.js, api/v1/cycle/dao.js, api/v1/cycle/service.js
- Update email content
#4231, #4236
=> DoS primary and alternate selectee emails

assets/js/backbone/apps/admin/views/admin_agencies_view.js, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/js/backbone/apps/admin/views/admin_dashboard_view.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, migrations/20191217191129-add-column-people-needed-to-task-table.js, migrations/20191218153640-update-people-needed-task-table.js
- Add new column in task table
- Copy data to new column
- Update opportunity show template to use data from new column
- Update opportunity preview template
- Update opportunity edit form with new buttons
#2213
=> How many people do you need field - make icons

api/admin/controller.js, api/admin/service.js, api/admin/sql/getTasksVolunteers.sql, api/model/AuditTypes.js, assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/templates/admin_applicant_participant_template.html, assets/js/backbone/apps/admin/templates/admin_delete_applicant_participant_template.html, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/styles/component/card/opportunity.scss, assets/styles/layouts/admin-dashboard.scss
- Add html for display participants and applicants in sitewide page
- Add delete modal for applicants and participants
- Update service
- Add audit log to track delete applicants record
#2066
=> Admin: Ability to remove applicants

api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_user_template.html
- Update default text in search box
- Update where clause for select
#4279
=> Add email to Manage User search

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html
- Move button to bottom of error alert
#4215
=> Update button placement in error alert

.github/ISSUE_TEMPLATE/open-opps-ticket.md
Adding ticket template, so the team can have an easier time writing tickets in GitHub.
=> Update issue templates

api/notification/task.update.submitted.admin/template.html, api/notification/task.update.submitted.admin/template.js
=> Email update: Opportunity Submitted email to admin

assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
- Update template to hide date if there's no submitted date
- Also hide date if still in submitted status
#1857
=> Only show posted date after approval

assets/js/backbone/apps/comments/new/templates/comment_form_template.html, assets/styles/component/card/opportunity.scss
- Add data-text
- Add CSS to show and hide data-text
#2154
=> Opportunity page default text for comment box

test/database/midastest.sql
- New automated database backup
=> Update database for automated testing

api/user/dao.js, api/user/service.js, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, migrations/20191231180409-remove-vsfs-from-community-table.js
- Add label and add community Approver to data
#4306
=> Add BIC label to profile of BIC community member

assets/js/backbone/apps/tasks/show/templates/task_share_template.txt, assets/js/backbone/apps/tasks/show/views/task_item_view.js
- Update email subject
- Update email body
#2173
=> Share Opportunity Email changes

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- Limit  input digits for month,day and year
- Add validation if completion date is past date
#1850
=> Don't allow past dates for estimated completion date

api/model/Badge.js, test/unit/models/Badge.test.js
=> Community manager badge

assets/js/backbone/apps/admin/views/admin_community_view.js, assets/js/backbone/apps/tasks/show/views/task_item_view.js
Remove arrow functions from backbone scripts
#4331
=> Hotfix 8.4 release

migrations/20200106213114-diable-accounts-older-than-three-years.js
- Disable account that have not logged in or made profile changes in
the last 3 years
#4244
=> Disable inactive accounts

assets/js/backbone/apps/home/views/home_view.js, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/profiles/home/views/home_view.js, assets/js/backbone/apps/profiles/list/views/profile_list_view.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/js/backbone/apps/tasks/search/views/task_search_view.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/globals/search-utils.js
- Fix undefined variable usage
=> Code refactor

api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/tasks/search/templates/task_filters.html, assets/js/backbone/apps/tasks/search/views/task_search_view.js, assets/styles/app/pages/_search.scss, elastic/service.js
Add community dropdown and populate.
#4289
=> Add search filter for communities

api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/browse-app.js, migrations/20200107150421-add-column-vanity-url-to-community-table.js, migrations/20200107150821-community-vanity-url-data.js
- Add vanity_url column to community table
- Add fai as vanity_url
- Add backbone route for /community(/:vanity)
- Add API route lookup for community by vanity URL
- Add redirect to search page with proper community filter
#4288
=> Vanity URL for FAI

assets/js/backbone/apps/admin/templates/admin_community_form_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/js/backbone/globals/validation-utils.js
-Remove Application process field from community and make not required  for microsite url
-Fix save issue with update validation-utils.js
- Fix charcounter
#4287
=> Vanity URL for Cyber

assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/apps/nav/templates/nav_template.html
- Correct issue where administration link did not display for BICs
#4356
=> Administration link

api/admin/controller.js, api/admin/sql/getUserCommunityListBySort.sql, api/auth/auth.js, api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/admin/templates/admin_announcement_template.html, assets/js/backbone/apps/admin/templates/admin_dashboard_top_contributors_template.html, assets/js/backbone/apps/admin/templates/admin_main_template.html, assets/js/backbone/apps/admin/templates/admin_summary_template.html, assets/js/backbone/apps/admin/templates/admin_system_settings_template.html, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/apps/nav/templates/nav_template.html, migrations/20200106214213-create-sitewide-approver-role.js
- Create new approver role
- Sitewide approver can only approve submitted opportunities
#3035
=> Create new user role

migrations/20200109133506-add-vanity-url-for-cyber-community.js, migrations/20200109133657-add-banner-for-cyber-community.js
- Create vanity URL
- Create custom search banner
#4287, #4290
=> Cyber community vanity URL and search page

assets/js/backbone/apps/profiles/list/views/profile_list_view.js
- Add var appliedFilterCount
#4289
=> People tab not loading

elastic/service.js, migrations/20200109160525-remove-duplicate-badges.js
- Remove duplicate user badges
- Fix Elastic query for community filter
#4289, #1872
=> Remove duplicate badges

api/admin/controller.js, api/admin/sql/getUserListBySort.sql, assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/admin/views/admin_user_view.js
- Add ability for admins to add/remove approver role
#3035
=> Sitewide approver role

migrations/20200110135854-update-community-name-cyber-reskilling-to-community-table.js
- update community name of cyber
#4368
=> Change name of Cyber community

.circleci/config.yml, manifest.yml, package.json
- Upgrade to NodeJS 10.8.0
- Upgrade to NodeJS Buildpack 1.7.8
=> Upgrade build and runtime dependencies

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- Add character count on title and intro
- Add character count on what you'll do, what you'll learn, and who we are
- Remove "Recommend 100 words or less"
- Update Headline to Title
#3345 
#1917
=> Enhancement: Display field limits on Create

api/v1/cycle/service.js
- Update USAJOBS logo path in service file
#4350
=> Update USAJOBS logo path

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
- Update to only show role labels for certain permissions
#4315
=> Label display on profile for user roles

assets/js/backbone/apps/footer/templates/footer_template.html
- Remove open source link
#1911
=> Remove Open Source Link in Footer

api/auth/dao.js, api/auth/passport.js, api/user/controller.js, api/user/dao.js, api/user/service.js, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/profiles/home/views/home_view.js, assets/js/backbone/apps/profiles/show/templates/profile_bureau_office_message_template.html, assets/js/backbone/apps/profiles/show/templates/profile_bureau_office_preview_template.html, assets/js/backbone/apps/profiles/show/templates/profile_bureau_office_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/styles/layouts/profile.scss, migrations/20200113141131-add-user-bureau-office-table.js, migrations/20200115192429-insert-midas-user-bureauid-officeId-to-user-bureau-office-table.js
- create table user_bureau__office
- Add Data migration to insert record for
existing bureau/office profile data
- Update template for Bureau and office display to the profile
-  Add Modal
-  Add logic for insert and remove bureau and office to the new table user bureau office
-  add css
-  update logic for already exist bureau and office object to array data for home page and internship edit page
#4353
=> Allow for State users to be associated to multiple bureaus/office/posts

assets/js/backbone/apps/admin/templates/admin_community_user_table.html, assets/js/backbone/apps/admin/templates/admin_user_table.html
- Add profile link to user page for sitewide,community and agency
#4347
=> Link User's Names to Profile in Admin Dashboard

migrations/20200116201652-update-fai-vanity-url.js
- Change vanity URL for FAI community
#4381
=> Update FAI vanity URL

api/opportunity/service.js, assets/js/backbone/apps/admin/templates/admin_task_table.html
=> verify BIC approval process

assets/js/backbone/apps/apply/templates/submitted_application_template.html
Withdraw available until review end date.
#4327
=> DoS - Student Withdraws Application After Application Cycle Closes

assets/js/backbone/apps/internships/edit/templates/internship_step_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
=> Add field size limit for internship opportunities

assets/js/backbone/apps/profiles/show/templates/profile_alert_message_template.html
- Fix text change for alert message
#4345
=> Add "Remove" Link Below Badges on User's Profile Page

api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_community_add_bureau_office_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js
- update logic to display bureau when edit office/post
#4400
=> Allow for office/post to be moved to a different bureau

package-lock.json, package.json
- Add remove-markdown dependency to package file
#1887
=> Opportunity card

gulpfile.js
- Emit errors during scripts build task
=> Update gulp build process

api/admin/export/dao.js
- Update query and add field to export
#4377
=> Update State community user .csv to include BIC

api/admin/dao.js, api/admin/export/sql/getCommunityCycleApplications.sql, api/admin/export/sql/getCycleInteractions.sql, api/admin/sql/getCommunityCycleApplicants.sql
- update queries to not display withdrawn
students in dashboard,csv and search
applicants
#4389
=> Withdrawn students should not display in admin view

assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html, assets/js/backbone/apps/profiles/home/templates/home_participated_template.html, assets/styles/app/pages/_dashboard.scss, assets/styles/component/pill.scss
=> Create applicant status pills

gulpfile.js, package-lock.json, package.json
- Add merge-stream dependency
- Merge gulp streams when moving files
=> Update gulp build

assets/js/backbone/apps/apply/templates/submitted_application_template.html, assets/styles/layouts/internship.scss
=> DoS - Student Dashboard Enhancements

assets/js/backbone/apps/admin/templates/admin_community_preview_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/styles/layouts/admin-dashboard.scss
- Added community search preview template
- Updated view for modal functionality
- Updated CSS
#4416
=> Add Preview Button in Admin Panel

api/notification/sql/getApplicationsDue.sql
- Only pull not submitted applications
#4001
=> DoS application due email

assets/js/backbone/apps/admin/templates/admin_community_custom_form_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/styles/layouts/admin-dashboard.scss
=> Updates to community attribute table

assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/profiles/show/templates/profile_bureau_office_preview_template.html, assets/js/backbone/apps/profiles/show/templates/profile_photo_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tasks/search/templates/task_search_template.html, assets/styles/layouts/admin-dashboard.scss, assets/styles/layouts/profile.scss
- Profile: Update HTML to correct duplicate id issue
- Profile: Update HTML to correct improper nesting inside anchor
#4421
=> 508 issues from the recent scan

api/notification/state.department/internship.application.due/template.html
=> Student application due

api/notification/state.department/internship.application.due/template.js
- Update subject for application due email
#4001
=> Application due email

assets/js/backbone/apps/admin/templates/admin_community_form_template.html
- Update Manage Community page HTML
#4413
=> Update Manage Community page HTML

api/document/fileUtils.js, assets/js/backbone/apps/admin/views/admin_community_cycle_edit_view.js, assets/js/backbone/apps/admin/views/admin_community_cycle_view.js, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/js/backbone/apps/apply/views/skill.js, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/js/backbone/apps/login/views/login_create_view.js, assets/js/backbone/apps/profiles/home/views/home_view.js, assets/js/backbone/apps/tasks/search/views/task_search_view.js, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/js/backbone/base/base_app_module.js, assets/js/backbone/base/base_component.js, assets/js/backbone/base/base_controller.js, assets/js/backbone/base/base_view.js, assets/js/backbone/components/tag_factory.js, assets/js/backbone/entities/comments/comment_collection.js, assets/js/backbone/entities/search/search_model.js, assets/js/backbone/globals/autocomplete-utils.js, assets/js/backbone/globals/search-utils.js, assets/js/backbone/globals/utils.js, gulpfile.js
- Correct URL for gulp lint task
- Correct javascript style guide errors and warnings
=> Enforce javascript code styles

api/document/fileUtils.js
- Only attempt to parse exif data for jpgs
#4413
=> Image uploads

assets/js/backbone/apps/profiles/home/templates/home_search_template.html
- Fix display issue when acquisition career field is not in the top results
=> Fix 8.7 rendering issue

assets/js/backbone/apps/admin/templates/admin_community_custom_form_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/styles/layouts/profile.scss, assets/styles/lib/_jquery-fileupload.scss
=> Updates to community attribute table 

README.md, package-lock.json, package.json
- update package.json
- update readme.md file
=> Create release package 8.9.0

assets/js/backbone/apps/admin/templates/admin_community_custom_form_template.html, assets/js/backbone/apps/admin/templates/admin_community_preview_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/js/backbone/apps/tasks/search/templates/task_search_template.html
- Set default colors
- Update preview template
#4413
=> Customize community search banner

migrations/20200218133802-add-pay-plan-table.js, migrations/20200218133831-import-pay-plan-data.js, utils/payplan-data.js
- Create pay plan table
- Import pay plan data from USAJOBS
#4463
=> Import Pay Plans

api/model/Agency.js, api/opportunity/service.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/search/templates/search_pills.html, assets/js/backbone/apps/tasks/search/templates/task_filters.html, assets/js/backbone/apps/tasks/search/views/task_search_view.js, elastic/dao.js, elastic/service.js, migrations/20200218215215-add-restricted-to-column-to-task.js, migrations/20200218215920-update-restricted-to-values.js
- Ability to limit to my agency or parent department
- Ability to filter by my agency or parent department
#2824
=> Agency and department limit participation enhancements

assets/js/backbone/apps/admin/views/admin_agencies_view.js
- Fix issue loading page to user's agency
#2824
=> Update agency admin dashboard

assets/js/backbone/apps/admin/templates/admin_community_form_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/styles/layouts/admin-dashboard.scss, migrations/20200218141451-add-auto-join-to-community-table.js
- Add auto_join column to community table
- Add auto-join toggle to manage community page
- Add js to hide/show auto-join
- Update CSS
#4451
=> Add Auto Join Toggle on Create/Edit Community Page

api/enumerations/controller.js, api/enumerations/dao.js, api/enumerations/service.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/styles/component/card/opportunity.scss, migrations/20200213131307-add-columns-to-task-table.js, migrations/20200214154142-add-part-time-detail-to-tag-entity.js
- add template
-  update service
-Add payplans 
-add options for fultime and part time
-add migration to add columns
#4453 #4449
=> View DOI Opportunity

api/auth/profile.js, api/model/Agency.js, api/opportunity/controller.js, api/opportunity/service.js, elastic/dao.js, elastic/service.js
- Add users as members to closed communities that belong to same agency
#4452
=> Closed agency community auto join

assets/js/backbone/apps/tasks/search/templates/task_search_banner.html, assets/js/backbone/apps/tasks/search/templates/task_search_template.html
- Update search banner to display community customization
#4413, #4416
=> Custom search banners

assets/js/backbone/apps/admin/templates/admin_community_custom_form_template.html, assets/js/backbone/apps/admin/templates/admin_community_preview_template.html, assets/js/backbone/apps/admin/views/admin_community_edit_view.js, assets/js/backbone/apps/tasks/search/templates/task_search_banner.html, assets/js/backbone/apps/tasks/search/templates/task_search_template.html
- Update search banner to display community customization
#4413, #4416
=> Custom community search banners

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/component/card/opportunity.scss
- update text
-Add data to preview page and show page
-change to required fields
#4449 , #4453
=> Create/Edit Opportunity Page for DOI
