openopps/openopps-platform

- Gruntfile.js
Select2 depends on a few small support images for the look-and-feel
of the plugin. It expects that these images will be located in the
css directory. This commit adds a copy:csssupport task that moves
the resources to the correct location.
Fixes #458
> Adding a grunt task to move some support images to the prod folder.

- chef/Berksfile
Chef 12 introduced a breaking change by requiring metadata.rb
to contain a name attribute. The released user cookbook, 0.3.0,
does not contain this attribute, and therefore will not work
with the current version of chef. The name attribute is in
Github master, but the maintainers of the repo have not been
responsive about when/if the current version will be released.
This change switches the cookbook to use the Github master
version of the cookbook.
> Adding a Berksfile entry for chef-user.

- api/services/dispatch/sendSimpleEmail.js
The error message that is raised when email is not configured
to send isn't very informative. This adds a brief message to
provide context for the ECONNREFUSED error message as a 'hint'
for developers.
Fixes #420
> Adding a more friendly error message for failing to send an email.

- api/controllers/AdminController.js
Using an underscore (lodash) chain of operations to make it more clear how `users.withTasks` is counted.
Good to go.
> Try different method for settings users.withTasks. Fixes #486

- INSTALL.md
- config/models.js
for now, let’s go back to production config
with dev change to ‘alter’ so we can get AWS
installation up and running
> production config

- package.json
we need additional packages
I added --production to the midas-cookbook npm install to speed up deploys
then it failed since we run 'make build' on production
this commit moves required libraries out of devDependencies
> since we run ‘make build’ on production

- assets/js/backbone/apps/login/templates/login_template.html
- assets/js/backbone/apps/login/views/login_view.js
- config/auth.js
- test/api/sails/helpers/config.js
- test/api/sails/user.test.js
When a user signs up for a new account, we ask for their full name:
It's validated to not be empty:
And it's saved to their profile on sign-up:
Also includes a test to make sure the name saves during registration.
Good to go.
Refs #472
> Require user name during registration

- api/services/dispatch/sendSimpleEmail.js
If present, a list of addresses to CC or BCC will be added to all outgoing emails.
Use by setting the following in `config/local.js`:
```js
// System-wide email notification settings
// Set as a comma-separated list of email addresses
notificationsCC  : '',
notificationsBCC : '',
```
Closes #487
> Set up global notification CC and BCC

- api/services/sources/model.js
- test/api/sails/tag.test.js
With the .10 update for Sails, `LIKE` queries need to include wildcards. This adds them for the autocomplete endpoints.
Fixes 18F/midas-open-opportunities#57
@ultrasaurus ready for review
> Add wildcards for autocomplete query match pattern

- assets/js/backbone/apps/login/templates/login_template.html
- assets/styles/application.css
I came across this [issue](https://github.com/18F/midas/issues/308) while browsing some of 18F's projects and thought I could help.
What are your thoughts on moving "forgot password" below the password input. That seems to take away some of the noise around the sign-up link.
> Make "sign up now" link more prominent

- assets/js/backbone/apps/browse/templates/browse_main_view_template.html
- assets/js/backbone/apps/events/list/templates/event_collection_view_template.html
- assets/js/backbone/apps/events/new/templates/event_form_template.html
- assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
- assets/js/backbone/apps/tasks/list/templates/task_collection_view_template.html
Adds a `backdrop: 'static'` attribute to modal dialogs to prevent closing them by clicking outside of the modal.
Closes #183
> Add modal static attribute. Add cancel button to new event modal.

- api/controllers/TaskController.js
- api/models/Task.js
- api/services/utils/user.js
- assets/email/templates/taskCreated/html.ejs
- assets/email/templates/taskCreated/text.ejs
- assets/js/backbone/apps/browse/templates/browse_main_view_template.html
- assets/js/backbone/apps/browse/views/browse_main_view.js
- assets/js/backbone/config/ui.json
- assets/styles/application.css
- config/settings/emailTemplates.ex.js
- config/settings/notifications.ex.js
This PR pulls together a bunch of different tickets related to setting up a workflow for draft tasks.
Admins set config options to determine the workflow for publishing new tasks. Tasks may either be created as `open` or `draft`. Once a new task is posted, [an email alert](https://github.com/18F/midas/issues/508) goes out to the task creator (admins CCd). The admin or task creator may then update their task to `open` when it's ready to be published to the site.
OO-specific notes are here: https://github.com/18F/midas-open-opportunities/issues/61
> [Not ready] Draft Tasks Workflow

- api/controllers/TagController.js
- test/demo/data/utils.js
Two problems were occurring with `make init`:
1. Tests were passing even if responses from the API return error codes >= 400, which was hiding the second problem
2. At some point while handling the request, `req.body.id` is being added as `undefined`. When a model is created with an `undefined` `id`, it fails, because the `id` needs to be not `null`. If the `id` is not present, the database will automatically create one. I'm guessing this showing up now has something to do with the Sails v.10 upgrade.
This PR fixes both issues.
cc @ultrasaurus 
Refs #532
> Fix make init

- CONTRIBUTING.md
- INSTALL.md
- Makefile
- tools/postgres/init.sh
- tools/postgres/migrate/1.sh
- tools/postgres/migrate/2.sh
- tools/postgres/schema/current.sql
We're at a point where we need to make some database changes, and we want to do so in a way that manages schema changes under version control and allows for automated deployment. This PR adds scripts and documentation for implementing a schema management process as well as managing schema changes going forward.
It adds the current database schema, migration scripts, and updates the make file and documentation for managing schema changes.
Enables: #514
Closes: #515
> Add database schema management

- config/local.ex.js
- config/settings/auth.ex.js
@dlapiduz This replaces the relative path with an absolute path. Do you need this of all relative instances or just this one?
For instance, is [this](https://github.com/18F/midas/blob/devel/config/auth.js#L9) a problem?
```js
var authSettings   = require('./settings/auth.js');
```
How about [this](https://github.com/18F/midas/blob/devel/config/auth.js#L10)?
```js
var userUtils      = require('../api/services/utils/user.js');
```
> Set require for login.json to absolute path

- Gruntfile.js
- views/layout.ejs
Uses the last commit `sha` for the production js and css file names.
> Use sha for css and js production files

- Makefile
- tools/postgres/init.sh
`make build` no longer runs `./tools/postgres/init.sh`
Use `make migrate` instead.
cc @dlapiduz
> Move DB migration to `make migrate`

- api/controllers/UserController.js
- api/policies/test.js
- assets/js/backbone/apps/login/views/login_view.js
- config/policies.js
- test/api/sails/user.test.js
We have two reported issues of duplicate users with the same email address: #377 and #548 
I've tested that it is not possible to create duplicate local users (normal email and password registration). This PR adds those tests as well a front-end change to disable the new user submit button on submit (prevents double clicking).
The only thing I can think of that may be an issue is when users sign in with MyUSA. Waiting on upstream work to test that.
> Avoid duplicate users with the same email address

- config/session.js
- package.json
- Adjusts session cookie to 30 days
- Uses `sessions` table in postgres DB for active sessions
- Adds `connect-pg-simple` module for managing session through connect / express
Closes #496
> Use postgres for session store

- assets/js/backbone/entities/profiles/profile_model.js
The DB returns null values for attributes, which sails then uses to overwrite existing values on update. This removes null values when the user model is loaded.
This should resolve https://github.com/18F/midas-open-opportunities/issues/60
> Remove null attributes from user model

- assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html
- assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
Adds fields to set the published, assigned, and completed time for tasks.
Closes #595
> Add datetime fields on task edit form

- assets/js/backbone/apps/admin/templates/admin_tag_template.html
- assets/js/backbone/apps/admin/views/admin_tag_view.js
- assets/js/backbone/components/tag_factory.js
This adds a simple UI to browse and create tags for admins:
Allows admins to handle requests like https://github.com/18F/midas-open-opportunities/issues/79 without needing to access the DB directly.
> Add tag creation UI for admins

- api/controllers/AdminController.js
- assets/js/backbone/apps/admin/templates/admin_dashboard_table.html
- assets/js/backbone/apps/admin/views/admin_dashboard_view.js
Adds a section to the admin dashboard that counts interactions, as described in https://github.com/18F/midas-open-opportunities/issues/73
cc @ultrasaurus 
Also adds drafts to the task counts on the dashboard.
> Add interactions to admin dashboard

- api/services/utils/user.js
When browsing tasks, the application crashes if it attempts to access tags[i].tag when tag is undefined.
This appears to be related to relations defined in the tag table no longer existing or being corrupt. 
If the data is complete, this will have no effect. If the data is incomplete the browse will never complete, even if forever is working and catches the application crash.
> Stops app crash when tag data is incomplete

- assets/js/backbone/apps/browse/templates/no_search_results.html
- assets/js/backbone/apps/browse/views/browse_list_view.js
- assets/js/backbone/config/require_config.js
- assets/js/backbone/config/ui.json
- assets/locales/en-US/translation.json
- assets/locales/en/translation.json
Text displayed when there are no search or browse results to replace the current behavior of no feedback at all.
Uses uiconfig to decide to show Projects or FAQ lines.
Stores top text in translation file, so it can be customized per installation.
Uses uiconfig for systemEmail mailto for last line.
Is it's own template so a design can be implemented at a later date.
Addresses #101
> Add text when no search results

- Makefile
- test-browser/task.js
- test/data/disk.db
Adds sample data for tests generated from `make demo` and truncated.
Adds tests for the following scenarios:
1. Access `/tasks`
2. `/tasks` has a list of task
3. Access task page
4. Title of task page matches link on `/tasks`
Closes #582
> Add sample data. Add more browser tests for tasks.

- assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- package.json
Fixes #613 
Sails Waterline ORM treats `""` (empty string) as a string instead of `undefined`, so saving empty dates fail.
> Timestamp patch

- chef/Berksfile.lock
Provisioning a Vagrant box was failing for me because it was trying to run
the client config task, which was deleted in
d0b0563d6fa9de6d2bccfdc2dcfcc7a50e36af51 (and references nonexistent
files).
> Update Berkshelf.lock version of midas-cookbook.

- .gitignore
- INSTALL.md
amend INSTALL: use nvm for installing node
Now that nodejs has moved on to 0.12 the default instructions (brew install nodejs) are no longer what you want. Midas depends on 0.10, for the time being at least. Instead of fragile instructions on versioning, recommend managing versions with nvm instead.
While in here, ignore vi temp files (*.swp).
> Small setup improvements -- nvm to handle nodejs 0.10 dependency

- assets/js/backbone/apps/tasks/show/templates/change_state_template.html
Simple UX fix. The labels next to the radio buttons should be clickable.
> Click on opportunity state label changes the radio

- assets/js/backbone/components/tag_factory.js
This PR fixes bug #313. When clicking outside the tag selection field, add the tag instead of discarding it.
> Add tag when clicking outside the input field

- api/models/File.js
This PR fixes #589 by never dropping and recreating the file table when the development server is started.
Something gets messed up in the extraction and re-insertion of the binary data during the automatic migration.
The real fix would be to dig deep in the database adapter and figure out what's going on, but this workaround is good enough since the file table is not likely to change often and thus need to be migrated in development.
> Don't migrate the file table automatically

- assets/js/backbone/apps/comments/new/templates/comment_form_template.html
While I realize that you have the hierachy of comments in there right now and the change to non-nested comments in #687 may not something you want to do right now, I still want to submit this UI fix for the width of the comment box.
I still think that a simpler comment system would help in the long run (I'm not sure I would know in which of the 3 boxes I should write a comment in the picture above).
> The comment input should be full width

- api/controllers/TaskController.js
- api/controllers/UserController.js
- api/models/Task.js
- api/models/User.js
- api/services/utils/export.js
- assets/js/backbone/apps/admin/templates/admin_task_template.html
- assets/js/backbone/apps/admin/templates/admin_user_template.html
- assets/js/backbone/apps/admin/views/admin_task_view.js
- assets/js/backbone/apps/admin/views/admin_user_view.js
- assets/styles/application.css
- config/policies.js
- package.json
- test/api/sails/admin.test.js
- test/api/sails/helpers/config.js
- test/api/sails/helpers/utils.js
- test/api/sails/task.test.js
- test/api/sails/user.test.js
Add a "download" button on the user and tasks admin pages to save a csv
format of those files. CSV file formatted for easy import into Excel by
handling null strings and formatting dates. Adds dependency on the
json2csv module to produce well-formatted csv (handles escape quoting,
etc.)
This fixes issues #667 and #668.
Some clumsiness on the task csv in how it counts volunteers to summarize
in the "signup" column. I couldn't get a groupby/count to work with the
waterline ORM, so had to resort to clunky sql and exclude that for test
cases, where the backend isn't sql-compliant.
> Admin csv export for users and tasks

- config/env/development.js
Since we use **npm run migrate** for db changes and since migrate alter doesn't play nice with our sails postgres soft deletes fork, migrate alter should never be used even in development.
> Change migrate to safe in the development env file as default

- config/log.js
- package.json
Basic logging with Winston. This should catch all current logging except the debug info thrown by i18n.
To use, you need to **npm install winston**
A couple of notes:
1) Winston uses different logging levels than sails (they are flipped), so the log_levels variable addresses that
2) Sails logging level (on line 68 of log.js) is the superset of available levels for other transports
3) The transport.Console is required to push info to the console and it will use the lesser of it's logging level and the sails logging level. Without it, you will see no logging information in the console.
4)Multiple transports of the same type can be created (if you wanted to write different levels to different files for instance) but they MUST have different **name** attributes or an error will be thrown.
5) …
> Add logging with winston

- assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
- assets/js/backbone/apps/profiles/show/views/profile_show_view.js
Add client-side validation to profile editing that prevents members from saving with an empty name. Use utilities.validator for validation.
This should address issue #640.
As far as I can tell, there is no test coverage around this part of the application. Let me know if I'm mistaken and I'll add testing for this change.
> Issue #640: Prevent saving a profile with an empty name

- assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js
- assets/js/backbone/apps/tasks/show/views/task_item_view.js
When an unauthenticated volunteer clicks the "Volunteer" button on a task, they are prompted to log in. This PR triggers the "Volunteer" modal after sign-in for local accounts and new sign-ups. It won't work for oauth accounts, as they require a persistent mechanism (captured in #724)
Resolves #637
> Open volunteer modal after local sign-in

- api/controllers/TaskController.js
Added populate method so tags appear again in Project listing of associated tasks.
Fixes #750
> Add populate method to Task controller findByProjectId method

- assets/js/backbone/apps/projectowner/show/templates/projectowner_show_template.html
- assets/styles/application.css
**Problem:**
The 'Working Group Owners' section of the 'Edit Project' screen is too narrow to fit both the section header and the Cancel and Submit buttons, as documented in Issue #715.
**Solution:**
Move the buttons to be beneath the input field instead. Additionally, I switched the order of the buttons for visual consistency with the button ordering on the `Working Group Description` section.
The Working Group Owners section  should now look like the following screenshots in the editing state:
*Full width*
*Medium width*
*Minimum width*
> Issue 715: Button positioning bug while adding project owners

- assets/js/backbone/app.js
- config/csrf.js
- test/test.upstart.js
- views/layout.ejs
CSRF tokens prevent a certain type of session attack. This turns on verification of a valid CSRF token for all non-`get` requests to the API, provides the token as an HTML `meta` tag, and adds the token as an HTTP header to all `$.ajax` requests.
More: http://sailsjs.org/#!/documentation/concepts/Security/CSRF.html
> Enable CSRF tokens. Resolves #728

- api/controllers/TaskController.js
- assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js
- assets/js/backbone/apps/tasks/show/templates/clone_task_template.html
- assets/js/backbone/apps/tasks/show/templates/copy_task_template.html
- assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
- config/policies.js
- test/api/sails/task.test.js
**Change Summary**
*Server side changes:* This PR adds an endpoint to `TaskController`, `clone`. The endpoint accepts a task `id` and an optional `title` parameter (if no title is provided, the original title is used). It creates a new task instance, copying over the `projectId`, `title`, `description`, and `tags` from the original task. It then returns the id and title of the new task.
*Client side changes:* When viewing and editing a task, owners/admins now see an additional option:
Selection the option opens a confirmation modal that prompts for the title for the new task (defaulted to the original title with 'Clone' appended to the end). When the clone is submitted and succeeds, the user is navigated to the new task.
---
I'd like some feedback about the UI for task cloning - I'm not …
> Allow task creators to clone tasks

- assets/js/backbone/apps/browse/controllers/browse_list_controller.js
- assets/js/backbone/apps/profiles/show/views/profile_show_view.js
- assets/js/backbone/apps/project/show/views/project_item_coremeta_view.js
- assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- test/api/sails/tag.test.js
- tools/postgres/addLocationData.js
Fixes  #768
- adds missing `tag.data` property when saving new tags to profiles, tasks, and projects
- adds a test for the tag creation API that verifies location suggestions and saving location data
- adds a script to update locations missing data.
If you have locations without location data, you can bulk update them by running `node tools/postgres/addLocationData.js` from the project root directory.
cc @sefk
> Location data fix

- assets/styles/application.css
Addresses #736 
Changes this behavior:
To this:
> Project opportunity listing overflow fix

- assets/js/backbone/apps/tasks/list/views/task_collection_view.js
**Problem:** In the list of tasks shown on a project page, the `task-skills-required` tag was being rendered into the tag cloud. This tag is used to denote whether skills for a task are required or not, but isn't helpful to show in the task tag clound.
**Solution:** Filter out tags of the `task-skills-required` type before rendering the tag cloud.
This PR should take a task listing like this:
and turn it into this:
> Filter Required/Not Required from task list tag clouds

- config/env/development.js
Reverses an accidentally committed change to the `config/eng/dev` model migration setting.
Should fix #785
cc @sefk
> Fix config/env/dev migrate setting

- CONTRIBUTING.md
18F just published its Code of Conduct:  https://18f.gsa.gov/2015/05/12/on-culture-change-a-code-of-conduct/
We swtiched to Google Hangouts & needed to move to GSA calendar so we can have multiple hosts
> link code-of-conduct, update calendar link

- assets/styles/application.css
Currently, a long word/url can cause this behavior:
This change causes the same content to be rendered like this:
This is a low-risk change as this class is only used in one place.
> Fixes non breaking long strings in Project Description

- assets/email/layouts/default/html.ejs
Removes unsubscribe link from the HTML footer, because it points to a not yet implemented part of the user profile.
> Remove unsubscribe link from html email footer

- assets/js/backbone/apps/browse/views/browse_main_view.js
- adds escape to new (unmatched) search terms in the select2 drop down
- renders html correctly for new (unmatched) terms in the select2 drop down
This crept in when escapes were added.
Closes #799 
Thanks for the report @nhu313
> Fix html new term suggestion in search w/escape

- assets/js/backbone/apps/events/list/controllers/event_list_controller.js
The event modal wasn't being removed after closing, which caused the validation of other modals, such as for creating a new opportunity, to try to validate the empty event form.
This PR removes the modal on its hide event.
> Remove event modal after close. Fixes #803

- assets/js/backbone/apps/events/list/controllers/event_list_controller.js
The RSVP selector was using a class present on all event attendance buttons (rsvp) to toggle the buttons. So instead of toggling the singular events values when someone RSVP'd or cancelled, it would toggle all of the event buttons, causing unexpected behavior.
--This replaces the vague selector with a more specific selector that only operates on the emitted event's currentTarget (e.currentTarget).
Closes #804
Thanks for the bug report @nhu313!
> Make event rsvp selector more specific

- api/controllers/AuthController.js
- assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js
- assets/js/backbone/apps/tasks/show/views/task_item_view.js
This PR redirects the user to the referring url after logging in with an oauth account. This addresses the issue where logging into the `/people` page redirected away.
It also changes the way the volunteer modal is triggered after log-in so that it works with oauth accounts.
Closes #724
> Redirect to referring url after oauth login

- CONTRIBUTING.md
- Gruntfile.js
- package.json
Some improvements to the development workflow to speed things up. Now, during development, simply run `npm run watch` to start the application and have it restart on changes.
Removes the grunt-based watch task in favor of `npm run watch`, which uses nodemon. Modifies the default grunt task run on `sails lift` to only build the dev assets, which is faster because it avoids uglifying the files.
:ship: :dash:
> Faster dev builds with npm run watch

- assets/styles/application.css
Fixes #844: Constrains modal textareas by only allowing them to be resized vertically.
Tested in Firefox 38, Chrome 43
> only allow modal textareas to be resized vertically

- api/controllers/UserController.js
- api/services/utils/task.js
- api/services/utils/user.js
Fixes #848,
This solution uses the existing error reporting code in the `UserController`, which sends a 400, and results in a blank page. I'm currently working on the 404 page issue (#149) to make the frontend a little more helpful when this happens.
*edit: also fixes the `/tasks/:id` route, which suffered from the same problem. The `/project/:id` route [already performs this check](https://github.com/18F/midas/blob/devel/api/services/utils/project.js#L12)*
> handle NULL responses from findOne() query

- assets/js/backbone/components/tag_factory.js
I believe select2 was supposed to do this transparently, but seems to be disabled (probably because of the HTML emitted by `createSearchChoice()`).
> escape contents of tags

- api/policies/protectAdmin.js
- config/policies.js
prevents people from arbitrarily turning themselves into admins via the API.
> added filtering policy for user UPDATE requests

- assets/js/backbone/apps/comments/list/controllers/comment_list_controller.js
The templating engine is correctly escaping data [here](https://github.com/18F/midas/blob/devel/assets/js/backbone/apps/comments/list/templates/comment_item_template.html#L30), however, when strings (that contain HTML entities) are retrieved from attributes, [they become unescaped](http://stackoverflow.com/questions/11224362/getattributename-unescapes-html).
> escape the comment author's name

- assets/js/backbone/apps/nav/templates/nav_template.html
- assets/styles/application.css
- assets/styles/theme.css
Fixes #859 
Simply switches to a horizontal divider when in narrow/mobile mode.
> Fix navbar divider for mobile

- assets/js/backbone/apps/admin/views/admin_dashboard_view.js
Fixes #865 
~~This PR no longer stores comments in the database in escaped form. [This `html()` call](https://github.com/18F/midas/blob/devel/assets/js/backbone/apps/comments/new/views/comment_form_view.js#L133) was returning entities, whereas the `text()` call below was returning raw content.~~ This PR also adds `marked` comment rendering to the admin panel, and uses it to escape the contents, rather than the escaping in `_.template()`. ~~This appears to be backwards compatible with a database full of escaped comments.~~
> Fixed HTML comments in admin panel with marked

- assets/js/backbone/apps/browse/templates/project_list_item.html
Issue #759. Removed image from groups that don't have one uploaded. (Groups still show default image on their individual page.)
> Removed image from groups that don't provide one.

- assets/js/backbone/apps/attachment/templates/attachment_item_template.html
simply adds the `download` attribute to the link, so that files aren't downloaded with names like `2`, and `38`.
> Download files with the correct filename, rather than file ID

- Gruntfile.js
When uploading files to `assets/uploads`, they need to be copied to `.tmp/public` to be served. This copies them as part of the default grunt task in charge of copying assets. For production, this isn't an issue, because we serve assets from S3.
> Copy local image assets to tmp static file directory on build

- assets/js/backbone/apps/people/controllers/people_map_controller.js
In Firefox and Chrome, the D3 ajax request on the `/people/` page for `world-110m.json` can fail. This is because it requests
`http://localhost:1337/people/data/world-110m.json`
instead of,
`http://localhost:1337/data/world-110m.json`
This only happens when there is a trailing slash in the page URL (`http://localhost:1337/people/`). The solution was simply to make the path relative to the root, which now operates correctly. Tested in Firefox 38 and Chrome 43.
**To reproduce**
- point Firefox or Chrome at `http://localhost:1337/people/`. *(Note the trailing slash)*
- The map will fail to load, and the network inspector will show a 404'd request for `world-110m.json`
> Fixed ajax error for world data in Firefox

- api/controllers/UserController.js
- api/policies/project.js
- api/policies/task.js
- assets/js/backbone/apps/browse/browse_app.js
- assets/js/backbone/apps/project/show/controllers/project_show_controller.js
- assets/js/backbone/apps/tasks/show/views/task_item_view.js
- assets/js/backbone/entities/projects/project_model.js
- assets/js/backbone/entities/tasks/task_model.js
This is a first crack at #149 
When an item isn't found, instead of showing blank project/task/profile pages, this PR uses the `alert_template` to display the error the from the server.
**It turns this:**
**into this:**
> added simple 404 responses

- api/policies/user.js
- config/policies.js
prevents non-admin users from updating other user's information via the API.
I edited an existing policy to allow admins to perform UPDATEs to arbitrary users. The only other place where this policy was used is [`UserEmailController.findAllByUserId`](https://github.com/18F/midas/blob/devel/config/policies.js#L64) (handled [here](https://github.com/18F/midas/blob/devel/api/controllers/UserEmailController.js#L10-L16)), which I *believe?* is also an acceptable admin action.
> Prevent users from editting other users via the API

- config/policies.js
Prevents non-admin users from modifying existing tags in the database. [It was noted](https://github.com/18F/midas/blob/devel/api/controllers/TagEntityController.js#L11-L15) that this was intended to be secured, and only accessible by admins.
> added admin policy to TagEntity controller

- api/controllers/TagEntityController.js
Since the tag refactor, we do allow authenticated users to create new TagEntities
Follows up on #875
> Remove obsolete comment about TagEntity controller

- api/policies/ownerOrAdmin.js
- api/policies/volunteer.js
- config/policies.js
Plugs another API hole where any user could delete volunteers. The `ownerOrAdmin` policy was already present, but it passes requests that [aren't tasks or projects](https://github.com/18F/midas/blob/devel/api/policies/ownerOrAdmin.js#L11-L14), and the `isOwner` flag was never set. This PR adds a `volunteer` policy that sets the `isOwner` flag, and removes the project/task clause from `ownerOrAdmin`.
**Question**
Would it be better to remove `ownerOrAdmin` in favor of individual `ownsTask`, `ownsProject`, policies? The actual ID checks (to set the isOwner flag) are endpoint-specific, so it might be safer to have this done in one policy, rather than require a dependent policy to set flags.
> fixed ownerOrAdmin policy for volunteer destroy

- api/policies/comment.js
- config/policies.js
Previously, comment UPDATE requests were processed without question. With this policy, only comment owners, and admins are allowed to alter existing comments.
> Prevent users from updating comments they don't own

- assets/js/backbone/apps/admin/views/admin_tag_view.js
- assets/js/backbone/apps/profiles/show/views/profile_show_view.js
- assets/js/backbone/apps/tag/show/views/tag_show_view.js
- assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- assets/js/backbone/components/tag_factory.js
Frontend changes only
I was about ready to start adding new tag fields to the profile page for my client, when I noticed a lot of redundant code regarding Tag dropdowns. This PR helps keep things DRY by using the TagFactory where complicated `select2` calls were before. To do this, a handful of new options and existing code was added to the TagFactory.
80% of the TagFactory code you see being changed is actually just code moving from place to place. There were various versions of the same chunks of `select2` code floating around inside Midas. I have gathered them into the TagFactory, and provided extra options where neccessary. The remaining calls to `select2` are either trivial, or transact with endpoints other than `/api/ac/tag` (for instance, the `task_edit_form_view` uses …
> Slight refactor of the TagFactory

- api/controllers/UserController.js
Prevents problems where `/user/info/:id` is accessed with an invalid user ID, and returns an error. This error (produced by `services.utils.user.getUser()`) simply was not being handled soon enough.
Here's an example crash:
```
/var/lib/openshift/5570cea95973cad867000020/app-root/runtime/repo/api/controllers/UserController.js:53
if (reqId !== req.route.params.id) user.username = null;
^
TypeError: Cannot set property 'username' of null
at /var/lib/openshift/5570cea95973cad867000020/app-root/runtime/repo/api/controllers/UserController.js:53:56
at /var/lib/openshift/5570cea95973cad867000020/app-root/runtime/repo/api/services/utils/user.js:711:34
at wrapper (/var/lib/openshift/5570cea95973cad867000020/app-root/runtime/repo/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js …
```
> moved error check to prevent server crash

- api/services/utils/task.js
Just a small patch for something I saw coming up on the staging server.
> Catch for an error when finding tasks with users without tags

- tools/postgres/removeDuplicateUsers.sql
In theory, users shouldn't have been able to create multiple accounts with the same email address. An unreproducible bug allowed this to happen (#548)
With #902, we now enforce a database constraint on the uniqueness of `midas_user.username`. Before that update can be applied, we need to remove an duplicates that would violate the constraint.
This script produces a list of duplicate accounts to be deleted. Once that list has been reviewed, changing `SELECT *` to `DELETE` in the beginning of the query will remove those records.
Modified from https://wiki.postgresql.org/wiki/Deleting_duplicates
It prioritizes keeping enabled accounts and those with recent logins.
> Add script for reviewing and deleting duplicate users

- package.json
- test/demo/data/utils.js
- test/init/init/init.test.js
- test/test.upstart.js
Uses Sails directly instead of over http, avoiding the need for a temporary admin account.
Fixes the demo script. Note, this script still throws an error at the end but it works for getting the data set. Not worth troubleshooting the error as this should be rewritten too like the init script.
> Fix demo script. Simplify init script

- config/settings/sources.js
- tools/postgres/migrateOldTags.js
The autocorrect controller generally returns tags sorted by `id` which is great for most of our use cases. However, it was problematic with the `task-time-estimate` tags as the `id` isn't the best indicator of order for those tags.
This PR sorts `tagEntities` returned through auto-correct by the `updatedAt` field instead of `id`. It also updates a previous migration script (`/tools/postgres/migrateOldTags.js`) to make sure to delete old tags and touch the remaining `task-time-estimate` tags so that the `updatedAt` order is the proper order for UI display.
To close #916
> Sort time tags in proper order

- tools/wordpress-import/convert_xml.rb
- tools/wordpress-import/import-tasks.js
- tools/wordpress-import/import.json
This imports legacy task data from the Wordpress-based Open Opportunities site.
All imported tasks will be associated with user 1. We should change this to Lisa's profile ID as we run it on each environment.
All published, assigned, and completed timestamps are set to the date the task was created.
The associated user and timestamps can be changed by editing the task.
This gives us our best take on getting old data into the system for the admin metrics. Resolves #847 
First, download the export xml from the Wordpress site. Then run
```
$ ruby tools/wordpress-import/convert_xml.rb tools/wordpress-import/digitalservicesinnovationcenter.wordpress.2015-07-27.xml > tools/wordpress-import/import.json
```
to process and convert the xml to a JSON format that can be imported. (h/t to @ultrasaurus …
> Add scripts for importing tasks from Wordpress site

- developer/index.html
- index.html
In #922 @gbinal requested the addition of 18F Google Analytics snippets to the Open Opportunities application as well as the 18f-pages midas site.
This PR is for the static site hosted with 18F-pages only. It adds the supplied analytics snippet to the `index.html` page as well as the `/developer/index.html` page.
Per the issue, both use `UA-48605964-17` as their UA code.
> Include 18F analytics guild snippets

- .travis.yml
- package.json
Travis and our EC2 servers started failing on builds today. It looks like something is no longer compatible with npm v1.4.28. It doesn't seem to be related to new code, because the `master` branch, which passed a test a few days ago now fails without any changes.
A work-around is to just make sure builds use a more recent version of npm. This PR makes sure Travis updates npm before installing the application. And [this](https://github.com/18F/midas-cookbook/pull/37) makes sure the build server does the same.
> Define node and npm versions during builds

- api/notifications/volunteer.create.thanks/notification.js
Subject line of email was HTML escaped. It
no longer does this.
https://github.com/18F/midas/issues/903
> Fix Bad escaping in email subject line

- tools/postgres/init.sh
Ran into a lexical sorting problem when I added my tenth migration script, so I simply added the numeric sorting flag.
> Sort migration scripts numerically

- api/policies/attachment.js
- assets/js/backbone/apps/attachment/templates/attachment_show_template.html
- assets/js/backbone/apps/attachment/views/attachment_show_view.js
- assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js
- config/policies.js
- test/api/sails/attachment.test.js
- test/api/sails/helpers/config.js
- test/api/sails/task.test.js
This restricts file uploads to only users who have been verified in some way:
- admins
- task creators of open or assigned tasks
- task participants of assigned tasks
- project owners (not used for Open Opportunities)
- all signed in users can upload files that have no attachment (like profile photos)
The API will reject any other file upload or attachment requests. The front end selectively hides the "add attachment" button.
Tests for the API should pass.
Resolves #883
> Attachment policy

- assets/js/backbone/apps/attachment/views/attachment_show_view.js
Fixes a small bug that causes a JS error for non-authenticated users in #937
> Bug fix: Test to make sure user object exists

- assets/js/backbone/apps/attachment/templates/attachment_item_template.html
Per #939 any logged in users could delete any attachment on a task/opportunity.
This PR will restrict the ability to delete attachments to admin users and the users who are owners of that attachment.
> Only allow owners or admins to delete attachments

- views/layout.ejs
Per #922 we want to update the Google Analytics snippet with a [new one from the 18F analytics guild](https://github.com/18F/analytics-standards#javascript-code-snippet). The most observable differences are:
0. Force to use `https://` for the collect call
0. `anonymizeIp` and `forceSSL` are enabled.
> New Google Analytics snippet

- assets/styles/application.css
Added overflow: hidden to div.task-show-description
https://github.com/18F/midas/issues/944
> Fix for long link breaks task template

- assets/js/backbone/apps/profiles/show/views/profile_show_view.js
Firefox seems to be caching the first image and not
retrieving the new image when the  CSS is bumped.
Probably because the URL to the image never changes
(for example /api/user/photo/13).
My solution was to put a timestamp as a URL parameter when
retrieving the new image, (ie. /api/user/photo/13?1439337665153).
I believe this busts FF image cache, and forces FF to
get the newly uploaded image.
https://github.com/18F/midas/issues/800
> Fix issue with profile image update in FF

- tools/postgres/schema/current.sql
The `9.sh` migration script added the column `completedBy`, but this was never added to the `current.sql` schema. This will lead to errors such as:
`Details:  error: column task.completedBy does not exist`
if the user is setting up Midas on a fresh database.
> added completedBy column to the current schema

- assets/js/backbone/apps/tasks/new/views/task_form_view.js
We updated the "On going" tag to be "Ongoing" but part of the new task creation view did a string match to provide the user with additional context.
This simply changes that expected string to match the new tag in the database.
Reported by @dhcole in Slack: https://18f.slack.com/archives/midas-public/p1439908358000797
> Update "Ongoing" tag in the new task view

- assets/js/backbone/apps/browse/controllers/browse_list_controller.js
- assets/js/backbone/apps/browse/templates/task_list_item.html
- assets/js/backbone/apps/browse/views/browse_main_view.js
- assets/js/backbone/apps/tag/show/templates/tag_item_template.html
In order to close out #863 I made a few additions to how the list views work (also satisfies #832). With this PR the following functionality should be changed:
0. All "skill" tags should be links. This will be present on the individual opportunity/task and the individual project/working group view as well as the collection views. This is to directly close #863.
0. The link works by passing along the desired tag name in a query parameter to the respective collection. For instance, if you wanted to find all tasks that have been tagged with "javascript" you would navigate to `/tasks?search=javascript`. If you wanted "javascript" and "html" it would be `/tasks?search=javascript+html`.
0. Clearing the search filter criteria should set the URL back to the "clean" state (i.e. `/tasks`)
@dhcole …
> Make tags links to search results

- api/controllers/AdminController.js
- assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html
- assets/js/backbone/apps/admin/views/admin_dashboard_view.js
- assets/styles/application.css
- package.json
This adds support on the admin dashboard for several additional time intervals, in addition to Fiscal Year, as previously supported:
The `undefined` column are tasks with missing dates. Since we started tracking `completedAt`, `publishedAt` and `assignedAt` after the initial launch of the platform, some tasks do not have these dates defined.
Resolves #905
> More time intervals for task metrics

- api/hooks/populateFast/index.js
- config/connections.js
This conditionally replaces the standard `Model.populate()` method with one that's up to ***11 times*** faster. It generates a much simpler SQL query for retrieving associated data from many-to-many relationships.
This solution is implemented as a hook, so it could be spun out into it's own npm module for use on any Sails application. It's generic and gets all of its settings from the standard `populate` method.
To use, set `populateFast: true` on your connection's configuration:
`config/connections.js:`
```js
module.exports = {
postgresql: {
adapter: 'sails-postgresql',
populateFast: true
}
};
```
Since it uses a SQL query, it will only work with adapters that support SQL.
Here are two (previously) slow pages:
Refs #797 
Refs balderdashy/waterline#944
h/t to @sefk for doing the …
> Add populateFast hook for fast many-to-many associations

- api/controllers/UserController.js
There was an uncaught error in the export process for users without tags. This fixes it by not trying to iterate over missing tags. 
Fixes #985
Patched on production to enable exports.
> Fix user export error

- assets/js/backbone/apps/home/views/home_dashboard_view.js
The theme was clashing with our new dashboard to make it look like this:
The culprit was the `.home` class that was still being applied to the dashboard container. I removed the class from the view's render code to ensure that the class is only used for the unauthenticated page.
I wasn't able to get the themes to properly apply locally but I was able to test the removal of this class with Chrome dev tools to yield this:
@dhcole I believe this is ready for review.
> Fix theme collision with new dashboard

- api/controllers/AdminController.js
- assets/js/backbone/apps/admin/templates/admin_main_template.html
- assets/js/backbone/apps/admin/templates/admin_participants_template.html
- assets/js/backbone/apps/admin/templates/admin_task_template.html
- assets/js/backbone/apps/admin/views/admin_main_view.js
- assets/js/backbone/apps/admin/views/admin_participants_view.js
- assets/js/backbone/apps/admin/views/admin_task_view.js
This adds a participants section to the admin reports with a table of all task participants and fields specified by @LisaLNelson:
- Participant
- Participant Agency
- Task Title
- Task Categories
- Task Type
- Task Status
- Task Location
- Task Creator
- Task Creator Agency
- Task Date Published
- Task Date Completed
- Task Date Closes
It also includes a CSV download option.
Resolves #973
Resolves #963
> Add participant table for admins. Includes export csv

- assets/js/backbone/apps/home/views/home_dashboard_view.js
The task/opportunity count on the dashboard can show a number much higher than the number of open tasks. Previously we were using any task that wasn't in the 'completed' state, but now we are ONLY using tasks that are in the 'open' state.
To fix #1014
> Use tasks in 'open' state to calculate large task count

- assets/js/backbone/apps/home/templates/home_badges_feed_template.html
To fix #1034 we want to show all the participants for a given task. Previously we were explicitly selecting for just the first three, but now that has been altered to just display all participants for a given task.
> Show all participants of a task in dashboard feed

- assets/js/backbone/apps/profiles/show/templates/profile_activity_template.html
- assets/js/backbone/apps/profiles/show/views/profile_activity_view.js
- assets/styles/application.css
It was observed that the profile page doesn't show tasks that the user participated in (or created) but have been subsequently marked as "Completed". We were previously using opportunities that were "Open", "Assigned", or in "Draft" state and now we've also included "Completed" in that list.
Fixes #1032 - @dhcole ready for review
> Completed tasks should be displayed on profile view

- .travis.yml
Travis deployments require `sudo`.
> Use sudo for Travis

- api/controllers/AdminController.js
Quick fix for an error that prevented the participants table from loading.
> Skip participant records for missing tasks or users

- assets/js/backbone/config/ui.json
In commit 90d08bc8a59e020e1b4cfe488686c0a937b18bab the setting default was changed from displaying working groups to hiding them. This reverts that back so that working groups are displayed by
default.
cc @ultrasaurus
> Display working groups by default in UI

- api/controllers/VolunteerController.js
- api/models/Volunteer.js
- api/policies/addUserId.js
- assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html
- assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- tools/postgres/migrate/10.sh
- tools/postgres/schema/current.sql
This PR should close #1036, and adds a dropdown menu for admin users to the opportunity edit view. The admin user can select any user in the database to add as a participant and select to generate a notification as well.
Once the admin user completes other edits and saves their changes, the participant relationship will be created.
I think this is ready for review @dhcole.
> An admin can add participants to an opportunity

- assets/js/backbone/apps/tasks/show/templates/task_share_template.txt
> Remove double-escaping for share email template

- assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
To close #1067, I added back in a `div#modal-copy` to the task show template. The modal component was given this selector to use as the `el` but it didn't exist in the DOM/page.
> Add element hook to task show template

- assets/js/backbone/apps/profiles/show/views/profile_activity_view.js
To fix #1098, we want to only pass valid task objects to the template. This PR changes some front end code to filter out any task object that doesn't have the `createdAt` field.
> Ensure that user activity view on profile is populated

- DEPLOY.md
Making sure all the deploy instructions and branches are correct, so changed `dev` to `master` for the production deploy instructions.
> Update production branches in deploy documentation

- .travis.yml
This defines a `B_DOMAIN` global env var in the Travis environment for use with https://github.com/18F/cf-blue-green/pull/24.
This should fix #1097
> Use branch of cf-blue-green that supports env var

- api/models/Badge.js
- api/models/User.js
- assets/js/backbone/apps/home/templates/home_badges_feed_template.html
- tools/postgres/assignHistoricalBadges.js
- tools/postgres/migrate/11.sh
This PR addresses issues that I ran into getting the badges feature onto staging:
0. Silences badge notifications as a default. Since we don't currently have a way to pass that option all the way through the historical assignment would've triggered hundreds of notifications that should've happened in the past. 
0. Updates the `assignHistoricalBadges.js` script to use the updated badge API and to provide feedback to the user running the script.
0. Fix an undefined variable error in `User.js`
0. Remove a client side logging statement that snuck through
Just as a note, I did run into the perennial issue with the `open-opportunities-theme` repo, namely I forgot to update it. I wanted to document that #906 would have been useful in this case.
As a result of the way Cloud Foundry works, when I …
> Silence badge notifications and alter historical badge assignment script

- README.md
Current badge and the related link never resolve to analyzed
code. Code Climate is free and reliable for open source
projects, and code analysis is an important economic tool
for determining technical debt and choosing best places to
invest.
This commit just inserts the HTML for the badge directly into
the README. There are probably workarounds to keep it more
markdown-y, but I didn't feel these made for better readabliity.
> Replaces quantifiedcode.com badge with Code Climate badge

- assets/js/backbone/apps/login/templates/login_template.html
- assets/styles/application.css
On the signup page I changed the good/bad email icon so that it doesn't appear clickable.  I changed the anchor tag to a span so that it doesn't show a dead link at the bottom.  I then added a new class so that the cursor isn't a pointer and doesn't look like a link.
> Make the good/bad email icon not appear as a clickable link

- assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html
- assets/js/backbone/apps/admin/templates/admin_tag_template.html
- assets/js/backbone/apps/browse/templates/profile_list_template.html
- assets/js/backbone/apps/browse/views/browse_main_view.js
- assets/js/backbone/apps/browse/views/profile_list_view.js
- assets/js/backbone/apps/login/templates/login_template.html
- assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html
- assets/js/backbone/apps/profiles/show/templates/profile_share_template.txt
- assets/js/backbone/components/tag_factory.js
- assets/locales/en-US/translation.json
- assets/locales/en/translation.json
Made the term "Agency" a translatable term. The term is used in several places
in the UI. It is also a "tag" item, so certain parts of the UI already were
translatable by changing the name and plural properties in
assets/js/backbone/config/tag.js.
Fix for Issue #1043
> Agency not configurable

- INSTALL.md
and I moved the Windows instructions up to where the others Platforms were. When I was going through the install process on the Mac, I skipped over a couple steps since they seemed like they were located under the Linux install setups. This hopefully clarifies that and adds a table of contents to the top of the install for better navigation.
> Update to Layout in Install Docs and Addition of Table of Contents

- README.md
- package.json
Certain 3rd-party services, like Travis-CI and CodeClimate, don't have the 301 redirects that Github offers. So those URLs needed to be updated separately. Gemnasium's interface didn't really make it easy at first glance to fix the redirect issue. Hopefully it continues to point to `18f/midas` properly.
> tl;dr #907
> Midas redirects

- package.json
Moving from version 0.8.0-rc-1 to version 0.8.0-rc-2.
The `npm import` script needs to properly refer to the package name.
> Release dev to staging

- api/models/Task.js
During the demo at the end of last week, we encountered a bug on staging. This bug prevented badges from being awarded for task completion, though not for publishing tasks.
The logic gate to check for the task state was always returning. This is because this function is called from the beforeUpdate lifecycle callback on the Task model. That means, that the changes (including the state change) have not yet been saved to the database. This results in every task returning early from this function and therefore no badges being assigned.
Instead, we’ll rely on the logic gate that is within the lifecycle callback (the switch/case statement) and assume that anytime this function is called the task has been appropriately marked as “completed”.
> Fix bug currently on staging

- api/controllers/ActivityController.js
- assets/js/backbone/apps/home/templates/home_badges_feed_template.html
The original query for Users only included volunteers. This updated query will include the original task creators as well and allow for badges to show up on the Dashboard.
> Update query for User model to include creator

- docs/badges.md
The image for the Newcomer badge was linked to the wrong asset, fixed.
> fixed badge image

- api/controllers/UserController.js
- api/models/User.js
- api/notifications/comment.create.owner/notification.js
- test/api/sails/admin.test.js
- test/api/sails/user.test.js
Because the `user` object needs to be looked up and modified before being saved, leaving the code as it was before makes the most sense without refactoring this out to a `UserUtil` service.
This PR should touch multiple issues, because of how related they are to the `User` model.
I'll have to verify the changes made here run successfully with `npm run demo`. The previous errors I was experiencing were related to these two methods `enable` and `disable`.
> Revert `UserController` enable and disable

- test/api/sails/attachment.test.js
I thought I had left this behind with my task metrics work,
but it turns out it was in another area of the code. I wanted to
see cleaner tests anyways, so ...
> Removes console logging in a test

- assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html
- assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- package.json
The updating of previously created tasks when not in a "**Draft**" state reverted them into a "**Submitted**" state since the edit screen only had the options of "Submit for Review" or "Save as Draft". This branch updates this behavior to reflect what is in issue #1143.
> [ hotfix ] Save as Draft

- api/controllers/LikeController.js
- api/services/utils/likeActions.js
Thanks @baccigalupi for submitting this PR. This patch turns Likes into a Sails Service used by the Like Controller and minimizes duplicated code.
@baccigalupi original comment
After the last batch of refactors the LikesController showed up
as having the most technical debt. This seemed mostly related to
duplicate methods.
There is still some duplication in the controller actions that I
haven't worked with, but the like and unlike related actions
have be cleaned up:
* Extracts a LikeActions module with three 'classes'
* top level handler that takes dependencies and has two
methods: 'like', 'unlike'
* classes for liking and unliking
> Like controller cleanup v1

- package.json
seems like newer version of casperjs,
either bet4 or beta5 has some incompatibility
ideally we'd fix the root cause for #1247 but hopefully this will get Travis to be green
> pin versions so that tests pass

- assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
also we don’t expect to ever not have ‘task-time-required’
so let’s never display “None”
Only display mdash when there’s a time estimate
Also, display “completedBy” if we have one!
addresses #1090
> Full-time details don’t have ‘task-time-estimate’

- .travis.yml
- CONTRIBUTING.md
- Gruntfile.js
- INSTALL.md
- config/migrations.js
- migrations/20160316223014-initial-schema.js
- migrations/sqls/20160316223014-initial-schema-down.sql
- migrations/sqls/20160316223014-initial-schema-up.sql
- package.json
Replace use of SQL scripts run through psql to handle database
migrations with sails-db-migrate.  New migration scripts are written in
javascript.
Create an initial migration script which will load the initial schema.
(It can also be run against existing databases.)
Update the `migrate` npm task to run the new db-migrate migration
scripts.
Update the `init`, `install`, `demo` npm tasks to perform any pending
database migrations.
Update the `start` and `watch` npm tasks to warn the user about pending
migrations.
Update the Travis CI configuration to create the midas database since
`npm install` now runs the database migrations.
*See #1248 and https://micropurchase.18f.gov/auctions/17*
> Use db-migrate to Manage Database Migrations

- tools/tagtool/tagtool.js
There was a change a while back to how configuration
was structured, perhaps with a SailsJS update
This little tool was missed in the upgrade
> fix tagtool to work with latest config code

- assets/js/backbone/apps/admin/templates/admin_task_template.html
- assets/js/backbone/apps/admin/views/admin_task_view.js
- assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
- assets/js/backbone/config/ui.json
update text for full-detail description #1274
As an admin, it's confusing to see "Open Task" --> publish makes more sense #1277
also: fix typo: "Time Committment" -> "Time Commitment"
> text updates, per feedback from GSA OHRM

- CONTRIBUTING.md
https://chat.18f.gov now supports linking directly to the channel! See https://github.com/18F/chat/pull/5 for more information.
> link directly to chat room

- test/integration/controllers/ActivityController.test.js
**Problem**
`ActivityController` had no tests after I re-added it.
**Solution**
Add two basic tests of the `/api/activity/badges` endpoint - one for the base case of there being no completed tasks w/ associated badges in the system, and one for there being a completed task with an associated badge awarded.
**How to Test**
Tests should pass. No non-test code has been changed in this PR.
---
FYA @ultrasaurus
> ActivityController integration test for the badges endpoint

- api/controllers/TaskController.js
- api/models/Badge.js
- api/models/Notification.js
- api/models/Task.js
- api/models/User.js
- package.json
- test/fixtures/task.js
- test/integration/controllers/ActivityController.test.js
- test/integration/models/Notification-events.test.js
- test/integration/models/Notification.test.js
- test/integration/models/Task.test.js
- tools/demo.js
- tools/lib/modelTools.js
- tools/postgres/importParticipants.js
integration tests for many notifications 
basic Notification model tests
The approach is the test the creation of the Notification models on different events
and separately added an option Notification.trigger async callback
which is tested in isolation
also fixed a number of bugs, brought back code for notifications
updateTask needs to supply the id of the task
in the body, this now throws an error if missing
refactored Task model code, so we’re not calling
lifecycle callbacks from each other
more logging (verbose)
New high watermark in test coverage:
```
Statements   : 33.99% ( 755/2221 )
Branches     : 22.71% ( 293/1290 )
Functions    : 29.4% ( 157/534 )
Lines        : 36.7% ( 741/2019 )
```
> Fix many notifications, some test coverage

- assets/js/backbone/apps/footer/templates/footer_template.html
fixes #1324
also move back to semver #1198
we’ll need to coordinate with version number tags
so from now on tag should start with ‘v’
> version number in footer

- assets/js/backbone/apps/home/templates/home_view_template.html
We talked about this a while back, 
but didn’t get around to fixing till now
We want to engage people as much as possible
and only require registration / login when needed 
for task creation and sign up
fixes: #1325
> Home page call-to-action shouldn’t require login

- test/integration/models/Volunteer.test.js
more concise code to create all of the users at once
with the volunteers that didn’t create badges correctly
so leaving vol creation one-by-one with note about that
this replaces: https://github.com/18F/openopps-platform/pull/1312
re-applied to dev branch and removed commented out code
> refactor volunteer test a little

- assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html
This pull request addresses #1240. I copied the links from [task_form_template.html](https://github.com/18F/openopps-platform/blob/38a2570828aae818e7cdc8e6041b506e0a99eaa3/assets/js/backbone/apps/tasks/new/templates/task_form_template.html). They match [those cited by LisaLNelson](https://github.com/18F/openopps-platform/issues/1240#issuecomment-182423229).
> added links to task edit form template

- assets/js/backbone/apps/admin/templates/admin_task_template.html
in admin/tasks
in 0.9.5, I think there were never volunteers in completed
since server API is now more consistent, bug appeared
fixed in UI in two ways
- don’t display signups for completed tasks (more efficient)
- if vol has no name, display as “Unnamed”
also added comma between names to make it more readable
FYI: this only showed up with production data, didn't appear on openopps-test
> fix bug with undefined volunteer name

- assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
*Problem*
See issue #1276 
*Solution*
Add a conditional in the rendering template that checks for whether the required time commitment is full time, and if so doesn't  render the time commitment estimate.
@ultrasaurus Should we not show the ' 'How much time is needed?' option for  when editing full-time detail tasks? I could stick that in this PR too.
> Don't render time commitments for full-time details

- assets/js/backbone/apps/browse/templates/task_list_item.html
*Problem*
See issue #1293 
*Solution*
Render an entry in the list of info about the task in the browse view clarifying that the task is 'Virtual', ie completable from anywhere
> Add 'Virtual' to tasks with no location tag associated

- assets/js/utils/user.js
This was throwing errors when the database
wasn’t set up special for GSA (and also would
likely have been an issue for other agencies)
> fix for when agency doesn’t have data defined

- assets/js/backbone/apps/tasks/new/views/task_form_view.js
It looks like the code depended on the id of the tag
which was in the database, and that I changed the order
of creation when I re-wrote the scripts that create
the seed data.  Other places in the code it 
used the ‘value’ so I made that change here as well.
> we shouldn’t depend on task-time-required id

- assets/js/backbone/apps/tasks/task-form-view-helper.js
fix for https://github.com/openopps/openopps-platform/issues/1361
When a task is restricted to a specific agency
the model has the attribute ‘restrict’ 
set to the agency abbr
To test:
1. run the scripts to set GSA agency data:
```
node ./tools/postgres/addGSAdomain.js
node ./tools/postgres/addGSAFullTimeDetail.js
```
2. set your agency to be GSA in your profile
3. Create a new task, under “What type of effort is needed?” you should see a checkbox with label:
“Limit Participation to GSA Employees”
the state of the checkbox should be saved and display
with the correct state when the task is edited
> show state of checkbox for restricted tasks

- assets/js/utils/rendererWithExternalLinkSupport.js
- package.json
our custom linked renderer was created in order to 
render links with blank target (see PR https://github.com/openopps/openopps-platform/pull/1092)
it wasn’t actually calling the marked escape
we made a fork of marked that integrates 2 PRs to resolve XSS issue
then copied the escape function to be used by our custom renderer
here's a [good writeup](https://snyk.io/blog/marked-xss-vulnerability/) with more details about the marked vulnerability
> addresses marked XSS vulnerability

- assets/js/backbone/components/markdown_editor.js
fixes #1379
not quite sure how we lost this dependency, 
I think this got broken in 0.10.0
> fix for markdown editor buttons

- assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
should render when task-length tag is missing, 
which is true for some tasks on 18F production/staging
fixes #1380
> check for presence of task-length tag

- assets/js/backbone/apps/footer/templates/footer_template.html
- assets/js/backbone/apps/footer/views/footer_view.js
- assets/js/backbone/config/ui.json
also make the default config use http URL rather than mailto for the google group
configuration is in ui.json
```
"contact": {
"name": "openopps-platform group",
"link": "https://groups.google.com/forum/#!forum/openopps-platform"
},
```
fixes #1384
> make it so footer “contact us” is configurable

- .travis.yml
- INSTALL.md
- config/session.js
- package.json
figured out module dependencies to enable `npm run migrate` as part of `npm install`
this removes a manual step from the deploy when we modify the database
it does require npm version 3.x, so added that to .travis.yml
also updated install instructions, since that is also needed locally
> run migrate before installing

- config/connections.js
- config/session.js
- package.json
Use case: Attempting to deploy the OpenOpps Platform to the Heroku PaaS.
Changes: 
- Assuring that the two places that pull database config from the cfConf fall back to the `DATABASE_URL` in the environment, which is Heroku (and others) preferred method of setting the database.
- Make theming easier to use with Heroku by removing the `_theme` directory on each install.
Testing: Tested locally and on Heroku.
> Changes for easier deployment to Heroku

- api/policies/ownerOrAdmin.js
- package.json
Pairing with @EricSchles on this one.
This patch updates the check for isOwner to propagate down to the `req.body.taskId` which doesn't exist on every request for some reason.
> Patch is so that owners can delete participants

- INSTALL.md
- config/session.js
This PR gets the session.secret from the environment rather than having it hard-coded in the application. It's okay to have it in the code, but this will allow us to invalidate all sessions by just updating the user-provided-service.
> Update where session.secret is coming from

- INSTALL.md
- circle.yml
- config/cors.js
Due to an incident [reported from Gemnasium](https://gemnasium.com/github.com/18F/midas/alerts), we're adding the CORS configuration to SailsJS using the `VCAP_APPLICATION` coming from :cloud:.gov.
> Set CORS configuration from VCAP_APPLICATION

- Dockerfile.simple
- api/models/Notification.js
- assets/js/backbone/apps-router.js
- config/connections.js
- docker-compose.yml
Note that this PR is against #1499, since that seems to be the latest branch right now.
* Run `docker-compose up db` and wait until you see the log message `PostgreSQL init process complete`.  This means that the database has been created.  Then press ctrl-c.
* Run `docker-compose run app npm install --unsafe-perm`.  The `--unsafe-perm` is needed because you're running some startup scripts as root in the container, which `npm` doesn't like. We can fix that in a later PR though.
* Run `docker-compose run app npm run init`.
* Run `docker-compose up` to start everything and visit http://localhost:3000/.
* The docs claim postgres 9.2 is required, but some scripts use features introduced in 9.3.
* The docs are very confusing about what version of node is required, so I just used what was …
> [WIP] Add preliminary docker-compose support.

- package.json
main repo used to be at 18F, now that one is a fork of this one
so URLs should refer to https://github.com/openopps
> fix URL references to refer to openopps repo

- README.md
used relative links for most places
couldn't figure out how to make a relative link to issues, so those are fully qualified to refer to this repo
> link to this repo (instead of 18F)

- GOVERNANCE.md
now it is relative 
I think original reference to 18F Code of Conduct was an error
CoC is link from CONTRIBUTING.md is still broken, which is a separate issue
> fix link to Contribution Guide

- CONTRIBUTING.md
moving to CfA code-of-conduct since 18F link is broken
addressed issue #1521
> fixing code-of-conduct link

- api/notifications/volunteer.destroy.decline/notification.js
Property name on submitted mode is task not taskId. This fix should also fix one area causing application crashes. Resolves #1345.
> Should fix issue #1345

- INSTALL.md
- tools/demo.js
- tools/init.js
I tested install instructions starting from no database, and realized we were missing the db migrate command.
Also, added some instructions that we need to "ctrl-c" after the init and demo scripts, since I thought that might be helpful for new folks.
> Update mac install with dbmigrate command..

- api/document/service.js
Was passing string and expecting object. Fixed the get method for S3 to
expect string.
> Fix invalid parameters for AWS S3 storage integration.

- api/auth/auth.js
- assets/js/backbone/apps/profiles/show/controllers/profile_show_controller.js
Check for 401 and prompt user to log in if not already in order to view
profiles.
Create JSON message for 401 to display on login modal that user must log
in to view this page.
> Fix viewing shared profile from email link bug.

- config/application.js
process.env.[VariableName] is always a string so we have to run a match
to get a boolean type rather than string type.
> Fix cf environment boolean types.

- assets/js/backbone/apps/nav/views/nav_view.js
- assets/js/backbone/browse-app.js
- assets/js/backbone/components/modal_idle.js
- assets/js/backbone/components/modal_idle_template.html
- config/session.js
Added an idle modal that alert the user that due to inactivity they will
be logged out. The warning give the user a three minute window in which
to reset his/her session. Sessions are currently set for 30 minutes,
therefore the user will be alerted after 27 minutes of inactivity.
Reset session timer on page navigation. Reset session timer on 30
keypresses or one minute lapse in time since last keypress.
#1645
> Session expiration warning. 

- assets/js/backbone/apps/tasks/search/templates/internship_search_item.html
- elastic/service.js
Updating search to not show draft and submitted tasks if the user is not an admin. Also updated the search card display to show U.S. Department of State instead of just department of state.
#2708
> removing submitted and draft from search if not admin

- api/auth/passport.js
Added an x-authorization header as the standard authorization header is being blocked.
> x-authorization header code. Authorization header is being blocked.

- assets/js/backbone/apps/internships/show/templates/internship_view.html
- Fix url to internship search page  for issue selecting "skills" from internship view page
#3287
> Bug: Internship skills should search against internship page

- api/auth/dao.js
- api/auth/passport.js
Adding logic to remove duplicate government URIs from other accounts when logging in with an account that has a government URI. 
There is no equivalent github ticket so not able to connect with an issue.
> Add logic to remove duplicate government URI on login

- assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html
- assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Update date format to use "/" instead of "-" since Safari and Firefox
do not support this syntax for date formats
#3561
> Unsupported date format for Safari and Firefox

- assets/js/backbone/apps/nav/templates/nav_template.html
- redirect help link to new window
#2853
> Sitewide: Help links don't open in new window

- api/notification/state.department/firstphase.start.confirmation/template.html
- api/notification/state.department/firstphase.start.confirmation/template.js
- api/v1/cycle/controller.js
- api/v1/cycle/service.js
- config/application.js
- environment.json
Adding primary phase started email once a user starts the primary phase. The email will contain a status on whether the emails were queued and whether the boards were populated.
TFS ticket number 37488
> Adding primary phase started email

- api/admin/export/dao.js
Only show internship information that have been closed... if the closed date is null, show the ones that have a review end date.
#4251
> Bug: Internship .csv includes selectees prior to boards closing

- api/notification/service.js
- api/v1/cycle/service.js
- Since we queue up so many emails for DoS we need to add in
throttling to prevent AWS SES from rejecting email messages
> Throttle DoS emails

- api/opportunity/service.js
- Prevent opportunities going to submit status when changing location
#4284
> Don't send opps back to submit status when edited
