openopps/openopps-platform

api/controllers/UserController.js, api/services/preflight/prepareTaskVolunteerOwnerEmail.js, api/services/utils/user.js, assets/email/templates/taskVolunteerAddedOwnerReply/html.ejs, assets/email/templates/taskVolunteerAddedOwnerReply/text.ejs
Changed where the username was scrubbed from the user object so
that the emails to the task creator could contain contact info.
Also added the contact email to the html and text notification.
Fixes #471
=> Adding the volunteer's email address to task creator notifications.

assets/js/backbone/apps/profiles/show/templates/profile_activity_template.html, assets/js/backbone/apps/profiles/show/views/profile_activity_view.js, assets/js/backbone/apps/profiles/show/views/profile_show_view.js
Previously, the "Opportunities Created" and "Opportunities
Volunteered For" only contained "open" and "closed" tasks.
Now they will contain open, assigned, completed, and archived
tasks. Also fixed a tab issue due to having to task-based
activity tab controls.
Fixes #451
=> Updating the profile activity sections to contain assigned tasks.

INSTALL.md
sails .10 safe mode won't create DB schema
related to #475
=> note migrate 'alter' in install instructions

test/demo/data/utils.js
FYI: make demo failed in last release 0.0.27
don't have the fix yet, but this makes the error more readable
=> make demo works now

INSTALL.md, config/models.js
=> allow sails to alter schema in dev

api/controllers/AdminController.js
=> Filters user count on admin dashboard to include only active users

package.json
another thing needed for deployment now that we're not installing devDependencies
=> request is used in the app, not just for testing

config/env/development.js
Adds a separate config file to override settings when in development: config/env/development.js
Ready for review
=> Add dev config file

api/controllers/AdminController.js, api/models/Task.js, api/models/User.js, assets/js/backbone/apps/admin/templates/admin_dashboard_activities.html, assets/js/backbone/apps/admin/templates/admin_dashboard_table.html, assets/js/backbone/apps/admin/templates/admin_dashboard_template.html, assets/js/backbone/apps/admin/views/admin_dashboard_view.js, assets/js/backbone/config/require_config.js
Shows admins recent activities of all users. Should replace the need to have admins get all email notifications.
Discussion in #489
Closes #489
Refs #487
=> Add recent activity feed to admin dashboard

assets/js/backbone/apps/admin/templates/admin_main_template.html
=> Change admin nav header markup to avoid logo and hover styling

INSTALL.md
=> no longer need this manual step

api/controllers/AuthController.js
After validating a reset token, we need to reset the count of password attempts so the user may log in.
Fixes: #509
=> Actually reset user's passwordAttempts

api/controllers/MainController.js, api/policies/task.js, api/services/utils/task.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/application.css, views/layout.ejs
=> Drafts Part 2

api/models/Volunteer.js, api/services/audience/findTaskVolunteer.js, api/services/dispatch/sendSimpleEmail.js, api/services/notifications/manager.js, api/services/preflight/prepareTaskVolunteer.js, assets/email/templates/taskVolunteerAdded/html.ejs, assets/email/templates/taskVolunteerAdded/text.ejs, config/settings/notifications.ex.js
=> Set up volunteer signup email notification

config/settings/emailTemplates.ex.js
Fixes  https://github.com/18F/midas-open-opportunities/issues/69
=> Add email settings

assets/js/backbone/apps/login/templates/login_password_template.html, assets/js/backbone/apps/login/views/login_view.js
I took a stab at trying to help out with #309 (I came across it while browsing http://www.codeforamerica.org/geeks/civicissues). 
`make test` was passing without errors, but `make demo` had a few errors. I was unsure of differences?
COMMIT MESSAGE
- If user has entered bad information and
pressed 'submit', error messages appear.
This removes those messages as the user
fixes that bad information. Includes:
- if valid email is entered, removes
error messages
- if ALL password criteria are met, it removes
the error message.
- Created checkPasswordConfirm() method and
moved that error messaging below the confirmation.
=> Issue 309 Register errors

config/local.ex.js, config/settings/auth.ex.js
Magic is bad. (looking at you `sails lift`)
=> Use PWD for appPath because `sails lift` doesn't run app.js

assets/js/backbone/apps/login/views/login_view.js
Based on @rpylipow's work in #539, adds client-side validation for the name field too.
=> Validate name field

api/services/utils/task.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js, config/session.js, package.json
- Hide volunteer button from task owners and when task is in draft. 
- Allow admins to see draft tasks associated with projects.
Fixes #538
(merge after #562 )
=> Draft updates

chef/Berksfile, chef/Berksfile.lock, package.json
We made some changes to `master` while troubleshooting problems with the production server. This catches up `devel` to `master`.
=> Update with master

Makefile, config/env/test.js, test-browser/home.js, test-browser/task.js, views/layout.ejs
Adds a test for `/task` and runs the browser tests on `make test`
Closed #330
=> Front-end tests

package.json
=> Revert "Add newrelic to package.json"

app.js, config/settings/newrelic.js, newrelic.js
=> Revert "Update New Relic configuration"

assets/js/backbone/apps/tasks/show/views/task_item_view.js
This fixes the issue. Leaving #582 open for a browser test to catch this in the future.
=> Fix error on task view page for unauthed users

assets/js/backbone/apps/profiles/show/views/profile_show_view.js
=> Check for emails on profiles

assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/update_name_template.html, assets/js/backbone/config/require_config.js
If a user doesn't have a name and clicks the Volunteer (or I'm in) button:
Then continue with the sign up process:
Updated name is saved to user's profile:
Closes #568
=> Ask for name before volunteering

api/controllers/AdminController.js, assets/js/backbone/apps/admin/templates/admin_task_template.html
Adds a draft tab to the admin panel:
Closes #474
=> Show draft tasks on admin task panel

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html
Makes requested copy edit and closes https://github.com/18F/midas-open-opportunities/issues/58
=> Adjust participant copy

api/controllers/AdminController.js, assets/js/backbone/apps/browse/controllers/browse_list_controller.js, assets/js/backbone/components/modal_wizard.js, assets/js/backbone/components/modal_wizard_template.html, assets/js/backbone/entities/tasks/task_model.js, assets/js/backbone/entities/tasks/tasks_collection.js
Adds a "Save Draft" button to the new task workflow.
Closes https://github.com/18F/midas-open-opportunities/issues/61
Closes https://github.com/18F/midas/issues/536
=> Add a "Save Draft" button

api/models/Task.js, api/services/preflight/prepareTaskAllVolunteers.js, api/services/preflight/prepareTaskVolunteer.js, assets/email/templates/taskAssigned/html.ejs, assets/email/templates/taskAssigned/text.ejs, config/settings/emailTemplates.js, config/settings/notifications.js
This is mostly done but we need to decide who gets this notification and whether more development is needed around the assignment workflow. 
Discussion in #579
=> Task assigned email notification

.gitignore, api/controllers/AuthController.js, api/services/utils/user.js
Addresses tasks related to MyUSA integration.
First round includes:
- If user has an existing account (based on email address) merge it with new MyUSA credentials
- Don't create multiple MyUSA accounts on subsequent log-ins.
=> MyUSA Configuration

tools/postgres/set_username_to_email.sh
this script fixes the database errors that were caused by a bug fixed in 0.2.0
script needs to be run manually 
related to https://github.com/18F/midas/pull/591
=> script to fix db errors caused by pre-0.2.0 bug

INSTALL.md
=> remove reference to local.ex.js - no longer used

api/services/utils/task.js
=> Sort first by publishAt descending

assets/js/backbone/apps/admin/views/admin_tag_view.js, assets/js/backbone/apps/profiles/show/views/profile_show_view.js
@ultrasaurus Try this. It should act more intuitively.
=> Adjust profile location behavior

api/controllers/UserController.js, api/policies/authenticated.js, api/responses/forbidden.js, config/auth.js, config/policies.js, package.json, test/api/sails/user.test.js, test/test.upstart.js
- Adds token bearer authentication for API requests using linked oauth accounts (like MyUSA)
- Adds a user profile endpoint that returns sanitized profiles based on query criteria
This is part of integrating Midas with the [hub](https://github.com/18f/hub).
Example profile response:
```json
[
{
"id": 2,
"username": "kids@test.gov",
"name": "Tammy Craig",
"title": "Social Media Director",
"bio": null,
"createdAt": "2015-03-02T16:21:30.000Z",
"updatedAt": "2015-03-02T16:21:39.000Z",
"tags": [],
"likeCount": 0,
"like": false,
"isOwner": true
},
{
"id": 3,
"username": "pran@test.gov",
"name": "Pran Mhasalkar",
"title": "Special Advisor",
"bio": "This is **pran**!",
"createdAt": "2015-03-02T16:21:31.000Z",
"updatedAt": "2015-03-05T15:44:18.000Z",
"agency": {
"tagId": 28,
"id": 84,
"createdAt": …
```
=> API Updates

assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/application.css
also touch up the divider bar to make more visible
I can't find the github issue, but that little divider was an issue in usability testing
hoping this small tweak will make the UI clearer
=> volunteers -> participants

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
it confuses people that there’s no related functionality
fixes #618
=> removing profile like/followers

assets/email/templates/taskVolunteerAdded/html.ejs, assets/email/templates/taskVolunteerAdded/text.ejs
Email text changes for the new volunteer added template
```
Dear David Cole,
We just received your request to claim Who to follow on Twitter? Kids.gov wants to know!! Thanks for your interest in this opportunity – we’re glad you’d like to help out.
Tammy Craig (CCd on this email) is the creator of this task and will contact you directly in the next few days.
If you change your mind or you’re unable to complete the task you expressed interest in please reach out to Tammy Craig and let them know.
Thanks again,
- The midas Team
```
Closes https://github.com/18F/midas-open-opportunities/issues/83
=> Update new volunteer email

assets/js/backbone/components/tag_factory.js, package.json
=> No location bug

api/controllers/AuthController.js, assets/js/backbone/config/ui.json, config/application.js
@ultrasaurus this addresses the after-myusa redirect issue you found while testing. 
@brandtheisey does this cause any trouble for you?
Closes #644 
Closes #646
=> Change /projects redirect to /tasks after authentication and logout

INSTALL.md
These are steps that I found outdated and necessary, respectively, when going through the installation process.
=> Update instructions in INSTALL.md.

assets/js/backbone/apps/browse/browse_app.js, assets/js/backbone/apps/nav/views/nav_view.js, assets/styles/theme.css
@ultrasaurus this should fix the menu issue you found in #648 
Fixes #648
=> Fix menu active states

README.md
This should create the how-you-can-help anchor needed for the ribbon on the gh-pages branch
=> Makes a header for How you can help section

index.html
http://greg.harmsboone.org/midas/
=> Fix the missing image problem

INSTALL.md
Found dead url  and updated the windows instructions thanks to #671 
Thanks @sefk !
=> Note on Windows install instructions

assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
Clicking like, then unlike would make the star disappear and numbers go negative.
=> Task like button could go negative

assets/js/backbone/apps/admin/templates/admin_dashboard_table.html, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/config/tag.js
This is a potential fix for #428. This was a mostly find-and-replace job, as I wasn't sure if the ticket included adding icons where icons did not already exist. 
Suggestions or critiques welcome.
=> Adjust iconography to be more consistent.

.editorconfig
IDE settings for the Midas project. Many IDE's support this as a starting point for a project. For more info, see http://EditorConfig.org.
I tested this with WebStorm and it worked. Haven't tested with other IDE's.
=> Add .editorconfig file for IDE's

assets/js/backbone/apps/comments/list/controllers/comment_list_controller.js, assets/js/backbone/apps/comments/list/templates/comment_item_template.html, assets/js/backbone/apps/comments/list/templates/comment_wrapper_template.html, assets/js/backbone/apps/comments/list/views/comment_item_view.js, assets/js/backbone/apps/comments/new/templates/comment_form_template.html, assets/js/backbone/apps/comments/new/views/comment_form_view.js, assets/js/backbone/apps/project/show/templates/project_item_view_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/application.css
Alternative to #687 
Adds ability to quote/reply.
Adds marked support in the comment input.
Scrolls to comment box if you click reply and the comment box isn't in the viewport.
=> Flat-comments w/ reply and markdown support

assets/js/backbone/apps/events/list/controllers/event_list_controller.js, assets/js/backbone/apps/events/list/templates/event_collection_view_template.html, assets/styles/application.css, config/policies.js
Allows Admin to delete events.
At some point may expand to project owner  && event creator can delete.
This is a CrowdWork required feature.
=> Allow admin to delete events

assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/components/modal_wizard.js, assets/js/backbone/components/modal_wizard_template.html, assets/styles/application.css, package.json
Fix issue #670: As a task creator, I would like to see an introductory screen informing me of expectations.
Involved a bit of hacking in the modal_wizard.js to handle the Save Draft button correctly. This works now, but could be done more generally, see issue #695.
=> Add responsibilities checkbox to "add task" wizard

assets/email/templates/welcomeUser/html.ejs, assets/email/templates/welcomeUser/text.ejs
Implements additional content changes and closes #661
Fixes #680
=> Welcome email text changes

api/controllers/MainController.js, assets/js/backbone/apps/footer/templates/footer_template.html, views/layout.ejs
Fixes #694 
Reads from `package.json` and links to github release.
=> Add version tag to footer

assets/js/backbone/apps/events/list/templates/event_collection_view_template.html, assets/styles/application.css
Change the css / html to match how delete Comments are marked.
Addresses #719
=> Change delete event span to anchor to match delete comment css/html

api/controllers/AdminController.js, assets/js/backbone/apps/admin/views/admin_dashboard_view.js, assets/js/backbone/apps/comments/list/controllers/comment_list_controller.js, assets/js/backbone/apps/comments/list/templates/comment_item_template.html, assets/js/backbone/apps/comments/list/templates/comment_wrapper_template.html, assets/js/backbone/apps/comments/list/views/comment_item_view.js, assets/js/backbone/apps/comments/new/templates/comment_form_template.html, assets/styles/application.css, config/policies.js, package.json
This allows admins to delete non-topic comments.
How to handle topics in general and topics with replies specifically will be addressed at a later date.
This is a CrowdWork requested feature.
=> Allow admin to delete comments

assets/js/backbone/apps/profiles/show/views/profile_show_view.js
Fix bug #631. When the search result doesn't have what you expect, enable a second search from where you were.
=> location search in profile allow second searches

api/controllers/AuthController.js, api/services/utils/user.js
Just some JSLint-recommended cleanup and a catch for a missing user object, which was causing a crash in some cases.
=> Linting and a catch for missing user object

api/controllers/AuthController.js, api/controllers/MainController.js, api/services/utils/user.js, assets/styles/application.css, views/main/index.ejs
This addresses #708 by showing the user an error to tell them their oauth account is already linked to another account. 
@ultrasaurus How's this work for you?
=> Show alert message when user tries to add an oauth account that's linked to another Midas account

api/controllers/MainController.js, views/layout.ejs
Only escape string values. Move backend user code to controller instead of view.
Resolves #748
=> Fix broken backend user data / missing admin link

assets/email/templates/commentOwnerReply/html.ejs, assets/email/templates/commentOwnerReply/text.ejs, assets/email/templates/taskCreated/html.ejs, assets/email/templates/taskCreated/text.ejs
Minor text changes until we find an email text customization solution.
Addresses #735
=> Minor email text changes

assets/styles/application.css
Quick fix for a minor but annoying bug:
=> CSS fix for truncated select2 inputs

api/models/Volunteer.js, api/services/audience/findTaskVolunteer.js, api/services/preflight/prepareTaskVolunteerRemoved.js, assets/email/templates/taskVolunteerRemoved/html.ejs, assets/email/templates/taskVolunteerRemoved/text.ejs, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, config/settings/emailTemplates.js, config/settings/notifications.js
This sends an email to a volunteer if they are deselected / deleted.
Uses text provided by @ultrasaurus .
Repalces #742 
Address #709
=> Add email when vol deselected

config/application.js, config/settings/auth.js
--changes process.env.PWD to a more cross platform -> process.cwd()
Addresses #769
=> Changed env.PWD to env.cwd()

api/services/utils/comment.js, assets/js/backbone/apps/comments/list/controllers/comment_list_controller.js, assets/js/backbone/apps/comments/list/templates/comment_wrapper_template.html, assets/js/backbone/apps/comments/list/views/comment_item_view.js, assets/js/backbone/apps/comments/new/views/comment_form_view.js, assets/styles/application.css
-orders comments from newest to oldest
-places form element on the top of the list
Addresses #775 
Discussion was here https://groups.google.com/forum/#!topic/midascrowd/PeZlcZXOf1s
=> Reverse comment order, form on top

tools/postgres/schema/current.sql
=> Add fd column to file table in current.sql

assets/js/backbone/apps/nav/templates/nav_template.html
Adds alt text to the image for the user icon in the nav bar to make it 508 Compliant.
=> Add nav bar alt text for user icon (508 compliance)

assets/js/backbone/apps/tasks/list/controllers/task_list_controller.js
Causes a task list refresh after task creation in the project / working group view.
Fixes #805
Thanks for reporting this @nhu313!
=> Refresh task list after task creation in project/working group view

tools/postgres/localizeUploads.js
Just a minor update to the migration script for file uploads that adds better logging.
=> Log errors in file localization script.

api/services/utils/task.js
Resolves #813, this rewrites a slow function that gets called on the task page. It should be at least 50% faster now.
=> Rewrite findTasks function to avoid duplicate queries

assets/js/backbone/apps/tasks/list/controllers/task_list_controller.js
Addresses #780,
All added code was already present in the [`browse_list_controller`](https://github.com/18F/midas/blob/devel/assets/js/backbone/apps/browse/controllers/browse_list_controller.js#L122-L175), which functions correctly. The `task_list_controller` was missing the `getTags()` function, which reads the tag data from the display.
Also copied the i18n call for the modal title (which was also present in [`browse_list_controller`](https://github.com/18F/midas/blob/devel/assets/js/backbone/apps/browse/controllers/browse_list_controller.js#L133)).
=> fixed tag submission for task creation via task_list_controller

INSTALL.md
Just instead Midas today so here are some notes from my process
=> Small installation changes

assets/email/templates/taskVolunteerAddedOwnerReply/html.ejs, assets/email/templates/taskVolunteerAddedOwnerReply/text.ejs, assets/email/templates/taskVolunteerAddedSupervisorReply/html.ejs, assets/email/templates/taskVolunteerAddedSupervisorReply/text.ejs, assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/apps/tasks/show/templates/volunteer_supervisor_notify_template.html, assets/js/backbone/apps/tasks/show/templates/volunteer_text_template.html, assets/locales/en-US/translation.json, assets/locales/en/translation.json
This pull request should change all user facing mentions of "volunteer" to "participant".
Should close 18F/midas-open-opportunities/issues/58 18F/midas-open-opportunities/issues/82 and #822
=> Change "volunteer" to "participant

assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
=> escape task owners name

assets/js/backbone/apps/browse/views/browse_main_view.js
Issue #753. Added the desired text for the search bar.
=> Changed search bar placeholder text.

CONTRIBUTING.md
I couldn't find this written up anywhere
so I added to Contribution Guide
=> policy on reviewing pull requests

assets/js/backbone/apps/project/show/controllers/project_show_controller.js, assets/js/backbone/apps/projectowner/show/templates/projectowner_show_template.html, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/application.css
Issue #743. Added names under people's picture for owners, participants, and requestors.
=> Namelabels

tools/tagtool/tagtool.js
Made the tagtool a little more user friendly.
Replaces failures like this (caused by no arguments):
```
/home/brendan/midas/tools/tagtool/tagtool.js:15
if (tagType.length === 0) {
^
TypeError: Cannot read property 'length' of undefined
```
with output like this:
```
This is a tool for loading tags into the database in bulk.
Usage:
./tagtools.js [type] [file]
type - The string type of tags to be loaded
file - file containing a newline delimited list of tag values to be loaded
```
Also changed the permissions to make it executable by the user.
=> Added more console help output to the tagtool

api/controllers/UserController.js, api/models/User.js, api/services/protocols/local.js
Fixes a bug that came up in v0.6.1
=> Allow admins to see other users' email addresses

package.json
Small update, avoids issue raised in #793
=> Update marked to avoid server-side DDOS vulnerability

api/controllers/AdminController.js, assets/js/backbone/apps/admin/views/admin_dashboard_view.js, tools/report/report.js
While debugging the missing task dashboard, I found a few JS errors on the admin pages. These were mostly just edge cases where data was missing.
Also updated the date range for the monthly report.
=> Small bug fixes and updates

assets/js/backbone/apps/nav/templates/nav_template.html, test/browser/profileActions.test.js
User wanted the logged in user's profile
link to contain the user id, so copy/
pasting of this link from browser
location bar would work
https://github.com/18F/midas/issues/469
=> Added user id to end of profile link

api/notifications/task.create.thanks/template.html, api/notifications/volunteer.create.thanks/notification.js, api/notifications/volunteer.create.thanks/template.html
Made clickable links to the opportunity in the email templates.
https://github.com/18F/midas/issues/888
=> Email template changes

assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tag/show/templates/tag_show_template.html, assets/js/backbone/apps/tag/show/views/tag_show_view.js
When in edit mode, all tags are shown in the input
box.
https://github.com/18F/midas/issues/737
=> New and old tags are edited in input box

assets/js/backbone/apps/home/templates/home_view_template.html, assets/locales/en-US/translation.json, assets/locales/en/translation.json
Changed wording
https://github.com/18F/midas/issues/817
=> Changed Hassle Free to Open Opportunities

assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/styles/application.css
Add links, consistent punctuation, adjust alignment:
=> Copy cleanup on task create page

assets/js/backbone/apps/browse/browse_app.js, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/new/views/task_form_view.js, assets/js/backbone/components/tag_factory.js, assets/js/backbone/entities/tasks/tasks_collection.js, assets/styles/application.css, assets/styles/bootstrap.css, assets/styles/theme.css, tools/postgres/migrateOldTags.js
Our new task creation feature deviated from the (now) agreed upon protocol for features that span design and development. In the future, we will ping @GailSwanson/design in the original PR so that we can sort out bugs and design changes in nice, discreet bunches.
That being said, now that we've merged in #932 we have some technical and design bugs to work out (#956, #957) which this PR will address when it is labelled as *Ready for Review*.
There are a few overlapping changes between this PR and #954 so I'll probably accept the #954 changes into `devel` and make sure this branch has no merge conflicts.
Resolves #957 
Resolves #956
=> Task creation fixes and design tweaks

index.html
This adds DAP reporting to the 18F pages part of the app. I'm not sure how to modify the Sails settings for the DAP source for the `devel` branch.
=> Adds DAP reporting to 18F pages part of the app

api/hooks/populateFast/index.js, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tasks/new/templates/task_form_template.html
Fixes a few typos and #971, a bug that came up in 0.7.3
=> Bug fix and typos

.dockerignore, Dockerfile, config/connections.js, config/email.js, config/env/test.js, config/fileStore.js, config/log.js, config/models.js, config/session.js, test/api/sails/helpers/config.js, test/browser/upstart.js, test/init/init/config.js, test/init/init/init.test.js, test/test.upstart.js, tools/docker-start.sh
Packaging Midas as a Docker container makes it for new team members and others interested in the project to quickly get started running the application locally. 
The PR makes a few changes to Midas to make it ready for running in a container:
- Move all settings from config file to env vars (also makes deploying to CloudFoundry possible)
- Allow Midas to run from disk database if postgres DB is not available
- Adjust init script to work with disk database and make it idempotent
And this PR sets up a Dockerfile for building Midas into a docker image. That image is [published on the Docker Hub](https://hub.docker.com/r/18fgsa/open-opps/) as `open-opps`
1. Download and install the [Docker Toolbox](https://www.docker.com/toolbox)
2. Open Kitematic on your Mac (it's installed with the Docker …
=> Set up development container (Docker)

api/controllers/AdminController.js
Some tasks that are complete do not have a complete date, because we added the field for tracking that date a few months into developing this platform. As a result, there is a column of "no date" tasks on the admin dashboard.
This makes it hard to see any progress in task completion. As a way around this, this PR updates the task metrics data to use the createdAt date for any missing completedAt or publishedAt dates. This gives the impression that tasks were completed on the same day they were created. While this is almost certainly not true, it is consistent with how we handled tasks that were imported from Wordpress for Open Opportunities. To more fully address the project, admins would need to edit the dates for each task with missing dates.
Here is what this looks like with data from …
=> Avoid "no date" in metrics

assets/js/backbone/apps/admin/templates/admin_user_template.html, assets/js/backbone/apps/admin/views/admin_user_view.js, config/email.js
This is a change for https://github.com/18F/midas/issues/977
Adds a label below pagination controls.
Let me know if you need any display changes.
=> User count label

README.md
Pretty straightforward. :dancers:
=> Quantified Code badge for static code analysis

api/services/passport.js, assets/js/backbone/apps/browse/views/browse_main_view.js, assets/js/backbone/apps/login/views/login_view.js, assets/js/backbone/apps/tasks/list/views/task_collection_view.js, assets/js/backbone/apps/tasks/new/views/task_form_view.js, config/settings/sources.js, tools/postgres/addGSAFullTimeDetail.js
This pull request should be the first iteration of the full time detail feature. Changes to the application are as follows:
0. There is a script to add a "Full time detail" tag that is restricted to GSA affiliated users
0. A task creator who is also a GSA affiliated user can create tasks with this new tag
0. GSA affiliated users looking for tasks through the regular search interface will see these opportunities, but users that don't have GSA as their agency will not be able to see these tasks.
@GailSwanson ready for your review
To close #988 #989 #990
=> Full time detail option for GSA

assets/js/backbone/apps/browse/views/browse_main_view.js, assets/js/backbone/apps/nav/views/nav_view.js, assets/js/backbone/apps/tasks/new/views/task_form_view.js
Found two more small bugs:
cc @jeremiak 
I've tested locally and will merge once tests pass.
=> Bug fixes for detail branch

assets/js/backbone/apps/profiles/show/templates/profile_activity_template.html, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tag/show/templates/tag_show_template.html, assets/js/backbone/apps/tag/show/views/tag_show_view.js, assets/js/backbone/config/login.json, assets/js/backbone/config/ui.json, assets/styles/application.css, test/browser/profileActions.test.js
The implementation of the new profile, which includes changes to both the display and editing views, per the designs in #962.
@GailSwanson this should be ready for your review.
As a note, badges have been removed from this implementation (though they appear in the designs), but will be re-tackled alongside issue #979.
Resolves #962
=> New profile view

api/controllers/AdminController.js
Small catch to fix an error from deleted data.
=> Skip volunteer if task or user was deleted

api/controllers/MainController.js, api/models/Task.js, api/notifications/task.due.soon/notification.js, api/notifications/task.due.soon/template.html, api/notifications/task.due.today/notification.js, api/notifications/task.due.today/template.html, api/notifications/task.update.completed/notification.js, api/notifications/task.update.completed/template.html, api/notifications/task.update.opened/notification.js, api/notifications/task.update.opened/template.html, config/application.js, config/routes.js
This adds two new notifications
- participants when a task is complete
- task creator when a task is approved
To include a survey link in the task completed notification, set it as either `sails.config.survey` or `process.env.SURVEY_LINK`.
Once #979 is done, we can update the text to include a mention of the badges.
Resolves #959
Resolves #820
Resolves #819
Resolves #960
=> New notifications

api/controllers/AdminController.js, assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html, assets/js/backbone/apps/admin/views/admin_dashboard_view.js
=> Default participants table to empty strings

assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/update_location_agency_template.html, test/browser/config.js, test/browser/profileActions.test.js
If a user does not have their agency or location filled out when they click "Participate" on an opportunity, we want to prompt them to do so. This PR changes behavior so that when such a user wants to participate, we present them with a modal to request their agency and location so that we can update their profile with that information.
@dhcole finally ready for your review
To close #463
=> Prompt users to fill out their profiles if they haven't already

assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/new/views/task_form_view.js
This enables new opportunity creators to specify how many participants they are looking for and fixes #1003 
@dhcole and @GailSwanson - this is ready for review
=> Display select for person count on new opportunity view

.travis.yml
We switched endpoints for the CF endpoint. https://cloudgov.statuspage.io/incidents/fm8ksv9byzdb
@jeremiak one more to get CD working.
=> Update CF endpoint

.travis.yml
CD is still failing. Trying this to make sure the needed var is available.
=> Try export for Travis

api/controllers/MainController.js
This issue prevents the site from responding to curl HEAD requests. Details are here: https://github.com/balderdashy/sails/issues/2094
=> Work around Sails issue in v10

README.md
=> Update test server link

INSTALL.md
Please let me know if you need me to do anything else before this can be merged.
=> update install to fix photo placement, correct numbers

assets/js/backbone/apps/profiles/show/templates/profile_activity_template.html
=> Add missing leading slash for task links

assets/js/backbone/apps/footer/templates/footer_template.html
=> Add email address to footer

assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js
To close #984, the “I’m In” button will be hidden if a task is in either the "completed" or the "archived" state.
=> Hide "I'm in" if opportunity is closed

package.json
=> Bump package.json version number

.travis.yml, package.json
Our last production deploy failed, but now we've got a different `.travis.yml` file. Pushing this through the release process.
=> Staging release to test for Travis prod deploy issues

api/controllers/ActivityController.js, assets/js/backbone/apps/home/templates/home_badges_feed_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
To close #1138 using the `title` attribute on the badge images so that a tooltip will show up when the user hovers over the badge image.
=> Show tooltip with description of each badge

docs/badges.md
resolves https://github.com/18F/openopps-platform/issues/1137
=> documentation for what the badges mean

api/controllers/AdminController.js, api/models/Task.js, api/services/utils/userMetrics.js, test/unit/services/utils/userMetrics.test.js
I looked at the CodeClimate metrics and saw that the AdminController was the source of the highest technical debt with a combination of high churn and high complexity. This set of commits extracts the decoration of users with metrics into a separate service module. That service module houses a class that is unit tested.
Also, in the course of unit testing, I found a bug in the reporting of created projects: the wrong attribute was being used to look up the association.
There is more work that can be done to make the queries use associations, and do queries in a more uniform way, but this set of commits will hopefully make it easier for the next person if more work needs to be done in this area.
=> Admin user metrics extraction

assets/js/backbone/app.js, assets/js/utils/marked_with_external_link_support.js, assets/js/utils/rendererWithExternalLinkSupport.js
I'll be opening a PR on marked for this change, with an option to externalize links.
However, in the meanwhile, this should address #636
=> Now rendering external links with target=_blank

assets/js/backbone/apps/profiles/show/views/profile_show_view.js
This PR should fix #1170 when it's merged in.
=> Discrepant UI edit

.about.yml
need to go with current dashboard feature set
markdown (including line breaks!) is a future feature
=> refactor so “impact” can be one line

.travis.yml, assets/js/utils/rendererWithExternalLinkSupport.js, package.json
This release fixes some reported opportunities results page issues in IE that were introduced in v0.8.2.
=> [ 0.8.4 ] Staging Release

CONTRIBUTING.md, INSTALL.md, README.md
This PR touches a few updates to the documentation while also covering some of the tasks left over in #907.
=> Better documentation

api/controllers/AdminController.js, api/services/utils/taskMetrics.js, api/services/utils/taskMetrics/dateCodeGenerator.js, api/services/utils/taskMetrics/dateDecorator.js, api/services/utils/taskMetrics/stateMetrics.js, api/services/utils/taskMetrics/taskDecorator.js, api/services/utils/taskMetrics/volunteerAgencyMetrics.js, test/api/sails/admin.test.js, test/unit/services/utils/taskMetrics.test.js, test/unit/services/utils/taskMetrics/dateCodeGenerator.test.js, test/unit/services/utils/taskMetrics/dateDecorator.test.js, test/unit/services/utils/taskMetrics/taskDateDecorator.test.js
CodeClimate with using the classic engine which checks complexity (and not just style) shows the AdminController as the top offender. Since that debt translates to real development costs, I took another stab at yanking out some logic and writing tests.
https://codeclimate.com/github/18F/midas/api/controllers/AdminController.js#all
Extracts logic for admin/taskMetrics into a series of modules:
* DateDecorator for generating various sort codes based on a date string
* DateCodeGenerator for generating the right code based on a
group parameter
* StateMetrics for aggregating task counts related to task
states
* TaskDecorator for generating task object decorated with
additional state and date related data
* VolunteerAgencyMetrics for doing additional searches and
aggregating count data
* Top …
=> Extracts more logic out of AdminController into dedicated modules

api/controllers/AdminController.js, api/models/Task.js, api/notifications/task.update.submitted/notification.js, assets/js/backbone/apps/admin/templates/admin_dashboard_table.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/browse/browse_app.js, assets/js/backbone/apps/profiles/show/templates/profile_activity_template.html, assets/js/backbone/apps/profiles/show/views/profile_activity_view.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/new/views/task_form_view.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/change_state_template.html, assets/js/backbone/components/markdown_editor.js, assets/js/backbone/components/markdown_editor_template.html, assets/js/backbone/components/modal_alert.js, assets/js/backbone/components/modal_alert_template.html, assets/js/backbone/entities/tasks/task_model.js, assets/styles/components/_profile.scss, assets/styles/modules/task/_base.scss, assets/styles/modules/task/_form.scss, assets/styles/modules/task/_list.scss, package.json, test/browser/taskActions.test.js
Related updates after our Demo today.
=> [ redux ] Save as Draft

INSTALL.md
=> Install instructions for local dev w/ docker

api/notifications/task.create.thanks/template.html
when a new Opportunity is submitted, the email message should clarify next steps
resolves #1239
=> email text improvement

tools/postgres/schema/current.sql
also removed reference to jeremiakimelman
=> update to latest schema

CONFIG.md, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/new/views/task_form_view.js, assets/js/backbone/components/show_markdown.html, assets/js/backbone/components/show_markdown.js, assets/js/backbone/components/show_markdown_mixin.js, assets/js/backbone/config/ui.json, assets/styles/modules/task/_base.scss, assets/styles/modules/task/_show-markdown.scss, test/browser/taskActions.test.js, test/data/disk.db
fix for #1230 
rebased PR #1262 from @orangewise against dev
added draft of real sample text
integrated doc from wiki with new docs
filled in some other missing UI config doc
=> When I create a Full-Time Detail, I would like to see some helper text

.about.yml, assets/js/backbone/apps/tasks/new/templates/task_form_template.html
Fixing typos reported in:
https://github.com/18F/openopps-platform/issues/1252
https://github.com/18F/openopps-platform/issues/1258
=> fix some typos

api/controllers/ActivityController.js
resolves issue #1278
this doesn’t fix the root cause, but will omit
badges that have null users from the dashboard
(where badge was accidentally awarded to user
who was never assigned to the task)
=> bug fix: left side of dashboard blank

api/controllers/ActivityController.js
resolves issue #1278: left side of dashboard blank
=> 0.9.3.1 -> staging

api/controllers/AdminController.js, api/models/User.js, api/policies/agencyAdmin.js, api/policies/protectAdmin.js, assets/js/backbone/apps/admin/templates/admin_agencies_template.html, assets/js/backbone/apps/admin/templates/admin_main_template.html, assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/admin/views/admin_agencies_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/js/backbone/apps/nav/templates/nav_template.html, config/policies.js, migrations/20160321214134-add-agency-admin.js, package.json, test/api/sails/admin.test.js, test/client/backbone/apps/admin/views/admin_agencies_view.js, test/client/backbone/apps/admin/views/admin_main_view.js, test/client/backbone/apps/admin/views/admin_user_view.js, tools/postgres/migrate/13.sh, tools/postgres/schema/current.sql
integrated https://github.com/18F/openopps-platform/pull/1264
rebased to dev
updated to use new native node migrations
=> Agency admin

test/unit/models/Task.test.js
default property values
submittedAt set after changing state
=> some unit tests for Task properties

docs/save-as-draft.md
=> docs about “Save as Draft”

assets/js/backbone/apps/tasks/new/templates/task_form_template.html
more consistent headers in first section
=> nicer formatting on task new page

api/models/Volunteer.js, test/integration/models/Volunteer.test.js
*Problem*
There was no test coverage for the `Volunteer` model.
*Solution*
Added tests covering `Volunteer` creation and badge assignment. Fixed several issues in the process.
---
FYI @ultrasaurus
=> Add Volunteer model tests and fix Volunteer model bugs

api/controllers/TaskController.js
**Problem**
Attempting to perform a task export resulted in a `500`.
**Solution**
Update outdated property references in `TaskController.export`.
**How to +10/QA**
1. `$ git checkout task-export && npm start`
2. Navigate to [http://localhost:1337/admin/tasks](http://localhost:1337/admin/tasks) and click on the 'download' icon.
3. A .csv file populated with the correct data should download.
---
FYA @ultrasaurus @DavidEBest
=> Correct task creator id field references in TaskController.export

assets/js/backbone/apps/nav/templates/nav_template.html, assets/styles/_custom.scss, assets/styles/app/components/_navigation.scss, assets/styles/main.scss, config/settings/analytics.js, exclude.txt, manifest-dev.yml, package.json, views/layout.ejs, views/main-layout.ejs
changes both here and in the theme itself to make the skinning / config changes work for the federal instance 
also added analytics from 0.9.5
testing:
in the directory above openopps-platform:
```
git clone git@github.com:18F/open-opportunities-theme.git
cd openopps-platform
npm run import --openopps-platform:dir=../open-opportunities-theme
```
=> changes required to make the theme work

.sailsrc, views/layout.ejs, views/main-layout.ejs, views/sails.ejs
in the layouts, conditionally turn off sockets
- when testing
- when configured to be off
following guidance here: https://github.com/balderdashy/sails/issues/3580#issuecomment-185089243
resolves #1330
=> use .sailsrc to turn off sockets

api/controllers/UserController.js, test/integration/controllers/UserController.test.js
fixes #1336
when I look at someone else's profile, 
I see my opportunities
=> UserController.activities - return tasks correctly

api/controllers/AuthController.js
=> destroy session to effectively log out

config/fileStore.js, tools/aws-env-prod.sh, tools/aws-env.sh
now we use an s3 service to create a bucket in cloud.gov (for staging and dev)
currently prod has different names for environment vars
since that was set up using legacy infrastructure
so there’s a diff script for now to for ‘prod’ env 
(which we can remove when this all rolls out to production)
fixes #1338: uploading images fails on staging server
=> s3 setup for cloud foundry

api/services/utils/task.js, assets/js/backbone/apps/nav/views/nav_view.js
also, fixed an error that I found while debugging:
if task is malformed, log error instead of crashing
=> navigate to homepage on logout

assets/js/backbone/apps/admin/templates/admin_task_template.html
tasks should never have a null owner,
but if they do, just log to the console
and still display everything else
=> check for null owners

CONTRIBUTING.md, assets/js/backbone/apps/footer/templates/footer_template.html, assets/js/backbone/apps/footer/views/footer_view.js
mostly 18F => openopps
contact email address => open source google group
=> text updates since the repo has a new home

package.json
changes for moving repo to new home
open source governance model
=> version -> 0.10.3

assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
fixes https://github.com/openopps/openopps-platform/issues/1372
=> fix style for requestor popover

package.json
0.10.6 worked for me (though failed for @rogeruiz in production)
this commit makes dev work for me again
can anyone else test and provide another pair of eyes?
=> revert previous commit

Dockerfile
This seems to have gotten removed at some point. Updated the node version to a more recent release, but otherwise unchanged.
=> Re-adding a Dockerfile to the repo.

assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
the live site sometimes has ‘task-time-required’ missing
needed an extra check 
fixes #1387
=> page renders with ‘task-time-required’ missing

assets/js/backbone/app-run.js
when not logged in, user should not be re-directed to /dashboard
this was broken when I added User object
forgot to test for null user
fixes #1393
=> not-loggedin user should see /

api/notifications/task.create.draft/template.html
Minor grammar correction in the email that gets sent when you save a draft opportunity.
=> Correct grammatical error in template.html

assets/js/backbone/apps/login/views/login_view.js
the User object needs to be created
after login and register, not just
when the page is loaded
https://github.com/openopps/openopps-platform/issues/1405
=> fix create opportunity page

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/new/templates/task_form_template.html
=> Check for agency when display Limit Participation

system-security-plan.yml
=> Authority to operate

assets/js/backbone/apps/browse/controllers/browse_list_controller.js, assets/js/backbone/apps/browse/templates/browse_main_view_template.html, assets/js/backbone/apps/browse/views/browse_main_view.js, assets/js/backbone/apps/browse/views/profile_map_view.js, assets/js/backbone/apps/nav/templates/nav_template.html, package.json
This is currently [available on Staging](https://openopps-staging.18f.gov/profiles) without the map functionality.
=> Bring back the people's tab for search

assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, package.json
This patch adds the owner directly to the modelData being passed to the
server.
=> Pass owner user model to modelData

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/new/templates/task_form_template.html
=> Copy edits

api/notifications/task.update.opened/template.html, api/notifications/volunteer.create.thanks/template.html, api/notifications/volunteer.destroy.decline/template.html
First round of email updates. More to come.
=> Email updates

assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/volunteer_full_time_text_template.html, assets/js/backbone/apps/tasks/show/templates/volunteer_text_template.html, assets/locales/en-US/translation.json
This is for https://github.com/openopps/openopps-platform/issues/1231
=> Add full time and update general confirmations(#1231).

assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/locales/en-US/translation.json, assets/locales/en/translation.json
Probably also require https://github.com/18F/open-opportunities-theme/pull/101 to be merged.
=> Apply to opportunity - change language on button #1428

assets/js/backbone/config/login.json, config/passport.js, config/settings/auth.js
This PR disables the myusa authentication from the application.
=> Remove myusa authentication functionality

CONFIG.md, views/main-layout.ejs
changed CONFIG.md to account for change in environment variable set up.
=> updating config.md

assets/js/backbone/apps/browse/templates/browse_main_view_template.html, assets/js/backbone/apps/browse/views/browse_main_view.js, assets/js/backbone/apps/home/templates/home_dashboard_template.html, tools/lib/dbTools.js
https://github.com/openopps/openopps-platform/issues/1466
=> Filter tasks by agency via query param

README.md
iframe tag wasn't rendering, changed to a simple link
=> embed not working: just link to video

assets/js/backbone/apps/home/views/empty_modal_view.js, assets/js/backbone/apps/home/views/home_dashboard_view.js, assets/js/backbone/apps/home/views/home_view.js
Just uncommenting a few lines of code.
=> Re-enabling the localize call so those values can be changed via the theme.

CONFIG.md
=> fix formatting in CONFIG.md

CONTRIBUTING.md
=> Fix Google JavaScript style guide link.

api/models/Badge.js, assets/js/backbone/apps/home/templates/home_badges_feed_template.html
Fixed issues with incomplete sentences for badge descriptions.
=> Fix grammer issues with badge feeds. Resolves #1501.

assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
Fix javascript error preventing an opportunity from being copied
=> Issue 1529 - Unable to copy existing opportunities

views/main-layout.ejs
Remove view implementation of CRSF since project also contains an AJAX implementation. This should also fix #1532 which was causing server errors and possible crashing.
=> CSRF causing server errors

INSTALL.md
- update Node version
- remove outdated dependency on npm 3
- removed/edited some of the text which I thought was outdated or confusing
=> update install instructions on mac

api/opportunity/controller.js, api/opportunity/dao.js, api/user/controller.js, api/user/service.js, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/entities/profiles/profile_model.js, assets/js/backbone/entities/tasks/task_model.js, assets/js/backbone/entities/tasks/tasks_collection.js, migrations/20171221185750-update-task-people-tag.js
Fixes #1589 to update PUT to a POST since PUT requests are blocked by Akamai WAF.
=> change PUTS to POST in koa branch

tools/lib/dbTools.js
Updated the import tag function in dbTools to insert data value as JSON rather than text.
Fixes #1590.
=>  Correct corrupt demo data set up.

api/activity/controller.js, api/admin/controller.js, api/auth/auth.js, api/comment/controller.js, api/opportunity/controller.js, api/user/controller.js, api/user/service.js
Authentication validation removed from controllers and placed into an
auth.js file. The functions in auth.js determine if users are
authenticated and if he or she has the proper role level to preform
certain operations.
=> Refactor authentication validation.

.elasticbeanstalk/config.yml, api/auth/controller.js, api/auth/service.js
fixes #1596 
Addresses the specific issues that I noticed which happened on user sign up.
=> filter sensitive info before logging

api/auth/controller.js, api/auth/service.js, api/notification/service.js, api/opportunity/service.js, import-theme.js, package.json
Fixed minor coding bug found after deploying latest dev branch out to cloud.gov.
=> Fix bugs found during deploy to dev environment.

api/auth/controller.js, api/auth/service.js, api/notification/service.js, api/opportunity/service.js, import-theme.js, package.json, tools/init-tag-data/task-people.txt, tools/init-tag-data/task-time-required.txt, tools/lib/dbTools.js
Added Full Time Detail to task-time-required.txt.
Updated dbTools tag import funtion to ingore trailing newlines in text
files, and update the split to a regex to handle both Unix and Windows
style line endings.
=> Update TagEntity data load operations.

api/volunteer/dao.js, api/volunteer/service.js
Fix participant notification object to send back the id of the task for the new participant notification.
=> Fix participant notification object

api/document/service.js
If using S3 then return data.Body.
=> Fix issue with S3 file retrieval.

api/document/service.js
=> Fix S3 file retreival bug.

app-koa.js, package-lock.json, package.json
Added koa-cache-control middleware so we can easily set the cache
control response header.
=> Add cache control middleware.

app-koa.js, config/cache.js
Added new file config\cache.js. Currently utilizing cache.public and
cache.noStore options.
=> Set up cache control configuration.

api/user/controller.js
Routes where out of order. Koa routing is first match wins.
=> Fix reset password bug.

assets/js/backbone/apps/nav/views/nav_view.js, gulpfile.js, package-lock.json, package.json, views/layout.ejs
When editting your own profile the window.cache.currentUser was not
calling the User contructor which resulted in a null agency object. This
null object then caused further application failures.
=> Fix edit user bug.

manifest-dev.yml, manifest-prod.yml, manifest-staging.yml, package.json
Update package version to 0.15.0 and update node to 8.9.4.
Update manifest files to use new USAJOBS domains for Open Opportunities.
=> Open Opportunities version 0.15.0.  

app-koa.js, config/application.js
Issue a 301 redirect to any domain making a request other than what is
defined in the HOST environment variable.
=> 301 redirect.

api/user/controller.js, api/user/service.js, assets/js/backbone/entities/profiles/profile_model.js, config/application.js
Fix issue where uploading a picture procedure was flawed. Extra curly
braces caused sucess funtion to not be called.
#1625
=> Upload profile picture procedure.

assets/js/backbone/apps/profiles/show/views/profile_reset_view.js
Make sure we compare the password and confirm password field values. If
not equal then show proper error message. If equal then submit password
reset.
#1616
=> Validate confirm password on password reset.

api/comment/controller.js, api/notification/task.update.completed/template.html, api/opportunity/controller.js, api/user/controller.js, api/volunteer/controller.js, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/comments/list/controllers/comment_list_controller.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/entities/profiles/profile_model.js, assets/js/backbone/entities/tasks/task_model.js, assets/js/backbone/entities/tasks/tasks_collection.js
Adding back HTTP PUT and DELETE verbs after an exception was put in place to use them.
Addresses #1589
=> Add back HTTP PUT and DELETE verbs.

api/document/service.js, package-lock.json, package.json
Set Content-Type header value from file mimeType column value.
Removed file-type dependency.
#1628
=> Fix profile image bug for IE and Edge.

api/auth/controller.js, api/auth/passport.js, api/auth/service.js, api/user/controller.js, migrations/20180123130707-update-midas-user-username.js
Force all username values to lowercase and trim. Created a database migration to update existing username values in midas_user table to lowercase.
#1646
=> Email/username should not be case sensitive.

api/auth/service.js, tools/lib/dbTools.js
- Fix typo on new user registration.
- Add the .lib path when loading dbTools.
TODO: Make logging a dependency injection.
=> Minor bug fixes.

assets/js/backbone/apps/home/templates/home_view_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/app/components/_profile.scss, assets/styles/app/pages/_dashboard.scss, assets/styles/app/pages/_homeview.scss, assets/styles/layouts/profile.scss
Changed spacing on elements throughout the page, and wording in the How
does it work? area.
=> Made Home Page Match InDesign

assets/js/backbone/apps/browse/views/browse_main_view.js, assets/js/backbone/apps/profiles/list/controllers/profile_list_controller.js, assets/js/backbone/apps/profiles/list/templates/profile_list_table.html, assets/js/backbone/apps/profiles/list/templates/profile_list_template.html, assets/js/backbone/apps/profiles/list/views/profile_list_view.js, assets/js/backbone/browse-app.js, assets/styles/app/pages/_search.scss, assets/styles/component/card/opportunity.scss
Updated People page to match InDesign. Also moved People page to its own
template so its no longer sharing a template with Search/Tasks.
=> Update People Page

assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/templates/admin_user_template.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/admin/views/admin_user_view.js
User tab was not being updated properly when switching from Tasks tab.
Add an id attribute to the table content for User tab and Task tab.
=> Correct page content issue on admin dashboard.

assets/js/backbone/apps/browse/templates/browse_main_view_template.html, assets/styles/app/pages/_search.scss, assets/styles/app/pages/task/_base.scss, assets/styles/component/card/opportunity.scss
Updated the filters on the side of the Search page to more closely match
InDesign.
=> Updated Filters on Search Page

api/notification/layout.html, api/notification/service.js, manifest-dev.yml
Update email base layout to include new OPM branding and no
OpenOpportunities logo.
#1567
=> Apply OPM branding to emails.

assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/styles/layouts/profile.scss, assets/styles/main.scss, views/layout.ejs
More changes necessary for alerts to display correctly.
=> Addiitional Alert Files

assets/js/backbone/apps/admin/templates/admin_agencies_template.html, assets/js/backbone/apps/admin/templates/admin_dashboard_template.html, assets/js/backbone/apps/admin/templates/admin_participants_template.html, assets/js/backbone/apps/admin/templates/admin_tag_template.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/templates/admin_user_password.html, assets/js/backbone/apps/admin/templates/admin_user_template.html, assets/js/backbone/apps/attachment/templates/attachment_show_template.html, assets/js/backbone/apps/attachment/views/attachment_show_view.js, assets/js/backbone/apps/comments/new/templates/comment_form_template.html, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_settings_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/components/alert_template.html, views/403.ejs, views/404.ejs, views/500.ejs
Updating alerts across the site to match Design System.
=> Updating Alerts

assets/styles/app/pages/_dashboard.scss, assets/styles/layouts/profile.scss
Small styling fixes on landing page and profile edit page.
=> Small Styling Fixes on Landing Page and Profile Edit Page

assets/js/backbone/apps/profiles/show/views/profile_reset_view.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/components/markdown_editor_template.html, assets/styles/app/pages/task/_form.scss, assets/styles/app/pages/task/task.scss
Not quite finished, but close!  Some styling on the mark up changed and will show up on Profile.
=> Task create new updates.

.gitignore, gulpfile.js, package-lock.json, package.json
Separate install and build procedure
Add package-lock file
=> Update install and build procedures

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/new/views/task_form_view.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/browse-app.js, assets/js/backbone/components/modal.js, assets/js/backbone/components/modal_idle_template.html, assets/js/backbone/components/modal_template.html, assets/js/backbone/entities/tasks/tasks_collection.js, views/layout.ejs
Update the layout, verbiage, and styles of the design system for the Create/Edit Opportunies.  Update the modals to the design system.  Create reusable modal.
#1563
#1667
#1665
#1666
#1668
#1669
#1715
=> Update Create/Edit and modals to design system standards

assets/js/backbone/apps/home/templates/home_view_template.html, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/nav/views/nav_view.js, assets/styles/app/pages/_homeview.scss, assets/styles/component/nav.scss
Update top navigation to show current location and update top navigation
styles.
=> Update Top Navigation

assets/js/backbone/components/modal_idle.js, views/layout.ejs
Update layout to add closing section tag. Update modal js to add missing ":".
=> Update Layout and Modal JS

assets/js/backbone/apps/login/templates/login_create_template.html, assets/js/backbone/apps/login/templates/login_password_template.html, assets/js/backbone/apps/login/views/login_create_view.js
Fix the validation on all fields, fix validation on submit of create
account.
=> Fix validation and create account functionality

assets/styles/app/pages/_search.scss, assets/styles/component/card/opportunity.scss, assets/styles/layouts/profile.scss
Update filter spacing to match Design System.
=> Update Filter Spacing

assets/js/backbone/apps/tasks/show/templates/participants_template.html
Fix javascript error that occurs when viewing
an opportunity when not logged in.
=> Fix error when not logged in 

config/session.js
- Set session timeout to 15 minutes as required
by security policy
#1733
=> Change session timeout

api/opportunity/controller.js, api/opportunity/service.js, assets/js/backbone/apps/tasks/show/templates/participants_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js
- Add a toggle switch to allow for task creators
to continue accepting applications or to close
the task to prevent additional participants.
#964
=> Add ability to toggle accepting applicants

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/show/templates/copy_task_template.html
Fix the number of characters that is valid from 100 or less to less than
100.
#1715
=> Fix Headline validation of less than 100

api/notification/userpasswordreset.create.token/template.html
Update the verbiage to match the AC.
=> Match verbiage to AC

api/opportunity/service.js
Load full task details need to send the email
notification for task updates.
=> Load full task details for email notification

app-koa.js
Set the cache-control header for the index page
to no-store.
=> Update cache-control header

assets/styles/app/pages/_search.scss, assets/styles/main.scss
Update search input to prevent text from overlapping the search icon.
=> Update Search Input on Search Tasks Page

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/styles/app/pages/_dashboard.scss, assets/styles/app/pages/_search.scss, assets/styles/component/card/opportunity.scss, assets/styles/element/_icon.scss, assets/styles/layouts/profile.scss
Update Profile page styles so icons and other items display correctly in
Internet Explorer.
=> Update Profile Page Styles for IE

api/opportunity/dao.js, assets/js/backbone/apps/login/views/login_create_view.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/new/views/task_form_view.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/copy_task_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/js/backbone/components/modal_idle.js, assets/js/backbone/config/ui.json, assets/styles/component/card/opportunity.scss, migrations/20180301202720-add-task-complete-to-volunteer.js
- Identify assigned participants
- Easily see what state an opportunity is in
=> Opportunity management

assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/tasks/list/templates/no_search_results.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/config/tag.js
Fix typos listed in the document from testing.  Update icons to match
design system.
=> Fix typos, icons, and styles

api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_agencies_view.js, assets/js/backbone/apps/admin/views/admin_dashboard_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/styles/layouts/admin-dashboard.scss
- Fix cannot view tasks tab as agency admin
(#1808)
- Fix tooltip for download csv on focus in
task tab admin dashboard (#1810)
- Fix browser back button action for admin
dashboard (#1803)
=> Administration dashboard

assets/js/backbone/apps/home/templates/home_badges_feed_template.html, assets/js/backbone/apps/home/templates/home_dashboard_template.html, assets/js/backbone/apps/profiles/show/templates/profile_activity_template.html, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/app/pages/_dashboard.scss
Update headings and layout issues on mobile.
=> Update Headings and Layout Issues on Mobile

assets/styles/lib/_select2.scss, assets/styles/main.scss
Change the focus element style site wide from blue blur to dotted outline.
#1669
=> Style focus elements to use new design system standard

api/opportunity/service.js, api/volunteer/controller.js, api/volunteer/service.js, assets/js/backbone/apps/tasks/show/templates/remove_participant_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/styles/component/card/opportunity.scss, assets/styles/component/modal.scss
- Mark participant as completed task (#1168)
- Mark opportunity as complete (#1120)
=> Manage Opportunity

assets/js/backbone/apps/profiles/show/templates/profile_activity_template.html
Update opportunity status to pills on Profile page.
=> Update Profile Opportunity Status

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/components/alert_template.html, assets/js/backbone/config/ui.json, assets/styles/layouts/profile.scss
Hide Duplicate when user is not signed in.  Display no image icon and adjust size to match design.
=> Hide Duplicate when user is not signed in.  Display no image icon and adjust size to match design.

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/new/views/task_form_view.js, assets/styles/app/pages/_task.scss, assets/styles/layouts/profile.scss, assets/styles/lib/_select2.scss
Update tips on Create/Edit Opportunity pages so they no longer go too
far off to the right.
=>  Update Tips for Create/Edit Opportunity

gulpfile.js, package-lock.json, package.json
- Update package procedure steps
=> Create release package 1.4.16

api/opportunity/controller.js, migrations/20180306163044-add-updated-by-to-task.js
- Add _updatedBy_ to task table
- Will allow for tracking of who is marking
task as completed
#1662
=> Task metrics

assets/js/backbone/apps/profiles/list/views/profile_list_view.js, assets/styles/app/pages/_search.scss
Update search bar on People page to add functionality back.
=> Update Search on People Page

assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/styles/component/pill.scss, assets/styles/layouts/admin-dashboard.scss
- Only show action buttons for submitted
opportunities
#1830
=> Administration manage submitted task

api/notification/task.update.submitted/template.html, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/js/backbone/apps/home/templates/home_view_template.html, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/js/backbone/apps/tasks/show/controllers/task_show_controller.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/js/backbone/config/ui.json, assets/locales/en-US/translation.json, assets/locales/en/translation.json, assets/styles/element/_select.scss, assets/styles/lib/_select2.scss, assets/styles/main.scss
Add loading text and icon to Opportunity page and hide once page is
loaded.  Add style to center and padding...site wide using the existing
Fullwidth.text-center class name.
=> Add loading text and icon to Opportunity page

assets/js/backbone/apps/nav/views/nav_view.js, assets/js/backbone/apps/profiles/show/controllers/profile_show_controller.js, assets/js/backbone/apps/tasks/show/views/task_item_view.js
- Requesting login from opportunity page
apply button returns to opportunity page
- Requestion login from shared profile email
returns to profile view
=> Requesting user login 

assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/component/card/opportunity.scss, assets/styles/main.scss
Update task creator name on task page to be a link.
=>  Update Task Creator Name

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/new/views/task_form_view.js, assets/styles/lib/_select2.scss
- Fix errors with data not saving
- Fix improper widths
=> Opportunity create/edit

assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/styles/app/pages/_search.scss, assets/styles/component/card/opportunity.scss
- Update Search page to move "Post opportunity" button to the top of the
page on mobile.
=> Update Search Page

assets/js/backbone/apps/profiles/list/views/profile_list_view.js, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html
- Search for people by name, title, agency or
location
- Remove _cancel application_ link
=> Minor bug fixes

assets/js/backbone/apps/tasks/list/templates/no_search_results.html
Update verbiage on no results returned page to fix gramatically errors,
etc.
=> Update verbiage on no results returned

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/config/login.json
- Replace digitalgov.gov addresses with
openopps-help links
=> Update digitalgov.gov address

views/layout.ejs
Add Google Analytics to Open Opps site.
#1602
=> Add Google Analytics to Open Opps site

assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, manifest-staging.yml, manifest-test.yml
- Fix bug where selection message still displays
after opportunity has been marked completed
#1869
=> Opportunity progress

assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/nav/views/nav_view.js, assets/styles/component/nav.scss
Update nav menu to include People and Opportunities menu items under a
Search dropdown, matching the InVision mockup.
#1893
=> Update Nav Menu For Mobile

assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/layouts/profile.scss
Update with mobile design.  Fix click on oppportunity link.
#1883
=> I am unable to click on the opportunity I created from my profile page

api/notification/volunteer.destroy.decline/template.html, api/notification/volunteer.destroy.decline/template.js, api/volunteer/controller.js, api/volunteer/dao.js, api/volunteer/service.js, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js
- Add ability to cancel your application
- Email opportunity owner of a withdrawn
application
#1751 
#1847
=> Cancel opportunity application

assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/new/views/task_form_view.js
- Fix timezone issue with target completion date
on ongoing opportunities
#1854
=> Opportunity target completion date

assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/components/tag_factory.js, assets/styles/layouts/profile.scss, assets/styles/lib/_select2.scss
- Update Profile edit page to correct mobile display issues
#1883 
#1896
=> Update Profile Edit Page For Mobile

api/user/dao.js, api/user/service.js, assets/js/backbone/apps/profiles/show/templates/profile_participated_template.html, assets/js/backbone/apps/profiles/show/views/profile_activity_view.js, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tasks/show/views/task_item_view.js
- Fix participant status values on profile page
- Fix modal title for application cancellation
confirmation message
#1870
#1751
=> Opportunity updates

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/app/pages/_task.scss, assets/styles/base/_forms.scss, assets/styles/component/card/opportunity.scss, assets/styles/lib/_select2.scss
- Update view opportunity page to correct mobile display issues
#1901
=> Update View Opportunity Page For Mobile

assets/js/backbone/apps/profiles/show/templates/profile_created_template.html, assets/js/backbone/apps/profiles/show/templates/profile_participated_template.html
- Fix IE not supporting ES6 syntax
=> Fix profile page display issue in IE

assets/styles/component/card/opportunity.scss, assets/styles/component/nav.scss
- Update nav menu to show search on mobile and desktop
- Update nav menu to center icons on mobile
#1894
=> Update Nav Menu

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/new/templates/task_form_template.html, assets/js/backbone/apps/tasks/new/views/task_form_view.js, assets/js/backbone/apps/tasks/task-form-view-helper.js, assets/styles/component/card/opportunity.scss
- Update New and Edit Opportunity page to use date fields from Design
System.
#1945
=> Update New/Edit Opportunity Page

app-koa.js, views/layout.ejs
- Apply an MD5 checksum on main stylesheet to help
with cache busting
=> Add cache busting for main stylesheet

api/notification/badge.create.owner/template.html, api/notification/comment.create.owner/template.html, api/notification/layout.html, api/notification/task.create.draft/template.html, api/notification/task.create.thanks/template.html, api/notification/task.create.thanks/template.js, api/notification/task.due.soon/template.html, api/notification/task.due.today/template.html, api/notification/task.update.assigned/template.html, api/notification/task.update.completed/template.html, api/notification/task.update.opened/template.html, api/notification/task.update.opened/template.js, api/notification/task.update.submitted/template.html, api/notification/user.create.welcome/template.html, api/notification/user.create.welcome/template.js, api/notification/userpasswordreset.create.token/template.html, api/notification/volunteer.create.thanks/template.html, api/notification/volunteer.destroy.decline/template.html
- Updated email footer
- Added email closing to layout for consistency
- Removed email closing from individual emails
#1704
=> Updated Email Footer

assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html, assets/js/backbone/apps/admin/templates/admin_dashboard_template.html, assets/js/backbone/apps/admin/templates/admin_main_template.html, assets/js/backbone/apps/admin/templates/admin_task_template.html, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/admin/views/nav_secondary_view.js, assets/styles/layouts/admin-dashboard.scss
Fix display issues for Admin page in mobile view.  Fix secondary navigation.
#1895
=> Bug - Mobile: Admin page display issues

api/notification/layout.html, api/notification/service.js, api/notification/task.update.assigned/template.html, api/notification/task.update.assigned/template.js, api/notification/task.update.completed.participant/template.html, api/notification/task.update.completed.participant/template.js, api/notification/task.update.completed/template.html, api/notification/task.update.completed/template.js, api/notification/task.update.opened/template.html, api/notification/task.update.opened/template.js, api/notification/volunteer.create.thanks/template.html, api/notification/volunteer.create.thanks/template.js, api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- Update opportunity completed email to opportunity participant
- Create new opportunity completed email to opportunity creator
- Update opportunity applicants interested email
- Update email addresses in layout
#1693 
#1694 
#1706
=> Update Opportunity Completed Email

assets/js/backbone/apps/profiles/list/templates/profile_list_template.html, assets/js/backbone/apps/profiles/list/views/profile_list_view.js, assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/styles/app/pages/_search.scss, assets/styles/lib/_select2.scss
- Update Search page and People page to use Design System loading icon
- Update Create account page to add margin to Agency and Location fields
#1886 
#1885
=> Fix Display bugs

api/notification/task.update.completed/template.html
- Updated verbiage and added a link to the survey
#1706
=> Update Opportunity Completed Creator Email

api/notification/comment.create.owner/template.html, api/notification/comment.create.owner/template.js
- Update email sent to task owner when there is a new comment.
#1697
=> Update New Comment Email

api/badge/service.js, api/comment/dao.js, api/comment/service.js, api/notification/controller.js, api/notification/dao.js, api/notification/service.js, api/notification/volunteer.create.thanks/template.js, api/opportunity/dao.js, api/opportunity/service.js, api/user/service.js, api/volunteer/dao.js, api/volunteer/service.js, app-koa.js, config/email.js, migrations/20180330135558-add-bounced-to-midas-user.js, migrations/20180330135816-add-complained-to-midas-user.js, migrations/20180330150044-add-notification-monitor.js
- Set up endpoint to monitor AWS SES bounce and complaint notifications
#1542
=> Email replacement

api/admin/taskmetrics/stateMetrics.js, assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html
As an administrator, I want to generate metrics on how opportunity creators are creating their opportunities.
Note:  Because the data pulled is new, not all years will have creator/admin completed.
#1969
=> As an administrator, I want to generate metrics on how opportunity creators are creating their opportunities

api/opportunity/service.js
=> Open Opps System Email: opportunity approved

api/comment/controller.js, api/comment/service.js, assets/js/backbone/apps/comments/list/controllers/comment_list_controller.js
Fix server side - Users, Admin, Agency Admin can delete comments correctly.
#1970
=> Fix server side - Users, Admin, Agency Admin can delete comments correctly

assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html, assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/home/templates/home_badges_feed_template.html, assets/js/backbone/apps/home/templates/home_view_template.html, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/tasks/list/templates/task_list_item.html, assets/js/backbone/components/markdown_editor_template.html, assets/styles/app/pages/_dashboard.scss, views/layout.ejs
Update various elements and pages for 508 compliance.
=> Update for 508 Compliance

api/notification/layout.html
Update font size for ordered and unordered lists in emails.
#1687
=> Update Email Font Size

api/notification/user.create.welcome/template.html
Update text from task to opportunity.
#1684
=> Update New User Email

assets/js/backbone/apps/tasks/list/templates/task_list_item.html
Fix issues introduced by #2032
=> Fix opportunity list rendering on search page

api/volunteer/dao.js, api/volunteer/service.js
=> Fix sql statement syntax

assets/js/backbone/apps/login/templates/login_forgot_template.html, assets/js/backbone/apps/login/views/login_forgot_view.js
- Make sure we can only submit one password reset request at a time.
#2028
=> Password reset form

assets/img/graphic_search.svg, assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/styles/app/pages/_search.scss
- Add "Find people to help you..." box on Search page
#2033
=> Add Find People Box to Search Page

api/notification/task.update.assigned/template.html, api/notification/task.update.assigned/template.js, api/opportunity/service.js, api/volunteer/controller.js, api/volunteer/dao.js, api/volunteer/service.js, assets/js/backbone/apps/tasks/show/templates/confirm_participant_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/styles/component/card/opportunity.scss, config/application.js
Open Opps System Email <Applicants - Assigned> 
#1695
=> Open Opps System Email <Applicants - Assigned>

assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/styles/app/pages/_search.scss, assets/styles/component/card/opportunity.scss, assets/styles/component/search/search-tab.scss, assets/styles/main.scss
Add new filters to UI and implement UI mobile filter tab.
#2023
#2047
#2048
#2049
#2052
#2053
=> Add Filters and Mobile Filter Tab

api/notification/task.update.not.assigned/template.html, api/notification/task.update.not.assigned/template.js, api/opportunity/service.js
- Send email to non selected participants when an opportunity changes to _in progress_
#1696
=> Open Opps System Email: Applicants - Not assigned

assets/js/backbone/apps/tasks/list/templates/search_pills.html, assets/js/backbone/apps/tasks/list/templates/task_filters.html, assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/js/backbone/components/tag_factory.js, assets/js/backbone/config/ui.json, assets/styles/component/pill.scss, assets/styles/component/search/search-tab.scss
- Add ability to filter opportunity search result by skill, series,
time, and location
- Add USAJOBS search pills
#2048
#2052
#2053
#2050
=> Search filters

assets/js/backbone/apps/home/templates/home_achievements_template.html, assets/js/backbone/apps/home/templates/home_annoucement_template.html, assets/js/backbone/apps/home/templates/home_dashboard_template.html, assets/js/backbone/apps/home/templates/home_network_stats_template.html, assets/js/backbone/apps/home/templates/home_search_template.html, assets/js/backbone/apps/home/templates/home_users_feed_template.html, assets/js/backbone/apps/home/views/home_dashboard_view.js, assets/styles/app/pages/_dashboard.scss, assets/styles/app/pages/_loginview.scss, assets/styles/app/pages/_search.scss, assets/styles/base/_shell.scss, assets/styles/component/card/opportunity.scss, assets/styles/component/nav.scss, assets/styles/layouts/profile.scss
Update landing page header and shell with new and updated sections.
#1992
=> Landing Page (signed in): New page shell

assets/js/backbone/apps/tasks/list/templates/task_filters.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/styles/app/pages/_search.scss, assets/styles/component/search/search-tab.scss
=> Mobile: Search page updates

assets/js/backbone/apps/tasks/list/templates/task_list_template.html
=> Update text in keyword search bar

api/opportunity/dao.js, assets/js/backbone/apps/tasks/list/templates/task_list_item.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/styles/app/pages/_dashboard.scss, assets/styles/app/pages/_search.scss, assets/styles/component/card/opportunity.scss
- Display the headline
- Display 4 lines of the opportunity description
- Display Location, Hours, and Time committment in one line
- Display pills associated to skills
- Display related keywords and make clickable
- Display creator's name with their agency in parenthesis after the name
- Display "Posted on MM/DD/YY" underneath the creator's name
- Add status pill to bottom right
- Add alternating colors for initial icons for the opportunity creator
#2035
=>  Updates to opportunity list card

package-lock.json, package.json
=> Create release package 2.4.3

assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tasks/list/controllers/task_list_controller.js, assets/js/backbone/apps/tasks/list/templates/search_pills.html, assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/js/backbone/browse-app.js, assets/styles/layouts/profile.scss
Add career field to profile view and edit.
#2026
=> Profile Page: Add Career Field

api/opportunity/controller.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/global-utils.js, assets/styles/base/_forms.scss, assets/styles/lib/_select2.scss
- Add "- Select -" to drop downs
- Add agency abbreviation to "Limit participation" checkbox
#1995
=> Fix opportunity create form

assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/js/backbone/global-utils.js, assets/styles/component/card/opportunity.scss
- Fix JavaScript parsing error in IE
#2049
=> Fix parse error

assets/styles/app/pages/_search.scss
- Remove gradient on description text
#2035
=> Update Opportunity Card

assets/styles/component/card/opportunity.scss
- Fix opportunity creator section on search page
#2084
=>  Fix IE rendering issue

api/autocomplete/service.js, assets/js/backbone/global-utils.js, assets/styles/component/card/opportunity.scss, migrations/20180507135119-add-careers-to-tagentity.js, migrations/20180507140634-add-sort-to-task-tagentities.js, tools/init-tag-data/career.txt
- Add new career field values to database
- Add sort key to data column for task related tagentities
- Fix a few small bugs
#2093
=> New career field values

assets/js/backbone/apps/tasks/list/templates/task_filters.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js
- Fix bug with new career field selection values
#2093
=> Fix bug related to additional career fields

assets/js/backbone/apps/home/templates/home_users_feed_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/component/card/opportunity.scss
- Update to add initials, job title, and agency
- Placeholder data for now
#2013
=> Update See Other People Like You Section

api/activity/controller.js, api/activity/dao.js, api/activity/service.js, assets/js/backbone/apps/home/templates/home_search_template.html, assets/js/backbone/apps/home/templates/home_users_feed_template.html, assets/js/backbone/apps/home/views/home_dashboard_view.js, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/styles/app/pages/_homeview.scss
- Add list of opportunities by career
- Add list of opportunities by skill
- Add list of opportunities by location
- Add people like you based on job title
- Add people like you based on agency
- Refactor code issues identified by codeclimate
#2012 
#2013
=> Signed in landing page

assets/js/backbone/apps/home/templates/home_annoucement_template.html, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/app/pages/_dashboard.scss, assets/styles/layouts/profile.scss
- Profile image fix on view and edit profile.
- Add annoucement text.
=> Profile image fix, Add annoucement text

api/opportunity/dao.js, assets/js/backbone/apps/home/templates/home_users_feed_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/component/card/opportunity.scss
- Fix bug where initials show instead of uploaded profile picture
- Fix layout on opportunity view page
#1994
#2013
=> Various bug fixes

assets/js/backbone/apps/tasks/list/templates/task_filters.html, assets/styles/component/search/search-tab.scss
Scroll bar displaying for Filters in IE and Edge 
#2130
=> Scroll bar displaying for Filters in IE and Edge

assets/styles/component/card/opportunity.scss, assets/styles/layouts/profile.scss
- Update requestor figure and initial sizing on desktop
- Update requestor text alignment
- Update actions margins
#1994
=> Update Opportunity Page

assets/js/backbone/apps/home/templates/home_annoucement_template.html
- Landing Page (signed in): Announcement section update to new video.
- Fix Lesley spelling.
- Remove Question link.
#2011
=> Landing Page (signed in): Announcement section

api/activity/dao.js, api/activity/service.js
- Fix bug where people like you by title only returns 1 result
=> Fix "other people like you"

assets/js/backbone/apps/home/templates/home_annoucement_template.html, assets/js/backbone/apps/home/templates/home_search_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js
Add Virtual link to Locations section.
=> Landing Page (signed in): Search opportunities by

assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/styles/component/search/search-tab.scss
=> Mobile: Footer should display on all pages

api/activity/dao.js, assets/js/backbone/apps/home/templates/home_search_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js
- Fix issue where agency restiction filter gets removed
when adding an additional filter
- Fix issue on search filters coming from signed in landing page
=>  Search page filters

api/activity/dao.js
- Fix issue where count was invalid and causing misordered list
under search opportunities by career field
#2012
=> Fix landing page search opportunities by career field

assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/styles/component/card/opportunity.scss
- Fix issue with validation errors on page preventing preview
button from functioning properly
#2172
#2163
=> Fix issues on create opportunity page

assets/js/backbone/components/markdown_editor_template.html
- Remove Help and Preview button
#2164
=> Remove Help From Markdown Editor

assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/styles/app/pages/_task.scss
- Supress headings during preview for data not provided
#2034
=> Opportunity preview page

api/opportunity/dao.js, assets/js/backbone/apps/home/templates/home_achievements_template.html, assets/js/backbone/apps/home/templates/home_users_feed_template.html, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/js/backbone/apps/tasks/list/templates/task_list_item.html, assets/js/backbone/apps/tasks/show/templates/confirm_participant_template.html, assets/js/backbone/apps/tasks/show/templates/participants_not_complete_template.html, assets/js/backbone/apps/tasks/show/templates/remove_participant_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/global-utils.js, assets/styles/app/pages/_task.scss, assets/styles/component/_initials.scss, assets/styles/component/card/opportunity.scss, assets/styles/main.scss
- Fix layout issue on opportunity create/edit
- Fix css layout issues with preview page
- Assign initials color class based on user id
- Apply user initials change to opportunity view page
#1995
#2034
=> Fix layout issues

assets/js/backbone/apps/login/templates/login_create_template.html
- Update link to open in new tab
#2156
=> Update Terms and Conditions Link

api/opportunity/dao.js, assets/js/backbone/apps/comments/list/templates/comment_item_template.html, assets/styles/component/card/opportunity.scss
- Replace silhouette on comments in discussion section with
user initials as per new design requirements
=> Replace silhouette on comments with user initials

assets/js/backbone/apps/tasks/show/templates/remove_participant_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/component/card/opportunity.scss
- Make opportunity owner's name clickable
- Make applicants' names clickable
- Make assigned participants' names clickable
#2212
=> Make profile name hyperlink clickable

assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html
- Remove leading and trailing spaces when saving/updating profile name
#2215
=> Update Profile Page

assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/styles/component/card/opportunity.scss
- Correct overlapping text in IE
- Update min-height depending on what step the opportunity is on
#2212
=> Correct Overlapping Text

assets/js/backbone/apps/tasks/list/templates/task_filters.html
- Do not show participation limitation filter on search page
when user is not logged in
#2004
=> Restrict view of limit participation to agency opportunities

api/opportunity/service.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/styles/app/pages/_task.scss
- Add three fields to the duplicate process that had been left out
- Fix 508 issues from AMP report
#2155
=> Update Duplicate Opportunity Functionality

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_announcement_template.html, assets/js/backbone/apps/admin/views/admin_announcement_view.js, assets/js/backbone/apps/home/templates/home_announcement_template.html, assets/js/backbone/apps/home/views/home_dashboard_view.js, assets/js/backbone/apps/tasks/list/templates/search_pills.html, assets/js/backbone/components/markdown_editor.js, assets/js/backbone/components/markdown_editor_template.html, assets/js/utils/user.js, assets/styles/layouts/admin-dashboard.scss, migrations/20180330150044-add-notification-monitor.js, migrations/20180518160731-add-announcement-table.js, migrations/20180524174234-update-announcement-table.js, migrations/20180524183318-initialize-first-announcement.js
- Site admins can now update the landing page announcement
section from the admin dashboard
#2031
=> Admin: ability to manage announcement text

assets/js/backbone/apps/admin/templates/admin_dashboard_task_metrics.html, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/login/templates/login_create_template.html, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/profiles/list/templates/profile_list_table.html, assets/js/backbone/apps/profiles/show/templates/profile_created_template.html, assets/js/backbone/apps/profiles/show/templates/profile_participated_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/templates/task_preview_template.html, assets/js/backbone/apps/tasks/list/templates/task_filters.html, assets/js/backbone/apps/tasks/list/templates/task_list_template.html
- Update multiple items based on AMP report
=> Update Based on AMP Report

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/announcement/controller.js, api/announcement/dao.js, api/announcement/service.js, app-koa.js, assets/js/backbone/apps/admin/views/admin_announcement_view.js, assets/js/backbone/apps/home/views/home_dashboard_view.js
- Fix issue where logged in non-admin users would experience a
flickering dashboard due to a authentication error
#2238
=> Fix dashboard loading error

assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/component/card/opportunity.scss
- Update profile picture to be a link as well per AC
#2212
=> Update Profile Picture to be Clickable

assets/js/backbone/app.js, assets/js/backbone/apps/tasks/list/views/task_list_view.js, package-lock.json, package.json
- Add autocomplete for related keywords
#2046
=> Keyword Filters Needed

assets/js/backbone/apps/footer/templates/footer_template.html
- Update privacy link in footer to point to correct URL
#2223
=> Update Footer Privacy Link

assets/js/backbone/apps/admin/templates/admin_announcement_template.html, assets/styles/layouts/admin-dashboard.scss
- Update announcement title input from textbox to textarea
#2031
=> Update Admin Announcement Title Input

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/model/Audit.js, assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/templates/change_owner_template.html, migrations/20180531113213-add-audit-log-table.js
- Added ability for admins and agency admins to change the
ownership of an opportunity
#1964
=> Ability to reassign an opportunity to a new creator

api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/templates/admin_agencies_template.html, assets/js/backbone/apps/admin/views/admin_agencies_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/styles/lib/_select2.scss
- Fix issue where agency admin dashboard
was showing opportunities from another
agency causing 403 during reassignment
#1964
=> Admin ability to reassign an opportunity to a new creator

assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/js/backbone/apps/tasks/show/templates/task_progress_template.html, assets/styles/component/card/opportunity.scss
- Add Help icon above the toggle
#2198
=> Update Continue accepting applicants toggle

assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tag/show/templates/tag_show_template.html, assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/js/backbone/config/tag.js
- Update Profile page
- Update Profile edit page
#2246
=> Update Profile Page to Separate Skills and Interests

api/admin/dao.js, api/autocomplete/dao.js, assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/templates/add_participant_template.html, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/components/modal.js, assets/styles/main.scss
- Correct verbage on assigning applicants
- Fix issue where page behind modal can be scrolled
- Fix issue where we are showing disable users on
change owner and assign applicants drop-downs
- Fix keyboard accessibility issues
#1964
#1878
#2280
=> Admin manage opportunities

assets/styles/layouts/admin-dashboard.scss
- Update margin-bottom on button on mobile
#2031
=> Update Bottom Margin on Button

assets/js/backbone/apps/tasks/list/templates/task_list_template.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/styles/component/card/opportunity.scss
- Add results numbers above results on search page
#2235
=> Update Search Results to Display Results Numbers

assets/styles/app/pages/_search.scss, assets/styles/component/card/opportunity.scss
- Add ellipsis to placeholder text when it overflows
#2094
=> Update Placeholder to Add Ellipsis on Overflow

assets/js/backbone/apps/tasks/list/views/task_list_view.js
- Fix issue displaying incorrect counts
#2235
=> Display Viewing Numbers at top of search results

api/auth/controller.js, api/auth/service.js, assets/js/backbone/apps/login/views/login_create_view.js
- Fix issue where users can ignore errors and still create an account
#1849
=>  Require a federal email address

assets/js/backbone/apps/tag/show/views/tag_show_view.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/components/tag_factory.js
- Apply 35 character limit to skills tags
#2211
=> Character Limit on Skills field

api/admin/service.js, api/notification/task.update.applied/template.html, api/notification/task.update.applied/template.js, api/opportunity/service.js, api/volunteer/controller.js, migrations/20180611150555-update-series-1102.js
Updated to send an email notifying the open opportunity creator that someone new has applied.
#2231
=> Email Opportunity creators when people sign up for their opportunity

assets/js/backbone/apps/tasks/list/templates/task_list_item.html, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/styles/app/pages/_search.scss
- Add link around entire opportunity card
- Remove links in description
- Remove links from Career field, Series, and Related keyword tags
#2188
=> Update Opportunity Card To Be Clickable

assets/styles/app/pages/_search.scss
- Update from initial to #000
#2188
=> Update CSS Color For Opportunity Card

api/user/service.js
- When updating or inserting tags check database for existance
of location tags before creating new ones
#2236
=> Remove and prevent duplicate locations

assets/js/backbone/apps/tag/show/views/tag_show_view.js
- Refactor tag_show_view based on issues identified by Code Climate
=> Refactor code base

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/styles/component/nav.scss
- Fix padding issue with top nav menu
- Deleted unused code in profile
=> Fix padding issue with top nav menu and deleted unused code

gulpfile.js
- Update README with newest version after each build
=> Update README during builds

assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js
- Fix issue where the edit form was not being cleaned up causing
form submission on the page
=> Clean up edit opportunity form

README.md, gulpfile.js
- Fix omission of 'v' on the version designation
=> Fix README

api/document/controller.js, api/document/service.js, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/styles/layouts/profile.scss
- Fix issue where profile photograph does not update after
successful upload
- Fix issue where proper error message does not display after
failed upload attempt
#1852
=> Profile photograph upload

assets/styles/layouts/profile.scss
Update Profile submit button style to align properly in IE.
#2316
=> Align Profile Buttons

assets/styles/app/pages/_search.scss
- Reduce opportunity card width to prevent cards from displaying as one column at certain browser widths
#1898
=> Reduce Opportunity Card Width

assets/styles/component/pill.scss
- Make pills full-width like the Design System
#2256
=> Update Pills to Display Per Design System

migrations/scripts/addParentAbbrToTaskRestrict.js, migrations/scripts/fixTaskRestrictValue.js
resolves issues #2331 
error: operator does not exist: json ->> boolean
hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
adding parens in some places and an explicit type case to`text` in one place resolved this issue for me
=> fix migration error: operator does not exist: json ->> boolean

assets/js/backbone/apps/admin/views/admin_announcement_view.js, assets/js/backbone/apps/admin/views/admin_dashboard_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/js/backbone/apps/admin/views/admin_task_view.js, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/js/backbone/apps/home/views/home_dashboard_view.js, assets/js/backbone/apps/home/views/home_view.js, assets/js/backbone/apps/login/views/login_view.js, assets/js/backbone/apps/profiles/list/views/profile_list_view.js, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/apps/tasks/list/views/task_list_view.js, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/styles/app/pages/_search.scss, views/layout.ejs
- Update pages to show loading icon
#2157
=> Add Loading Icon to Every Page

assets/styles/lib/_jquery-fileupload.scss
- Fix layout issue affecting IE
#1852
=> Photo upload: Issues with upload process

assets/js/backbone/components/modal_template.html, assets/styles/component/modal.scss
- Update header text color
- Update footer button size
#2278
=> Fix Modals to Match Design System

api/user/dao.js, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/js/backbone/apps/login/views/login_forgot_view.js, assets/js/backbone/apps/profiles/show/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/show/templates/profile_share_template.txt, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/styles/component/card/opportunity.scss, assets/styles/lib/_select2.scss
- Don't display errors until tab out or save/preview for series and forgot login.
- Filter out disabled users.
- Removed i18 for Profile.
=> Create Opportunity: Don't display errors until tab out or save/preview and filter out disabled users

assets/styles/component/nav-secondary.scss
Move link to the right and make it smaller according to the mock
#2334
=> Update Navigation Styling and Location of Sign Out

api/activity/dao.js
- Only display participants that were marked "task completed"
#2323
=> Latest achievements on home page

assets/styles/app/pages/_task.scss, assets/styles/lib/_select2.scss, package-lock.json
- Change class to prevent bottom border disappearing too early
- Remove style to allow dotted border to show all around active field
#2248
=> Correct Display Issues For Select2 Fields

README.md, manifest.yml, package-lock.json, package.json
- Update NodeJS buildpack for Cloud Foundry
- Roll NewRelic back to 3.1.0 as newer version are breaking
=>  Create release package 3.3.3

views/layout.ejs
- Update CSS so the background shows in IE and Edge
#2157
=> Update Loading Icon Background

assets/styles/lib/_select2.scss
- Remove the width to surrounding list item for Chrome
#2247
=> Update Skills and Series Input Widths

assets/js/backbone/apps/profiles/show/views/profile_reset_view.js
Fix to hide loading icon after register or reset page loads.
#2157
=> Loading icon issues

assets/js/backbone/apps/tasks/list/views/task_list_view.js
- Refactor code to better meet standards.
- Added settimeout to prevent flashing.
#2251
=> Mobile: Screen flashing after entering skills/filters

assets/js/utils/user.js
- Fix parse error in user who only do not enter full name
=>  Fix user initials

api/admin/dao.js, api/admin/service.js, assets/js/backbone/app.js, assets/js/backbone/apps/admin/templates/admin_summary_template.html, package-lock.json, package.json
- Pull user metrics counts
- Pull opportunity metric counts
#2363
#2364
=> Admin section 1 Users and Opportunities

api/admin/dao.js, assets/js/backbone/apps/admin/templates/admin_summary_template.html
- Add line for total users
#2363
=> Admin Dashboard: Section 1 - Users

migrations/20180716152249-fix-agency-data.js, migrations/20180716181646-add-agency-table.js, migrations/20180717115400-migrate-agency-data.js, migrations/scripts/fixAgencyData.js, migrations/scripts/migrateAgencyData.js
- Create normalized table to hold agency records
- Migrate tagentity records of type agency to agency table
#2397
=> Create agency table

api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_agencies_template.html, assets/js/backbone/apps/admin/templates/admin_summary_template.html, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_agencies_view.js, assets/js/backbone/apps/admin/views/admin_main_view.js, assets/styles/layouts/admin-dashboard.scss
- Sort task by createdAt descending order
- Update agency dashboard page to show user and
opportunity breakdown
#2364
=> Admin Dashboard: Section 1: Opportunities

assets/js/backbone/apps/admin/templates/admin_summary_template.html, assets/js/backbone/apps/admin/templates/admin_task_table.html, assets/js/backbone/apps/admin/views/admin_task_view.js
=>  Admin Dashboard: Section 1: Interactions

assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/nav/views/nav_view.js, assets/styles/component/nav.scss
- Add banner to nav
- Adjust CSS so banner doesn't overlay menu items
- Add JS to dismiss banner
#2418
=> Add Login.gov Banner

views/layout.ejs
- Fix issue where toggle logic was flawed
#2426
=> Login.gov: Toggle to turn on and off

assets/js/backbone/apps/admin/templates/admin_user_table.html
- Only display Reset password if Login.gov feature is toggled off
#2429
=> Update User Table to Remove Reset Password

assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/admin/templates/assign_admin_template.html, assets/js/backbone/apps/admin/views/admin_agencies_view.js
Hide Community and refactor.
Fix error from missing syntax.
#2411
=> Admin Dashboard: Sitewide - Section 1 Users - Assign Administrator

assets/js/backbone/apps/admin/templates/admin_user_table.html
- Update logic so header shows when logged in as Agency Admin
#2429
=>  Update Admin Header on Users Table

assets/js/backbone/apps/login/templates/unauthorized.html, assets/styles/app/pages/_homeview.scss
- Add page based on InVision mockup
#2421
=> Add Unauthorized Page

assets/js/backbone/apps/admin/templates/admin_agencies_template.html, assets/js/backbone/apps/admin/views/admin_agencies_view.js
- Remove *X* from select box
#2398
=> Sitewide admin select agency

assets/js/backbone/apps/admin/templates/admin_user_table.html, assets/js/backbone/apps/admin/views/admin_user_view.js
- FIx issue pull proper permission level when managing agency users
- Refactor code to increase maintainability
#2411
=> Assigning administrator permissions

api/admin/dao.js, api/admin/service.js
- Update query to match new requirements
#2365
=> Admin Dashboard: Section 1 - Interactions

assets/js/backbone/apps/admin/templates/admin_agencies_template.html, assets/js/backbone/apps/admin/templates/admin_user_template.html, assets/styles/layouts/admin-dashboard.scss
=> Sitewide Admin: Ability to turn on/off internships per agency

assets/js/backbone/apps/home/controllers/home_controller.js
- Update link to take user to landing page always
#2465
=> Update Open Opps Logo Link

assets/js/backbone/apps/profiles/find/controllers/profile_find_controller.js, assets/js/backbone/apps/profiles/find/templates/profile_find_template.html, assets/js/backbone/apps/profiles/find/views/profile_find_view.js, assets/js/backbone/browse-app.js, assets/styles/layouts/profile.scss
=> Login.gov: Find my Open Opps profile

assets/js/backbone/apps/profiles/home/templates/home_search_template.html, assets/js/backbone/apps/profiles/home/templates/home_users_feed_template.html, assets/styles/app/pages/_dashboard.scss
- Update styles to match InVision mockup
#2455
=> Update Home Page Styles

assets/js/backbone/apps/home/controllers/home_controller.js
Remove dashboard from home controller.
#2455
=> Login.gov: New Open Opps Home page

assets/js/backbone/apps/profiles/find/templates/profile_find_template.html, assets/js/backbone/apps/profiles/home/templates/home_created_template.html, assets/js/backbone/apps/profiles/home/templates/home_participated_template.html, assets/js/backbone/apps/profiles/home/views/home_view.js, assets/styles/app/pages/_dashboard.scss
- Add Create a new account button to Find Profile page
#2476
=> Add Create a New Account Button

api/auth/controller.js, api/auth/dao.js, api/auth/loginGov.js, api/auth/passport.js, api/auth/service.js, api/model/Audit.js, api/notification/find.profile.confirmation/template.html, api/notification/find.profile.confirmation/template.js, app/security-setup.js, assets/js/backbone/apps/login/templates/expired.html, assets/js/backbone/apps/login/views/login_create_view.js, assets/js/backbone/apps/login/views/login_view.js, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/nav/views/nav_view.js, assets/js/backbone/apps/profiles/find/templates/profile_find_template.html, assets/js/backbone/apps/profiles/find/views/profile_find_view.js, assets/js/backbone/apps/profiles/home/controllers/home_controller.js, assets/js/backbone/apps/profiles/home/views/home_view.js, assets/js/backbone/browse-app.js, assets/js/backbone/global-utils.js, config/settings/auth.js, migrations/20180820192323-add-account-staging-table.js
- Ability to link USAJOBS and OpenOpps profiles
#2422
#2454
=> Complete find my profile 

environment.json
=> Update environment variables file

assets/js/backbone/apps/profiles/home/templates/home_created_template.html, assets/js/backbone/apps/profiles/home/templates/home_participated_template.html, assets/js/backbone/apps/profiles/home/views/home_activity_view.js, assets/js/backbone/apps/profiles/home/views/home_view.js
- Add view count of rows
- Add sorting
- Update Show more
#2455
=> Update New Home Page

api/activity/controller.js, api/activity/service.js, api/auth/controller.js, api/model/User.js, api/user/controller.js, api/user/dao.js, api/user/service.js, assets/js/backbone/apps/profiles/edit/templates/profile_edit_template.html, assets/js/backbone/apps/profiles/edit/views/profile_edit_view.js, assets/js/backbone/apps/profiles/edit/views/profile_skills_view.js, assets/js/backbone/apps/profiles/home/templates/home_created_template.html, assets/js/backbone/apps/profiles/home/templates/home_participated_template.html, assets/js/backbone/apps/profiles/home/templates/home_search_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/entities/profiles/profile_model.js
- Profile edit redirect to USAJOBS profile
- Send user to home page on log in
- Fix sort by on home page
- Fix search "Based on your profile"
- Fix save skill from deleting everything else
- Fix profile edit when Login.gov feature is off
#2455
#2461
#2464
=> Update profile and home pages

assets/js/backbone/apps/apply/controllers/apply_controller.js, assets/js/backbone/apps/apply/templates/internship_summary_template.html, assets/js/backbone/apps/apply/templates/process_flow_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/browse-app.js, assets/styles/layouts/internship.scss, assets/styles/main.scss
- Add apply directory
- Add process flow template
- Add CSS for process circle flow numbers
#2491
=>  Add DoS Application Process Circle Flow Numbers

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/js/backbone/apps/profiles/show/views/profile_show_view.js
- Email is a mailto link when viewing another user's profile
#2461
=> Profile page email link

assets/js/backbone/apps/apply/templates/process_flow_template.html, assets/styles/layouts/internship.scss
- Update CSS for mobile
- Add icon next to DoS title
#2491
=> Update Process Flow Circle Numbers

assets/js/backbone/apps/tag/show/views/tag_show_view.js
- Correct placeholder text
#2464
=> User profile skills

assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/footer/templates/footer_template.html, assets/js/backbone/apps/profiles/home/templates/home_achievements_template.html, assets/js/backbone/apps/profiles/home/templates/home_announcement_template.html, assets/js/backbone/apps/profiles/home/templates/home_template.html, assets/js/backbone/apps/profiles/home/views/home_view.js, assets/styles/app/pages/_dashboard.scss, assets/styles/component/card/opportunity.scss
- Add latest achievements
- Add announcement
- Update CSS for latest achievements and announcement blocks
- Add javascript to read more
#2493
=> Add Latest Achievements to Home

assets/styles/lib/_select2.scss
- Remove CSS causing display issues in IE11 and Edge
#2464
=> Update Select2 CSS for IE11 and Edge Display Bug

assets/js/backbone/apps/profiles/show/templates/profile_photo_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, assets/styles/layouts/profile.scss
- Update link wording
- Display alert warning when uploading invalid file type
#2462
=> Profile: Photo upload page

api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js
=> API endpoint to reindex Opportunities.

assets/js/backbone/apps/apply/templates/process_flow_template.html
- Updated Skills label to Languages
#2491
=> Application Process Circle Flow Numbers

assets/js/backbone/apps/apply/templates/internship_summary_template.html
Update style of Continue button per AC.
#2483
=> Department of State: Application Process

api/admin/controller.js, api/admin/service.js, api/auth/auth.js, api/auth/controller.js, api/auth/service.js, api/model/Audit.js, api/model/AuditTypes.js, api/user/controller.js, api/user/dao.js, api/user/service.js
- Log account created
- Log account enabled or disabled
- Log account permission changes
- Log account modification
- Log unauthorized attempt to modify account
#2513
=> OpenOpps: application audit log: account events

assets/js/backbone/apps/login/templates/unauthorized.html
- Update language on unauthorized page
#2553
=> Update language on unauthorized page

assets/js/backbone/apps/login/templates/logout.html
-  Fix punctuation issue
#2541
=> Signout Page

api/auth/controller.js, api/auth/passport.js, api/auth/service.js, api/model/AuditTypes.js, migrations/20180927184515-add-community-table.js, migrations/20180927204217-add-community-skill-table.js, migrations/20180927204235-add-community-user-table.js
OpenOpps: application audit log: password events and Community Tables
#2512 
#2550
=> OpenOpps: application audit log: password events and Community Tables

assets/js/backbone/apps/nav/templates/nav_template.html
-  Remove role from ul element
#2541
=> 508 compliance issue

assets/js/backbone/apps/login/templates/unauthorized.html
=> Unauthorized Trailing add

api/auth/controller.js, assets/js/backbone/browse-app.js, package-lock.json, package.json
- Upgrade to version 2.4.2 of openid-client
- Utlitize new endsession endpoint for OpenID Connect
#2563
=> OpenID Connect endsession endpoint

assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
- Add trailing slash to URL
#2597
=> Update Edit Profile Link

api/notification/task.update.completed/template.html, assets/js/backbone/apps/profiles/home/views/home_view.js
=> Update survey monkey link in opportunity creator email

assets/js/backbone/apps/profiles/home/views/home_view.js
-  Change Arrow function
#2571
=> Fix IE issue sort by opportunity

api/notification/task.update.completed.participant/template.html
- Change survey link in Opportunity Taker email
#2580
=> Change Survey Link

migrations/20180911183343-add-application-table.js, migrations/20180911183749-add-experience-table.js, migrations/20180911183805-add-reference-table.js, migrations/20180911183831-add-language-skill-table.js, migrations/20180911183907-add-education-table.js, migrations/20180914145731-add-application-task.js, migrations/20180927184515-add-community-table.js, migrations/20180927204217-add-community-skill-table.js, migrations/20180927204235-add-community-user-table.js, migrations/20181017125246-rerun-last-ten-migrations.js
- Fix invalid column specs for primary key columns
#2577
=> Fix data migrations

migrations/20181017185543-add-language-table.js, utils/language-data.js
=> Import System Data USaJobs-Language Code

assets/js/backbone/apps/nav/views/nav_view.js
- Remove display of banner and sign in before logout page is displayed
#2611
=> Remove Sign Out Banner Flash

migrations/20181018185159-add-community-type-value-to-community-table.js, migrations/20181018185217-add-FAI-community-record.js
- Add data migration to create FAI community
#2577
=> Create FAI Community

migrations/20181019123740-add-community-id-to-task.js, migrations/20181019123954-migrate-acquisition-opportunities.js, migrations/scripts/migrateAcquisitionDataToFAICommunity.js
- Find any opportunity that was posted for career field
acquisitions and attach them to the FAI community
- Find all creators for those opportunities and attach
them as members of the community
#2576
=>  FAI Community Assignment

assets/js/backbone/apps/tasks/show/views/task_item_view.js
-  Fix next button grayed out button popup
#2610
=> Able to click on grayed out Next Step button

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_community_template.html, assets/js/backbone/apps/admin/views/admin_community_view.js, assets/styles/layouts/admin-dashboard.scss
Added Community Interaction metric queries and UI.
#2599
=> Community Dashboard: Interactions

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/controllers/admin_main_controller.js, assets/js/backbone/apps/admin/views/admin_task_view.js
-  Add Manage Opportunities section
#2612
=> Community Admin: Manage Opportunities

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, assets/js/backbone/apps/admin/templates/admin_community_user_table.html, assets/js/backbone/apps/admin/templates/admin_user_template.html, assets/js/backbone/apps/admin/views/admin_user_view.js
Most of manage user completed.
#2614
=> Community: Manage Members

migrations/20181018185217-add-FAI-community-record.js, migrations/20181107190452-add-DHS-community-record.js
Insert data script to greate DHS community record.
Update to insert data script to greate FAI community record.
#2629
=> DHS: Create Community

migrations/20181113175907-update-DHS-community.js
- Update target audience and duration
#2629
=> DHS Community

assets/js/backbone/apps/tasks/edit/views/task_audience_form_view.js
-  Add selected options to buttons
=> Select Audience functionality

api/community/controller.js, api/community/dao.js, api/community/service.js, api/opportunity/controller.js, app/features.js, assets/js/backbone/apps/tasks/edit/templates/task_edit_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_audience_form_view.js, assets/js/backbone/apps/tasks/edit/views/task_edit_form_view.js, assets/js/backbone/browse-app.js, assets/js/backbone/entities/tasks/task_model.js
- If community is selected opportunity is saved to
community rather than agency
- Fix bug where forms where not being disposed of properly
#2634
=> Create Opportunity: Select Audience functionality

api/admin/controller.js, api/admin/dao.js, api/admin/service.js, api/autocomplete/dao.js, api/autocomplete/service.js, api/community/controller.js, api/community/dao.js, api/community/service.js, api/model/AuditTypes.js, assets/js/backbone/apps/admin/templates/admin_community_user_table.html, assets/js/backbone/apps/admin/templates/invite_member_template.html, assets/js/backbone/apps/admin/views/admin_user_view.js, assets/styles/layouts/admin-dashboard.scss
- Add ability to invite members to a community
- Add audit logging around new functionality
#2534
=> Invite user to Community

api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/tasks/edit/templates/task_audience_form_template.html, assets/js/backbone/apps/tasks/edit/views/task_audience_form_view.js
- When creating a new opportunity show all open communities
#2634
=> Select target audience

api/auth/profile.js
- Fix bug in profile sync that was causing location to not be populated
#2548
=> Incomplete profile message update

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/browse-app.js, assets/styles/app/pages/_task.scss
- Initial check in for unpaid internship page
#2625
=> Add Unpaid Internship

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Add languages display to unpaid internship page
=>  Add Languages

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Add description for showing "save for later page"
#2625
=> Create Opportunity: Unpaid Internship

db/configure-db.js
- We don't need to parse a variable that is already a JSON object
=> Fix elastic search database configure

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html
=> Add Language

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/templates/internship_language_preview.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Add languages section in loop
#2665
=> Create Opportunity: Language Selection display

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/templates/internship_language_preview.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/styles/app/pages/_task.scss
- Update class names for language display
- Add classes for Add Languages
- Remove classes from a few labels
- Update styles
#2625
=> Update Internship Styles

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/styles/app/pages/_task.scss
- Update widths of inputs
- Remove statement about hours
#2625
=> Update Input Widths

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Remove tips box from top of form
- Remove needed hours statement
- Add class to submit buttons
- Add class to Save language button
#2625
=> Remove Tips Box

README.md, migrations/20181211122525-update-DHS-community.js, package-lock.json, package.json
- Set DHS Joint Duty Program Office to be a closed community
- Create release package 7.4.16
=> Update DHS community

README.md, assets/js/backbone/apps/admin/templates/admin_community_user_table.html, assets/styles/layouts/admin-dashboard.scss, package-lock.json, package.json
- Apply fix from version 7.5 to fix invite community issue
- Create release package 7.4.17
=> Fix invite user to community

assets/js/backbone/apps/internships/show/templates/internship_view.html
- Add content to rightrail on Unpaid Internship View
#2652
=> Add Rightrail Content

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/styles/app/pages/_task.scss, assets/styles/component/card/opportunity.scss
Create Opportunity - Unpaid Internship: Preview Page
Merge with dev branch, styles for image and layout.
#2628
=> Create Opportunity - Unpaid Internship: Preview Page

migrations/20181212201920-import-country-data.js, migrations/20181212201930-import-country-subdivision-data.js, utils/country-data.js, utils/countrysubdivision-data.js
- Import country and country subdivision data
#2584
=> Import base location data from USAJOBS

api/notification/task.create.draft/template.html, assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/styles/app/pages/_task.scss, assets/styles/layouts/profile.scss
Update text and link in email.
Update Language title and add help text to Language.
#2628
#2720
=> Unpaid Internship: Preview Page Update and Bug Update text and link

api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/internships/edit/templates/internship_language_preview.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, migrations/20181212131747-add-task-id-change-application-id-to-language-skill.js
- Save Language selection display
- Add fields to task table
#2665
=> Language Selection display

assets/js/backbone/apps/internships/edit/templates/internship_language_preview.html
=> Languages Display

assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Update Text preview Page
-Fix  LanguageDisplay issue
#2665
=> Language Display

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/internships/show/templates/internship_view.html
- Change text for Language requirements
#2652
=> Change Language Text

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html
- Text Changes add language
#2627
=> Add Languages Text Display

assets/js/backbone/apps/tasks/search/views/task_search_view.js, migrations/20181220142511-import-base-system-data.js, migrations/20181220142559-import-language-data.js, utils/agency-data.js, utils/base-data.js, utils/country-data.js, utils/countrysubdivision-data.js, utils/language-data.js
- Migration to import base system data
- Migration to import language data
#2584
#2665
=> Import system data from USAJOBS

api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js, migrations/20181226164629-add-bureau-office-to-task.js
- Add Bureau and office to task table
- display data for save for later page
#2652,#2671
=> Create Opportunity: Unpaid internship View/Apply View of Opportunity

assets/js/backbone/apps/admin/templates/admin_community_user_table.html
- Change label from "Invite user" to "Add user"
#2729
=> Change label

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Update skill levels to reset instead of remaining on last selections
#2665
=> Language Skill Level Reset

db/configure-db.js
- Fix database connection for Elastic
#2669
=> Database configuration for Elastic

api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/internships/edit/templates/internship_language_preview.html, assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/internships/show/templates/internship_share_template.txt, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/js/backbone/browse-app.js, migrations/20190103185343-change-user-id-from-null-to-notnull-language-skill.js
- Fix User Id issue
- Fix delete language issue
- reset fields when Edit mode
- Add share link
#2652
=> Create internship apply

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/styles/component/card/opportunity.scss
- Scroll page to Foreign language section after a language is added
#2627
=> Scroll Page After Adding Languages

assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html
- Update Department of State Logo HTML  and CSS
#2628
=> Update Department of State Logo

api/opportunity/service.js
=> Internship apply

api/notification/task.create.draft/template.html
=> Bug: Draft submitted email has incorrect link

api/opportunity/dao.js, api/opportunity/service.js
- Email community administrators when a new opportunity has been submitted for approval
#2653
=> Create Opportunity Approval Email for Communities

api/notification/community.user.invite/template.html, api/notification/community.user.invite/template.js
=> Email to notify a user they are invited to a community

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/templates/internship_preview_template.html
- Update foreign language additional text
#2628, #2625
=> Update Foreign Language Additional Text

api/opportunity/controller.js, assets/js/backbone/apps/tasks/search/templates/search_pills.html, assets/js/backbone/apps/tasks/search/templates/task_filters.html, assets/js/backbone/apps/tasks/search/views/task_search_view.js, elastic/dao.js, elastic/service.js
Added agency filter logic to URL and in the backend for search.
#2669
=> Add logic to filter on users agency

assets/styles/layouts/admin-dashboard.scss
- Increase click target size for publish/delete icons on admin dashboard
#2364
=> Increase Click Target Size

elastic/dao.js, elastic/service.js
Added keyword autocomplete to the URL and added it to the elastic search query
#2669
=> Add keyword autocomplete as filter

api/cycle/controller.js, api/cycle/dao.js, api/cycle/service.js, assets/js/backbone/apps/admin/templates/admin_community_cycle_template.html, assets/js/backbone/apps/admin/views/admin_community_cycle_view.js, assets/js/backbone/components/modal.js
- Ability for cyclical communities to create new cycles
#2713
=> Community: Add cycle

assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Add a check to see if a language has already been added
#2627
=> Prevent Languages Being Added Multiple Times

api/opportunity/service.js, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js, assets/js/backbone/apps/internships/show/templates/copy_task_template.html, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js
- Add duplicate section for internship
#2652
=> Unpaid internship View/Apply View of Opportunity

assets/js/backbone/apps/tasks/search/views/task_search_view.js, elastic/service.js
Adding a parse int to the page parameter in search as well as adding a check for the user's agency before attempting to apply it in search
#2669
=> Adding parse int to page parameter and adding agency check for users

assets/js/backbone/apps/internships/show/templates/internship_view.html
- Fix order "who we are"
#2652
=>  internship apply page

assets/js/backbone/apps/tasks/list/templates/task_list_item.html
- Fix opporuntiy view link
#2830
=> BUG: Opportunity restrict to agency

assets/js/backbone/apps/admin/templates/admin_community_cycle_template.html, assets/js/backbone/apps/admin/views/admin_community_cycle_view.js
- Fix success modal not displaying proper cycle name
- Refactor validation code around dates
#2713
=> Community: adding cycle from community dashboard

assets/js/backbone/apps/internships/show/templates/internship_view.html
=> Internship Apply internship

migrations/20190114183026-add-hiring-path-to-user.js
- Add hiring_path to user table to designate federal employees from
students
#2749
=> DoS: Student Profile

assets/js/backbone/apps/internships/show/templates/internship_view.html
- U.S. Department of State Internships to open in a new window
#2652
=> Apply internship

assets/js/backbone/apps/tasks/search/controllers/task_search_controller.js, assets/js/backbone/apps/tasks/search/templates/internship_filters.html, assets/js/backbone/apps/tasks/search/templates/internship_search_template.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Add Javascript page
- Update html
#2701
=> Student Shell

api/community/controller.js
- Fixed issue where user had to log in to view opportunities
#2850
=> Bug: User should not have to log in to view an opportunity

api/user/controller.js, api/user/dao.js, assets/js/backbone/apps/profiles/edit/controllers/profile_edit_controller.js, assets/js/backbone/apps/profiles/show/controllers/profile_show_controller.js, assets/js/backbone/apps/profiles/show/templates/profile_photo_template.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, test/database/midastest.sql
- Add functionality to allow USAJOBS student profiles to access Open Opportunities
- Student profiles are only viewable to the student
- Student profiles are not accessible by any other user
- Remove student profiles from people  search
#2749
=> Student Profile

api/opportunity/dao.js, assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Initialize hide fields
- Fix name issue query
#2701
=> Student Shell display

assets/js/backbone/apps/profiles/home/internships/views/internships_view.js
- Fix student landing page sort
- Fix show more link for tables
#2459
=> Fix Student Landing Page Sort

assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/nav/views/nav_view.js, assets/js/backbone/apps/tasks/search/controllers/task_search_controller.js, assets/js/backbone/browse-app.js, assets/js/backbone/global-utils.js, package-lock.json, package.json
- Fix log in requirement for search
- Show both search pages if anonymous user
- Show appropriate search page to logged in user
- Add URLSearchParams polyfill for IE
#2850
=> Bug: User should not have to log in to view opportunities

assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/js/backbone/apps/tasks/search/templates/task_search_item.html, assets/js/backbone/apps/tasks/show/templates/task_show_item_template.html, assets/js/backbone/apps/tasks/show/views/task_item_view.js, assets/js/backbone/browse-app.js
- Selecting an opportunity from search will display a back to search
results link
#2187
=> Add Back to results link for Opportunities

api/autocomplete/controller.js, api/autocomplete/service.js, assets/js/backbone/apps/tasks/search/templates/internship_filters.html, assets/js/backbone/apps/tasks/search/templates/internship_search_template.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/js/backbone/components/tag_factory.js, elastic/dao.js, elastic/task_mapping.json
Updating language, agency, and term filters to go to url and add as a pill. Also added fields to elastic for internships
#2707
=> Updating language, agency, and term filters

migrations/20190122194851-update-community-name-to-community-table.js
=> Update Unpaid Internship community name

assets/js/backbone/apps/tasks/search/views/internship_search_view.js, elastic/service.js
Wiring up language filter and restricting student search to internships
#2707
=> Wiring up language filter and restricting student search to internships

api/community/controller.js, api/community/dao.js, api/community/service.js
- Add API to get list of current internship programs and cycles for
search page filters
#2701
=> Student search page

api/lookup/controller.js, api/lookup/service.js
- Update API needed for search page to not require logged in user
#2850
=> Bug: User should not have to be logged in to view an opportunity

assets/js/backbone/apps/internships/show/templates/internship_view.html
- Add check for null cycle
#2716
=> Display cycle dates on internship opportunity

api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/tasks/search/templates/internship_filters.html, assets/js/backbone/apps/tasks/search/templates/internship_search_cycle_box.html, assets/js/backbone/apps/tasks/search/templates/internship_search_template.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/styles/app/pages/_search.scss
- Add cycle dates display box for internship search page
#2701
=> Student shell page

api/admin/service.js, api/community/controller.js, api/community/service.js, api/user/controller.js, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html
- Only return cycles for a community during the posting cycle
#2717
=> Only return open cycles

api/community/service.js, assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
- Display error on page when no current open cycle
#2717
=>  Display Error If No Open Cycle

assets/js/backbone/apps/tasks/search/views/internship_search_view.js
- Fix Community Id  if undefined
#2701
=> Search student shell page

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
=> Add validation for cycle dates

assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/tasks/search/templates/internship_search_template.html, assets/styles/app/pages/_search.scss
- Update text width
- Add spaces to keywords search
#2701
=> Update Student Search Page

api/auth/passport.js, assets/js/backbone/apps/nav/templates/nav_template.html, assets/js/backbone/apps/tasks/edit/views/task_audience_form_view.js
- Internship page is also viewable by admins and members of
communities with a target audience of students
#2701
=> Search page

assets/js/backbone/apps/tasks/search/views/internship_search_view.js
When adding a location to the internship search, we need to reset the page number back to 1.
#2747
=> Reset page back to 1 after adding a location

assets/js/backbone/apps/tasks/search/templates/internship_search_cycle_box.html
=> Cycle box search internship

assets/js/backbone/apps/tasks/search/views/internship_search_view.js, elastic/dao.js, elastic/service.js, elastic/task_mapping.json
Adding cycle dates to elastic and internship search query
#2654
=> Adding cycle dates to elastic and internship search query

assets/js/backbone/apps/apply/templates/internship_program_template.html, assets/styles/layouts/internship.scss
- Initial check-in for HTML/CSS
#2785
=> Select Internship Opportunities From Search Results

assets/js/backbone/apps/tasks/search/templates/internship_search_cycle_box.html
- Add comma between day and year
#2897
=> Blue application deadline box for unpaid

api/admin/dao.js, api/opportunity/controller.js, assets/js/backbone/apps/tasks/search/templates/internship_search_item.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, elastic/dao.js, elastic/service.js, elastic/task_mapping.json, migrations/20190129131044-add-community-short-name-to-community.js
Adding the agency filter to search as well as updating the internships to store the posting agency. Also added community short name to show the correct community name on the search card.
#2708
=> Adding agency filter and community short name

assets/js/backbone/apps/apply/templates/internship_education_template.html, assets/styles/layouts/internship.scss
- Add HTML and CSS for uploaded transcripts
#2879
=> Add Transcript

api/application/controller.js, api/application/service.js, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/internships/show/templates/internship_view.html, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/js/backbone/browse-app.js, assets/js/backbone/components/modal.js
- Do not allow non students to apply to internships
- Update footer based on page
#2701
#2785
=> Student internship

migrations/20190129180851-add-bureau-table.js, migrations/20190129184834-add-office-table.js, migrations/20190129202704-import-bureau-data.js, utils/bureau-data.js, utils/bureau-data.json
Adding import of bureau and office data into open opps
#2671
=> Adding import of bureau and office data into open opps

assets/js/backbone/apps/tasks/search/views/internship_search_view.js, migrations/20190131012427-update-community-name-dos-to-community-table.js, migrations/20190131122019-update-community-name-vsfs-to-community-table.js
- Add period for unpaid internship
- Add acronym VSFS
#2897,#2701,#2704,#2798
=> Student shell page update radio button names

assets/js/backbone/apps/apply/templates/internship_statement_template.html, assets/js/backbone/apps/tasks/search/templates/internship_search_item.html, assets/js/backbone/apps/tasks/search/templates/task_search_item.html, assets/js/backbone/config/tag.js, assets/js/backbone/mixins/templates/popover_profile.html
- Update location icon to match design system
#2935
=> Update Location Icon

api/autocomplete/controller.js, api/autocomplete/dao.js, api/autocomplete/service.js, assets/js/backbone/apps/internships/edit/templates/internship_edit_form_template.html, assets/js/backbone/apps/internships/edit/views/internship_edit_form_view.js
=> Do not require state when a country has none.

api/cycle/controller.js, api/cycle/service.js, api/opportunity/controller.js, api/opportunity/dao.js, api/opportunity/service.js, assets/js/backbone/apps/tasks/search/templates/internship_search_item.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/js/backbone/apps/tasks/search/views/task_search_view.js, elastic/dao.js, elastic/service.js, elastic/task_mapping.json
Changed filters to load on initialize instead of loading on each search. Also updated the cycle date we use on search to the apply date and not the posting date. 
#2654
=> Performance improvements to search and cycle date search logic changes

assets/js/backbone/apps/apply/templates/internship_review_template.html, assets/styles/app/pages/_search.scss, assets/styles/layouts/internship.scss
- Initial check-in for HTML
- Updated CSS
#2882
=> Department of State: Review Application

assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/js/backbone/apps/tasks/search/views/task_search_view.js, elastic/dao.js, elastic/service.js, elastic/task_mapping.json
Fixing issue where internships would show on normal search page
#2825
=> Fixing issue where internships would show on normal search page

assets/js/backbone/apps/apply/templates/internship_add_language_template.html, assets/js/backbone/apps/apply/templates/internship_language_template.html
- Initial check-in of HTML
- Update CSS
#2880
=> Department of State: Languages

assets/js/backbone/apps/apply/templates/internship_add_experience_template.html, assets/js/backbone/apps/apply/templates/internship_add_reference_template.html, assets/js/backbone/apps/apply/templates/internship_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/styles/layouts/internship.scss
- Initial check-in for HTML, CSS, and JS
#2878
=> Department of State: Experience

assets/js/backbone/apps/internships/show/templates/internship_view.html
=> Unpaid Internship community name

api/auth/controller.js, api/auth/passport.js, api/auth/profile.js, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/login/templates/unauthorized.html, assets/js/backbone/apps/profiles/show/templates/profile_show_template.html, migrations/20190205140225-add-is-us-citizen-to-user-table.js
- Sync IsUSCitizen boolean from USAJOBS Profile
- refactor and update some code issues
#2877
=> Pull citizenship from USAJOBS profile

assets/js/backbone/apps/apply/templates/apply_ineligible_citizenship_template.html, assets/js/backbone/apps/internships/show/views/internship_view.js, assets/js/backbone/browse-app.js
- Added check for U.S. citizenship
- Added new route to send ineligible applicants to
- Added Back to results link to page
#2877
=> Department of State: Ineligible Citizenship

migrations/20190206161621-add-step-column-to-application-table.js
Script to add coumn for current step to application table.
#2789
=> Department of State - Progress Bar

migrations/20190206123905-add-columns-to-application-table.js, migrations/20190206133002-change-or-remove-columns-to-education-table.js
- Add ,remove, change columns in application and education table
#2879
=> Education and Transcript

assets/js/backbone/apps/tasks/search/templates/internship_search_template.html, assets/js/backbone/apps/tasks/search/views/internship_search_view.js, elastic/service.js
Corrected location on internship page as well as placed the term parameter in the keyword field if a refresh of the page occurs
#2671
=> correct location on internship and place term in keyword field on reload

assets/js/backbone/apps/apply/templates/process_flow_template.html
- Update HTML to show DoS Student Internship Program logo
#2789
=> Update Logo for Progress Bar

assets/js/backbone/apps/tasks/search/views/internship_search_view.js
updating the placeholder text for office
#2711
=> updating the placeholder text for office

assets/js/backbone/apps/error/templates/whoops.html, assets/styles/app/pages/_homeview.scss
- Created whoops page for errors.
#2785
=> Create Whoops Page

assets/js/backbone/apps/tasks/search/views/internship_search_view.js, assets/js/backbone/apps/tasks/search/views/task_search_view.js, elastic/service.js
refactored how filters are stored in the url. also did performance tuning on search call
#2711
=> refactored filters in url for search and optimized search call

assets/js/backbone/apps/apply/templates/apply_ineligible_citizenship_template.html, assets/js/backbone/apps/profiles/home/internships/templates/internships_applied_template.html, assets/js/backbone/apps/profiles/home/internships/templates/internships_saved_template.html
- Make column widths the same
#2459
=> Landing Page: Student user signed in landing page

assets/js/backbone/apps/apply/templates/apply_add_language_template.html, assets/js/backbone/apps/apply/templates/apply_language_template.html, assets/js/backbone/apps/apply/views/apply_view.js
Initial check in of language code.
#2880
=> Department of State: Languages 

assets/js/backbone/apps/tasks/search/views/internship_search_view.js
Resetting page count to 1 when adding bureau, office, or agency filters
#2711
=> Resetting page count to 1 when adding bureau, office, or agency filters

api/cycle/service.js
Added check for overlapping cycles when adding a new cycle. If an overlapping cycle is found, An error message is thrown with the cycle it is overlapping with.
#2988
=> Added check for overlapping cycles when adding a new cycle

api/auth/passport.js, api/auth/profile.js
- Fix issue where student email changes were not being updated
=> Update student profile email

api/auth/passport.js
- Fix issue where linked id value was not being set
=> Linking USAJOBS and OpenOpps accounts

api/application/controller.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js
Added ability to insert experience page as part of app guide experience page
#2878
=> Added ability to insert experience records

api/application/controller.js, api/application/dao.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_add_education_template.html, assets/js/backbone/apps/apply/templates/apply_education_preview_template.html, assets/js/backbone/apps/apply/templates/apply_education_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js, assets/js/backbone/apps/apply/views/templates.js, assets/styles/layouts/internship.scss
- Move education code to new file
- Add edit section
#2879
=> Department of state Education

assets/js/backbone/apps/apply/templates/apply_ineligible_gpa_template.html
=> Ineligible Gpa

api/application/controller.js, api/application/dao.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_program_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/internships/show/views/internship_view.js
- Fix back button on step 1
- Add ability for student to delete a program selection.
#2785
=> Student internship application 

api/application/dao.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/language.js
Adding education and experience to the initial application load. Also updated the experience page to now use the experience loaded from the application
#2878
=> Adding education and experience to the initial application load

assets/js/backbone/apps/apply/templates/apply_congratulations_template.html, assets/js/backbone/apps/apply/views/apply_congratulations_view.js
- Created generic javascript for drawers when only one can be open
- Created generic javascript for accordions when only one can be open
#2994
=>  Department of State: Right Rail of Submission Confirmation Page

assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js, assets/styles/layouts/internship.scss
=> Fix Merge conflicts

assets/js/backbone/apps/apply/templates/apply_statement_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/statement.js
- Move Statement of Interest functions to separate file
- Add generic drawer javascript
#2881
=> Department of State: Statement of Interest

assets/js/backbone/apps/apply/templates/apply_program_template.html, assets/styles/layouts/internship.scss
- Add sorting arrows to internship opportunity choices
- Add CSS
#2785
=> Add Sorting Arrows to Choices

api/application/controller.js, api/application/dao.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js
Adding delete functionality for experience records also coded a generic delete record modal that all pages can use in the future
#2878
=> Adding delete functionality for experience records

api/application/dao.js, api/application/service.js
- Refactor data pull for application lookup by id
=> Student internship application

assets/js/backbone/apps/apply/templates/apply_education_preview_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js
- Fix drawer data education
#2879
=> Dos Education

api/application/service.js, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js, utils/bureau-data.js
Converting add experience and delete experience to use the new data loading strategy
#2878
=> Updated experience templates and apis to leverage new loading strategy

api/application/controller.js, api/application/dao.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_language_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/language.js
Delete function, drawer view of language details, update queries with language name. 
#2880
=>  Department of State: Languages

assets/js/backbone/apps/apply/templates/apply_statement_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/statement.js, assets/styles/layouts/internship.scss
- Add validation to statement of interest page
- Remove duplicate functions from apply_view
#2881
=> Add Validation to Statement of Interest

README.md, assets/js/backbone/apps/tasks/show/views/task_item_view.js, package-lock.json, package.json
Fixes issue in production around applying to opportunities.
=> Production hotfix version 7.5.18

assets/js/backbone/apps/apply/views/statement.js
- Add update application step to Statement of interest page
#2881
=> Add Update Application Step to Statement of Interest

api/application/controller.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js
Adding ability to update experience on the experience page
#2878
=> Adding ability to update experience on the experience page

assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js
Added retention for experience questions when adding or updating experience
#2878
=> Added retention for experience questions when adding or updating experience

assets/js/backbone/apps/apply/templates/apply_education_preview_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js
- Fix retain data main education when edit
- Fix displaying Ineligible gpa page
#2879
=> Education Dos

assets/js/backbone/apps/apply/templates/apply_education_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/education.js, migrations/20190226165845-rename-column-to-application-table.js, migrations/20190227141013-change-columns-to-application-table.js
- update database table values to radio buttons
- Add migration to correct misspelling column name
- fix showing progress bar after saving
#2879
=> Education Transcript DOS

api/application/controller.js, api/application/service.js, assets/js/backbone/apps/apply/templates/apply_add_experience_template.html, assets/js/backbone/apps/apply/templates/apply_add_reference_template.html, assets/js/backbone/apps/apply/templates/apply_experience_template.html, assets/js/backbone/apps/apply/views/apply_view.js, assets/js/backbone/apps/apply/views/experience.js
Adding delete, insert, and view functionality for references. Edit to come shortly
#2921
=> Adding delete, insert, and view functionality for references

assets/js/backbone/apps/apply/templates/process_flow_template.html
- Update title on hover for Select Internships (Step 1)
#2789
=> Update Title for Select Interships
